keyteki/keyteki

README.md

Updated link to correctly point to keyteki file instead of ringteki; also fixed another reference to L5R in text

Updating incorrect link to implementing cards

---

.dockerignore
.gitignore
Dockerfile
README.md
config/default.json5
docker-compose.yml
package-lock.json
package.json
server/gamenode/Dockerfile
server/gamenode/gameserver.js
server/gamenode/zmqsocket.js
server/gamerouter.js
server/scripts/fetchdata.js

Based on work by Achocholacek.
Fixes #13

Add docker containerisation

---

server/game/cards/01-Core/SelwynTheFence.js
server/game/cards/02-AoA/AbondTheArmorsmith.js
server/game/cards/02-AoA/AubadeTheGrim.js
server/game/cards/02-AoA/BaronMengevin.js
server/game/cards/02-AoA/BarristerJoya.js
server/game/cards/02-AoA/BordanTheRedeemed.js
server/game/cards/02-AoA/BrobnarAmbassador.js
server/game/cards/02-AoA/DisAmbassador.js
server/game/cards/02-AoA/EyeOfJudgement.js
server/game/cards/02-AoA/FreeMarkets.js
server/game/cards/02-AoA/GoldenAura.js
server/game/cards/02-AoA/HaedrothsWall.js
server/game/cards/02-AoA/HallowedShield.js
server/game/cards/02-AoA/HealingBlast.js
server/game/cards/02-AoA/LionBautrem.js
server/game/cards/02-AoA/LogosAmbassador.js
server/game/cards/02-AoA/MarsAmbassador.js
server/game/cards/02-AoA/MartyrsEnd.js
server/game/cards/02-AoA/MotherNorthelle.js
server/game/cards/02-AoA/OpalKnight.js
server/game/cards/02-AoA/PrinceDerricUnifier.js
server/game/cards/02-AoA/SeraphicArmor.js
server/game/cards/02-AoA/ShadowsAmbassador.js
server/game/cards/02-AoA/ShardOfHope.js
server/game/cards/02-AoA/SirMarrows.js
server/game/cards/02-AoA/TheGreyRider.js
server/game/cards/02-AoA/UntamedAmbassador.js

Added [Sanctum] Bordan the Redeemed
Added [Sanctum] Lion Bautrem
Added [Sanctum] The Grey Rider
(Tested fine locally. Hope I'm doing this right!)

Added a few Sanctum Cards

---

server/game/GameActions/RandomDiscardAction.js

This allows a call along the lines of
gameAction: ability.actions.discardAtRandom({ amount: 1, location: 'archive'}) or location: 'hand'
(this was to accommodate Tantadlin, who does this, like an asshole.

Modified RandomDiscardAction.js action to allow for 'location' var

---

server/game/cards/02-AoA/Roxador.js
server/game/cards/02-AoA/StormCrawler.js

Takes advantage of newly added limitFightDamage effect.
Tantadlin will require a re-write of the random discard function to accommodate archives, but I'm gonna give it a whirl.

Add Roxador/StormCrawler

---

docker-compose.yml

* Moved to version 3.3 syntax.
* Volume adjustments to only use shares as required.

docker-compose.yml changes to fix issues with Docker on some systems.

---

README.md

When I tried to run via docker, it failed. After running those 2 commands, it worked.

Add missing steps to build/run via docker

---

server/game/cards/02-AoA/ShardOfGreed.js
server/game/cards/02-AoA/ShardOfHate.js
server/game/cards/02-AoA/ShardOfKnowledge.js

The shards seem to work but the Mars one produces errors:
```
node_1   | 2019-07-23T09:52:35.688Z - error:  message=Cannot read property 'getEventArray' of null, stack=TypeError: Cannot read property 'getEventArray' of null
node_1   |     at SimpleStep.continueFunc (/usr/src/node/server/game/GameActions/SequentialForEachAction.js:44:84)
node_1   |     at SimpleStep.continue (/usr/src/node/server/game/gamesteps/simplestep.js:10:21)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at EventWindow.continue (/usr/src/node/server/game/gamesteps/basestepwithpipeline.js:37:42)
node_1   |     at GamePipeline.continue (/usr/src/node/server/game/gamepipeline.js:105:36)
node_1   |     at AbilityResolver.continue …
```

Add missing Shards (Logos, Mars, Shadows)

---

server/game/cards/02-AoA/GuardDisguise.js
server/game/cards/02-AoA/HeistNight.js
server/game/cards/02-AoA/Nightforge.js
server/game/cards/02-AoA/PerplexingSophistry.js
server/game/cards/02-AoA/RiggedLottery.js
server/game/cards/02-AoA/SackOfCoins.js

Rigged Lottery and Sack of Coins

Guard Disguise, Height Night, Nightforge, Perplexing Sophistry, 

---

server/game/cards/01-Core/Shaffles.js
server/game/cards/02-AoA/Grovekeeper.js
server/game/cards/02-AoA/Redlock.js
test/helpers/integrationhelper.js
test/server/cards/02-AoA/HeartOfTheForest.spec.js
test/server/cards/02-AoA/Redlock.spec.js

~~NOTE: the Redlock test might be bugged, submitting PR to let you check it out~~
Should be fine now

Added Redlock and a couple tests

---

server/game/cards/02-AoA/MasterTheTheory.js
server/game/cards/02-AoA/ProjectZYX.js
server/game/cards/02-AoA/QuantumFingertrap.js

https://github.com/keyteki/keyteki/issues/5

Added Logos: Master The Theory, Project Z.Y.X., and Quantum Fingertrap

---

server/game/cards/01-Core/WildWormhole.js
server/game/cards/02-AoA/1-2Punch.js
server/game/cards/02-AoA/DirectorOfZyx.js
server/game/cards/02-AoA/GoldenAura.js
test/server/cards/02-AoA/1-2Punch.spec.js

Fixes #81 
Fixes #84 
Fixes #82 
Fixes #86

Misc bugfixes

---

server/game/cards/02-AoA/BinateRupture.js
test/server/cards/02-AoA/BinateRupture.spec.js

Fix binate rupture's first effect

---

server/game/cards/01-Core/Oubliette.js
server/game/cards/02-AoA/GargantesScrapper.js
test/server/cards/01-Core/Oubliette.spec.js
test/server/cards/02-AoA/GargantesScrapper.spec.js

Fix gargantes scrapper

---

server/game/Card.js
server/game/cards/02-AoA/HeartOfTheForest.js
server/game/cards/02-AoA/PunctuatedEquilibrium.js
server/game/cards/02-AoA/SoldiersToFlowers.js
test/server/cards/02-AoA/FilaTheResearcher.spec.js

Fixes KEYTEKI-5
Fixes KEYTEKI-6
Fixes KEYTEKI-9
Fixes #104

Fix sentry errors

---

server/game/deck.js
server/services/DeckService.js

Record which set a deck is from when it's imported

---

server/game/GameActions/DealDamageAction.js
test/server/cards/02-AoA/MaruckTheMarked.spec.js

Remove incorrect damagePrevented assignment

---

server/game/cards/02-AoA/FreeMarkets.js
server/game/cards/02-AoA/Murkens.js

Fixes KEYTEKI-N
Fixes KEYTEKI-M

Fix a couple more sentry issues

---

server/game/cards/02-AoA/PanpacaJaga.js
server/game/gamesteps/main/actionwindow.js

Panpaca Jaga fix

---

server/game/Card.js
server/game/cards/02-AoA/PainReaction.js
server/game/cards/02-AoA/Tezmal.js
server/game/cards/02-AoA/WarGrumpus.js

Fixes #120 
Fixes #113 
Fixes #110

More bugfixes

---

server/game/cards/02-AoA/BarristerJoya.js

Barrister Joya bugfix

---

server/game/cards/02-AoA/Dharna.js
server/game/cards/02-AoA/LittleRapscal.js
server/game/cards/02-AoA/PrinceDerricUnifier.js

Dharna bugfix

---

server/game/BaseActions/PlayArtifactAction.js
server/game/BaseActions/PlayCreatureAction.js
server/game/BaseActions/PlayUpgradeAction.js
test/server/cards/02-AoA/Murkens.spec.js

Murkens bug fix

---

server/game/cards/02-AoA/Bumblebird.js
server/game/cards/02-AoA/DuskChronicles.js
server/game/cards/02-AoA/ProjectZYX.js

Bumblebird bugfix

---

server/game/cards/01-Core/WildWormhole.js
server/game/cards/02-AoA/BarristerJoya.js
server/game/cards/02-AoA/Equalize.js
server/game/cards/02-AoA/EyeOfJudgement.js
server/game/cards/02-AoA/Foozle.js
server/game/cards/02-AoA/GrumpBuggy.js
server/game/cards/02-AoA/LittleRapscal.js
server/game/cards/02-AoA/Proclamation346E.js
server/game/cards/02-AoA/SignalFire.js
server/game/cards/02-AoA/Smite.js
server/game/cards/02-AoA/StandardisedTesting.js

More Misc bugfixes

---

server/game/cards/02-AoA/EyeOfJudgement.js

Was causing card not to work.
https://github.com/keyteki/keyteki/issues/155

fixed ID for eye of judgment

---

server/game/cards/02-AoA/MightMakesRight.js
server/game/cards/02-AoA/RiggedLottery.js
server/game/cards/02-AoA/TheFlex.js

fixes https://github.com/keyteki/keyteki/issues/163

Flex fix to target only player's controlled creatures

---

server/game/cards/01-Core/SoulSnatcher.js

https://github.com/keyteki/keyteki/issues/136

Added Effect text to make the log correct re: aember gain

---

server/game/cards/02-AoA/MightMakesRight.js

https://github.com/keyteki/keyteki/issues/141

Added 'self' qualifier on targeting.

---

server/game/cards/02-AoA/Ogopogo.js
test/server/cards/02-AoA/Ogopogo.spec.js

Ogopogo fix + test - should now only fire when Ogopogo is attacker.

---

server/game/cards/02-AoA/BrobnarAmbassador.js
server/game/cards/02-AoA/DisAmbassador.js
server/game/cards/02-AoA/LogosAmbassador.js
server/game/cards/02-AoA/MarsAmbassador.js
server/game/cards/02-AoA/ShadowsAmbassador.js
server/game/cards/02-AoA/UntamedAmbassador.js

Fixed Ambassador abilties so they work on both Fight/Reap

---

server/game/cards/02-AoA/Fetchdrones.js

https://github.com/keyteki/keyteki/issues/154

Fetchdrones fix to capture 2A instead of 1A

---

server/game/cards/02-AoA/LittleRapscal.js

Another Little Rapscal bugfix

---

server/game/GameActions/PutIntoPlayAction.js

Fix deploy when it's used on the left flank

---

server/game/cards/02-AoA/SeismoEntangler.js
test/server/cards/02-AoA/SeismoEntangler.spec.js

Fix for SeismoEntangler & Test for SeismoEntangler

---

server/game/cards/02-AoA/ForgemasterOg.js
test/server/cards/02-AoA/ForgemasterOg.spec.js

Fixes #159 
Fixes #214 
Adds Test.

Fixed Forgemaster Og + added Test.

---

client/pages/UserAdmin.jsx
server/api/account.js
server/api/user.js
server/models/User.js

Don't allow tokens to be refreshed for disabled accounts
Add list of IPs to the useradmin screen
Fixes #209

Fix banned users

---

server/game/cards/02-AoA/ShadowOfDis.js
test/server/cards/02-AoA/ShadowOfDis.spec.js

Fix Shadow of Dis to only affect creatures + add test

---

test/helpers/playerinteractionwrapper.js
test/server/cards/02-AoA/Lamindra.spec.js

Updated PlayerInteractionWrapper to allow for deploy scripting

---

server/game/cards/01-Core/MothershipSupport.js
server/game/cards/01-Core/OrbitalBombardment.js
server/game/cards/02-AoA/FirstBlood.js
server/game/cards/02-AoA/OrtannuTheChained.js
test/server/cards/01-Core/MothershipSupport.spec.js
test/server/cards/02-AoA/FirstBlood.spec.js

First Blood - allow damage dealt however player prefers + test

---

server/game/cards/02-AoA/ProjectZYX.js

Made Project Z.Y.X's reap ability optional.

---

server/game/cards/02-AoA/NiffleGrounds.js
test/server/cards/02-AoA/NiffleGrounds.spec.js

Fix Niffle Grounds affecting Non-creature cards. Add Test for Niffle Grounds

---

server/game/cards/02-AoA/MightMakesRight.js
test/server/cards/02-AoA/MightMakesRight.spec.js

No longer forges if you select less than 25 power worth of creatures.
Updated test with proper functions for archiving process.
Fixes #171 
Fixes #173

Fix for Might Makes Right/Test

---

server/game/cards/01-Core/MobiusScroll.js
server/game/cards/01-Core/RitualOfBalance.js
server/game/cards/02-AoA/Hexpion.js
test/server/cards/01-Core/MobiusScroll.spec.js
test/server/cards/01-Core/RitualOfBalance.spec.js

- Ritual of Balance is now exhausted when used by an opponent (Nexus, Remote Access) even if the condition isn't met
- Mobius Scroll is now archived in the owner's archives when used by an opponent (Nexus, Remote Access).
- Same as above for Hexpion (which can change controller)

Couple bug fixes

---

server/game/cards/01-Core/Protectrix.js
test/server/cards/01-Core/Protectrix.spec.js

Fix Protectrix' reap ability applying to undamaged creatures. Added test

---

server/game/cards/02-AoA/FreeMarkets.js

Fix play text to make amber gain clearer. Condense function as per Jadiel's suggestion

---

server/game/cards/02-AoA/MightMakesRight.js

Fixed MMR not forging if exactly 25 power worth of creatures are sacrificed

---

client/Components/GameBoard/AbilityTargeting.jsx
client/Components/GameBoard/CardImage.jsx
server/game/Card.js
server/game/gamechat.js

Fix maverick in AbilityTargeting. I needed to include some changes in Card.js to return data a bit more information from backend.

UI: Fix maverick in AbilityTargeting (#293)

---

server/game/cards/02-AoA/HallowedShield.js

Fix for Hallowed Shield applying to entire board rather than just target.

---

server/game/cards/02-AoA/BrobnarAmbassador.js
server/game/cards/02-AoA/DisAmbassador.js
server/game/cards/02-AoA/LogosAmbassador.js
server/game/cards/02-AoA/MarsAmbassador.js
server/game/cards/02-AoA/ShadowsAmbassador.js
server/game/cards/02-AoA/UntamedAmbassador.js
server/game/costs.js
server/game/effects.js

Fixes #189 (and all other ambassadors)

Fix for Ambassadors. no longer requires immediate play/use choice.

---

server/game/GameActions/RevealAction.js
server/game/cards/01-Core/WildWormhole.js
test/server/cards/01-Core/ChampionsChallenge.spec.js
test/server/cards/01-Core/Poltergeist.spec.js

Fix wild wormhole's reveal action

---

README.md
server/scripts/fetchdata.js
server/scripts/fetchdata/CardImport.js
server/scripts/fetchdata/KeyforgeImageSource.js

Updated script to download images for various languages

I18n scripts

---

server/game/cards/02-AoA/Neffru.js
test/server/cards/01-Core/Krump.spec.js
test/server/cards/02-AoA/Neffru.spec.js

Added Neffru Test and Krump Test.

Fixed Neffru awarding opponent an aember if he was attacked and both died. 

---

server/game/GameActions/DrawAction.js
server/game/gamesteps/draw/drawphase.js

Make sure the draw action is performed if we should be shedding chains

---

server/game/GameActions/ReturnToDeckAction.js

Modifies ReturnToDeckAction's game message when shuffle option is true (#358)

Modifies ReturnToDeckAction's game message when shuffle option is true

---

server/game/cards/02-AoA/MotherNorthelle.js
server/game/cards/02-AoA/NotFinishedWithYou.js

Fixed two cosmetic bugs (#378 and #379)

Fixed two cosmetic bugs (#378 and #379)

---

server/game/cards/02-AoA/ShardOfGreed.js
test/server/cards/02-AoA/ShardOfGreed.spec.js

Not the "best" way but it works for right now. Will need to be re-evaluated when we adjust use actions to reflect a temporary change of ownership.
Fixes #302

add fix for shard of greed to work with remote access. add tests.

---

client/reducers/cards.js
server/game/GameActions/ReturnToDeckAction.js

Fixes the order of newly imported deck and select the new deck (#350)

Fixes the order of newly imported deck

---

server/game/cards/01-Core/RoutineJob.js

Fixes RoutineJob.js message to be more precise on the amount of amber stolen (#336)

Fixes RoutineJob.js message (#336)

---

server/game/player.js

(e.g. Sneklifter effect) (#139)

Consider changeHouse when getting available houses for prompt (#139)

---

server/game/cards/01-Core/StealerOfSouls.js

StealerOfSouls message now says player gains 1 amber (#373)

StealerOfSouls message now says player gains 1 amber (#373)

---

server/game/cards/02-AoA/Smite.js
test/server/cards/02-AoA/Smite.spec.js

Fixed Smite hitting stunned creatures (#387)

Fixed Smite hitting stunned creatures (#387)

---

client/Components/GameBoard/PlayerRow.jsx
less/gameboard.less

Implemented it like other droppable piles.

Purged pile is now a Droppable pile (#382)

---

package-lock.json
server/game/GameActions/PutIntoPlayAction.js

as this is what the moveCard funciton uses.
This should remove the deploy weirdness that people have been reporting
Fixes #97

Use the cardsInPlay array when calculating the deploy index

---

server/game/GameActions/SearchAction.js
test/server/cards/01-Core/BearFlute.spec.js

Added extra test for bear flute.
Fixes #310

Modified SearchAction to properly shuffle discard back into deck. 

---

client/Components/Site/NavBar.jsx

Fixed unsupported languages to fallback to english

Fixed unsupported languages to fallback to english

---

server/game/Card.js

Suggested fix for proper glow of controlled card and omni card

---

server/game/Card.js
server/game/game.js
server/game/gamesteps/draw/drawphase.js

(not sure why the Card.js change is here, though)
Attempt to fixes #428

 Attempt to fix the check statement before collecting "after round" ambers by Redlock

---

server/game/cards/02-AoA/SirMarrows.js

Added a more specific game message to Sir Marrows

---

server/game/cards/01-Core/Dysania.js
test/server/cards/01-Core/Dysania.spec.js

Consider only own cards in archive

---

client/Components/GameBoard/Card.jsx
less/cards.less
less/gameboard.less
less/variables.less

Final changes to fix archived not showing controlled creatures

---

server/game/cards/01-Core/Mimicry.js
server/game/gamesteps/abilityresolver.js
test/server/cards/01-Core/Mimicry.spec.js

Fixes #107
Fixes #180
Fixes #348

Expand the list of locations mimicry can trigger from.

---

client/Components/GameBoard/ActivePlayerPrompt.jsx
client/Components/GameBoard/Card.jsx
client/Components/GameBoard/DrawDeck.jsx
client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerRow.jsx
client/Components/GameBoard/PlayerStats.jsx
client/Components/GameBoard/SquishableCardPanel.jsx
client/Components/Site/ErrorBoundary.jsx
public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/Card.js
server/game/CardSelectors/UpToXCardSelector.js
server/game/GameActions/ChosenDiscardAction.js
server/game/game.js
server/game/gamesteps/GameWonPrompt.js
server/game/gamesteps/ManualModePrompt.js
server/game/gamesteps/RematchPrompt.js
server/game/gamesteps/handlermenuprompt.js
server/game/gamesteps/setup/GameStartPrompt.js
server/game/player.js
server/services/CardService.js
test/helpers/playerinteractionwrapper.js

Server side i18n commit which includes:
- Server side prompt text
- Active player prompt
- locale updates
Relates to (#2)

Server side i18n commit which includes:

---

server/game/GameActions/PutIntoPlayAction.js
test/server/cards/01-Core/SpanglerBox.spec.js

Do not consider "Deploy" when creature is put into play only.

---

server/game/GameActions/DealDamageAction.js
server/game/cards/01-Core/RedhotArmor.js
test/server/cards/01-Core/ShieldOfJustice.spec.js
test/server/cards/02-AoA/MaruckTheMarked.spec.js

Fixes #192 Redhot armor should not allow Maruck to capture amber
Fixes #412 Dealing damage when it cannot affect a target should not reduce armor

Fixes Maruck bugs

---

client/Components/GameBoard/IdentityCard.jsx
client/Components/GameBoard/PlayerRow.jsx
less/common.less
less/site.less

in time to be rendered on the id card
Fix the less files to properly references the files in the bundle
Fix the id card for when there is no player 2

Add a dummy div so the font is preloaded

---

client/Components/GameBoard/IdentityCard.jsx

Might be safer to access this inside Promise

Using this.props inside Promise

---

server/game/cards/01-Core/CombatPheromones.js

Adjusted CombatPheromones' game message

---

client/ReduxActions/misc.js
client/index.dev.jsx
client/index.prod.jsx
client/reducers/navigation.js

Manage browser history properly

---

server/game/GameActions/RemoveStunAction.js

Found while developing the WC ward feature

Fix RemoveStunAction class name

---

server/game/Card.js

Bug fix for checkRestrictions

---

server/game/cards/02-AoA/Exhume.js

Make exhume's targetting optional as it's a 'may' ability

---

server/game/cards/01-Core/RelentlessWhispers.js
test/server/cards/01-Core/RelentlessWhispers.spec.js

Bug probably as leftover dead code after refactoring for the redirect damage change

Fixed a small bug on RW that wasn't stealing properly after destroying

---

server/game/GameActions/ReturnAmber.js
server/game/cards/03-WC/AVinda.js
server/game/cards/03-WC/BreakerHill.js
server/game/cards/03-WC/HitAndRun.js
server/game/cards/03-WC/Hock.js
server/game/cards/03-WC/HuggerMugger.js
server/game/cards/03-WC/InkyGloom.js
server/game/cards/03-WC/JVinda.js
server/game/cards/03-WC/KymoorEclipse.js
server/game/cards/03-WC/Mug.js
server/game/cards/03-WC/PesteringBlow.js
server/game/cards/03-WC/SpikeTrap.js
server/game/cards/03-WC/SubtleChain.js
server/game/cards/03-WC/Symon.js
server/scripts/copycard.js
test/server/cards/03-WC/AVinda.spec.js
test/server/cards/03-WC/BreakerHill.spec.js
test/server/cards/03-WC/HitAndRun.spec.js
test/server/cards/03-WC/Hock.spec.js
test/server/cards/03-WC/HuggerMugger.spec.js
test/server/cards/03-WC/InkyGloom.spec.js
test/server/cards/03-WC/JVinda.spec.js
test/server/cards/03-WC/KymoorEclipse.spec.js
test/server/cards/03-WC/Mug.spec.js
test/server/cards/03-WC/PesteringBlow.spec.js
test/server/cards/03-WC/SpikeTrap.spec.js
test/server/cards/03-WC/SubtleChain.spec.js
test/server/cards/03-WC/Symon.spec.js

Added shadows cards/tests

---

server/game/cards/03-WC/BrobnarPlant.js
server/game/cards/03-WC/DisPlant.js
server/game/cards/03-WC/LogosPlant.js
server/game/cards/03-WC/SaurianPlan.js
server/game/cards/03-WC/SaurianPlant.js
server/game/cards/03-WC/StarAlliancePlant.js
server/game/cards/03-WC/UntamedPlant.js
test/server/cards/03-WC/BrobnarPlant.spec.js
test/server/cards/03-WC/DisPlant.spec.js
test/server/cards/03-WC/Imperium.spec.js
test/server/cards/03-WC/LogosPlant.spec.js
test/server/cards/03-WC/SaurianPlant.spec.js
test/server/cards/03-WC/StarAlliancePlant.spec.js
test/server/cards/03-WC/UntamedPlant.spec.js

Depend on https://github.com/keyteki/keyteki-json-data/pull/14

Shadows' plants (depend on keyteki-json-data)

---

test/helpers/playerinteractionwrapper.js
test/server/cards/03-WC/SpikeTrap.spec.js

Enhance useAction to allow omni ability. Backward compatible.

Enhance useAction to allow omni ability.

---

server/game/cards/01-Core/TirelessCrocag.js
test/server/cards/01-Core/TirelessCrocag.spec.js

Fix for Tireless Crocag issue / test.

---

server/game/cards/01-Core/SeekerNeedle.js

SeekerNeedle now says gain 1 amber

---

test/server/cards/01-Core/WitchOfTheEye.spec.js

For #535 - added a test case for witch of the eye, but could not reproduce the error.

Add test for witch of the eye

---

server/game/CardAbility.js
server/game/GameActions/LoseAmberAction.js
server/game/GameActions/ModifyChainsAction.js
server/game/cards/03-WC/AxiomOfGrisk.js
server/game/cards/03-WC/Fidgit.js
server/game/cards/03-WC/IgonTheGreen.js
server/game/cards/03-WC/SpikeTrap.js
server/game/cards/03-WC/TheFeatheredShaman.js
server/game/cards/03-WC/UnnaturalSelection.js
server/game/cards/03-WC/Whisper.js
test/server/cards/01-Core/Begone.spec.js
test/server/cards/03-WC/AxiomOfGrisk.spec.js
test/server/cards/03-WC/BrobnarPlant.spec.js
test/server/cards/03-WC/DisPlant.spec.js
test/server/cards/03-WC/Fidgit.spec.js
test/server/cards/03-WC/FirstOfficerFrane.spec.js
test/server/cards/03-WC/ForceField.spec.js
test/server/cards/03-WC/IgonTheGreen.spec.js
test/server/cards/03-WC/LogosPlant.spec.js
test/server/cards/03-WC/Mug.spec.js
test/server/cards/03-WC/SaurianPlant.spec.js
test/server/cards/03-WC/SpikeTrap.spec.js
test/server/cards/03-WC/StarAlliancePlant.spec.js
test/server/cards/03-WC/TheFeatheredShaman.spec.js
test/server/cards/03-WC/UnnaturalSelection.spec.js
test/server/cards/03-WC/UntamedPlant.spec.js
test/server/cards/03-WC/Whisper.spec.js

Fixed a lint warning on FirstOfficerFrane.spec.js

Implemented new WC cards, QA of implemented cards, messaging enhancement

---

server/game/cards/02-AoA/Rustgnawer.js
test/server/cards/02-AoA/Rustgnawer.spec.js

fixed rustgnawer + added test

---

server/game/GameActions/CaptureAction.js
server/game/cards/03-WC/CityGates.js
server/game/cards/03-WC/DracoPraeco.js
server/game/cards/03-WC/SicSemperTyrannosaurus.js
server/game/cards/03-WC/Terrordactyl.js
server/game/cards/03-WC/Tertiate.js
test/server/cards/03-WC/CityGates.spec.js
test/server/cards/03-WC/DracoPraeco.spec.js
test/server/cards/03-WC/SicSemperTyrannosaurus.spec.js
test/server/cards/03-WC/Terrordactyl.spec.js
test/server/cards/03-WC/Tertiate.spec.js

City Gates, Draco Praeco, Sic Semper Tyrannosaurus, Terrordactyl, Tertiate

5 Saurian cards

---

client/Components/Games/GameLobby.jsx
client/Components/Site/Modal.jsx

to prevent clicking out of bounds from closing it

Add a setting to the modal dialog

---

server/game/cards/01-Core/RitualOfBalance.js
test/server/cards/01-Core/RitualOfBalance.spec.js

Fixes Ritual of Balance

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/CardSelectors/ExactlyXCardSelector.js
server/game/CardSelectors/UpToXCardSelector.js
server/game/cards/03-WC/Velum.js

Adjusted the prompts in the Card selectors

Fixes #591

---

server/game/cards/01-Core/YxiliMarauder.js
server/game/cards/03-WC/CincinnatusRex.js
server/game/cards/03-WC/PrimusUnguis.js
server/game/cards/03-WC/SowSalt.js
server/game/cards/03-WC/TribunePompitus.js
test/server/cards/01-Core/TirelessCrocag.spec.js
test/server/cards/01-Core/YxiliMarauder.spec.js
test/server/cards/03-WC/CincinnatusRex.spec.js
test/server/cards/03-WC/PrimusUnguis.spec.js
test/server/cards/03-WC/SowSalt.spec.js
test/server/cards/03-WC/TribunePompitus.spec.js

Added a few more saurian cards

---

server/game/PlainTextGameChatFormatter.js
server/game/game.js
server/game/gamesteps/setup/setupphase.js
server/gamenode/gameserver.js
test/helpers/integrationhelper.js

use it in sentry reports and after tests when a var is set

Add a method to dump the game log to plain text

---

server/game/Card.js
server/game/cards/01-Core/Firespitter.js
server/game/cards/01-Core/GabosLongarms.js
server/game/cards/01-Core/LordGolgotha.js
server/game/cards/01-Core/Zorg.js
server/game/cards/02-AoA/BingleBangBang.js
server/game/cards/02-AoA/Cowfyne.js
server/game/cards/02-AoA/Mindworm.js
server/game/cards/03-WC/EldestBear.js
server/game/cards/03-WC/FyreBreath.js
server/game/cards/03-WC/MegaCowfyne.js
server/game/cards/03-WC/PlasmaNozzle.js
server/game/cards/03-WC/Terrordactyl.js
server/game/cards/03-WC/TribunePompitus.js
server/game/effects.js
test/server/cards/03-WC/FyreBreath.spec.js
test/server/cards/03-WC/PlasmaNozzle.spec.js

use this instead of interrupt for clarity and to reduce repitition
fix fyre breath to use a gainsAbility

Add beforeFight convenience method

---

server/game/game.js
server/game/player.js
server/gamenode/gameserver.js
server/lobby.js

Don't consider a player to be disconnected until they've been gone for 30s

Make games a bit more disconnect tolerant

---

server/game/cards/03-WC/GeneralOrder24.js
test/server/cards/03-WC/GeneralOrder24.spec.js

Not completed yet, but can be edited by a maintainer.

General Order 24

---

server/game/cards/03-WC/FavorOfRex.js
test/server/cards/01-Core/Mindwarper.spec.js
test/server/cards/02-AoA/Replicator.spec.js
test/server/cards/03-WC/FavorOfRex.spec.js

Included Favor of Rex and a Replicator.spec.js scenario that is failing (xit'ed)

WC Favor of Rex

---

server/game/cards/01-Core/MightyLance.js
server/game/cards/01-Core/PositronBolt.js
test/server/cards/01-Core/MightyLance.spec.js
test/server/cards/01-Core/PositronBolt.spec.js
test/server/cards/cancreatecards.spec.js

PositronBolt and Spectral Tunneler

---

server/game/cards/03-WC/Harmonia.js
test/server/cards/03-WC/Harmonia.spec.js

Fixes WC Harmonia not granting amber when played herself

---

server/game/cards/01-Core/PawnSacrifice.js

Adjusts Pawn Sacrifice game message

---

client/Components/Lobby/UserList.jsx
client/ReduxActions/socket.js
client/pages/Lobby.jsx
client/pages/Login.jsx
client/reducers/lobby.js
server/api/account.js
server/lobby.js

only send new/update/removed games/users rather than broadcasting the whole list to everyone all of the time

Refactor the lobby to send less data

---

client/Components/Decks/DeckList.jsx
client/Components/Decks/ViewDeck.jsx
client/Components/Form/RadioGroup.js
client/Components/Games/SelectDeckModal.jsx
client/pages/Decks.jsx
less/common.less

Add paging, sorting, and some basic filtering to the deck list

---

server/game/cards/03-WC/Tribute.js
test/server/cards/03-WC/Tribute.spec.js

Tribute should ask to exalt only once

---

server/game/cards/03-WC/Buzzle.js
test/server/cards/03-WC/Buzzle.spec.js

Fixes Buzzle newly introduced - Sauryyyyy

---

server/game/Card.js
test/server/cards/03-WC/CaptainValJericho.spec.js
test/server/cards/03-WC/ChainGang.spec.js

Fixes center of line bug

---

test/server/cards/03-WC/Ghosthawk.spec.js

Add tests for ghosthawk

---

server/game/cards/03-WC/SciOfficerQincan.js
test/server/cards/03-WC/SciOfficerQincan.spec.js

Fix Qincan to always steal from opponent.  Refactor tests

---

server/game/cards/03-WC/BorrNitsTouch.js

Fix id for borr nit's touch

---

server/game/cards/03-WC/Fidgit.js
test/server/cards/03-WC/Fidgit.spec.js

Fidgit is a reap, not play ability

---

server/game/cards/03-WC/PrimusUnguis.js
test/server/cards/03-WC/PrimusUnguis.spec.js

Primus unguis applies to all friendly creatures, not just himself

---

server/game/cards/03-WC/LordInvidius.js
test/server/cards/03-WC/LordInvidius.spec.js

Fixes Lord Invidius granting abilities to other creatures

---

server/game/cards/03-WC/Zap.js
test/server/cards/03-WC/Zap.spec.js

Fixes Zap iterative damage

---

server/game/cards/03-WC/StiltKin.js
test/server/cards/03-WC/StiltKin.spec.js

Stilt-Kin can only attack when giant is played next to him

---

server/game/cards/03-WC/Crassosaurus.js
test/server/cards/03-WC/Crassosaurus.spec.js

crassosaurus fix for opp 10 amber capture

---

server/game/cards/03-WC/BookOfLeq.js
server/game/gamesteps/main/actionwindow.js
test/server/cards/03-WC/BookOfLeq.spec.js

Fixed leQ flag not being reset

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/03-WC/NepetaGigantica.js
test/server/cards/03-WC/NepetaGigantica.spec.js

Simplified the card and remove unused locales

Fix "Cannot read property 'choice' of undefined" on NepetaGigantica.

---

server/game/BaseActions/PlayUpgradeAction.js

When creatures are played as upgrades, effect should be permanent

---

server/game/cards/03-WC/MimicGel.js
test/server/cards/03-WC/MimicGel.spec.js

Fix mimic gel to not apply to all cards

---

server/game/cards/03-WC/Tribute.js
test/server/cards/03-WC/Tribute.spec.js

Fixed typo in "Tribute" -"exhalt" to "exalt".

---

server/game/cards/01-Core/RelentlessWhispers.js
test/server/cards/01-Core/RelentlessWhispers.spec.js

Fixes RW steal message not appearing

---

server/game/cards/02-AoA/ThrowingStars.js
test/server/cards/02-AoA/ThrowingStars.spec.js

Fix throwing stars when ward prevents damage

---

server/game/cards/02-AoA/Eyegor.js
test/server/cards/02-AoA/Eyegor.spec.js

Fix eyegor messaging(again)

---

server/game/cards/03-WC/ThoriumPlasmate.js

Fix messaging for throium plasmate

---

server/game/cards/03-WC/GeneralOrder24.js
test/helpers/playerinteractionwrapper.js
test/server/cards/03-WC/GeneralOrder24.spec.js

Fixes GeneralOrder24 not destroying itself

---

server/game/cards/03-WC/Buzzle.js
test/server/cards/03-WC/Buzzle.spec.js

Fix Buzzle.js when neighbor is warded
Fixes #850

Fix Buzzle.js target not defined

---

server/game/cards/03-WC/CincinnatusRex.js

Bug fix for Cincinnatus Rex

---

server/game/cards/01-Core/FinishingBlow.js
test/server/cards/01-Core/FinishingBlow.spec.js

Make FB message when it steals

---

server/game/costs.js
test/server/cards/02-AoA/BrobnarAmbassador.spec.js
test/server/cards/03-WC/AcademyTraining.spec.js
test/server/cards/03-WC/CXOTaber.spec.js
test/server/cards/03-WC/ComOfficerKirby.spec.js

Fixes cost calculation for houseEffects

---

server/game/cards/02-AoA/QuantumFingertrap.js
test/server/cards/02-AoA/QuantumFingertrap.spec.js

Fixes QuantumFingertrap Sentry error

---

server/game/cards/02-AoA/TheFlex.js
server/game/cards/03-WC/CXOTaber.js
server/game/cards/03-WC/ComOfficerKirby.js
server/game/cards/03-WC/CrashMuldoon.js
server/game/cards/03-WC/MedicIngram.js
server/game/cards/03-WC/Mug.js
server/game/cards/03-WC/SpikeTrap.js
test/server/cards/02-AoA/TheFlex.spec.js

fixes a few messaging issues

---

server/game/GameActions/ReturnToDeckAction.js

Fixes #805 
Sample output bellow using console.log to show it shuffled for both players:
```
Started
Shuffling after Troll player1
Shuffling after Streke player2
.
```

Fix ReturnToDeckAction to shuffle when card is the last card of the owner

---

server/game/Card.js
server/game/CardVisibility.js
server/game/cards/01-Core/ImperialTraitor.js
server/game/cards/03-WC/LateralShift.js
server/game/game.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js
test/server/cards/03-WC/LateralShift.spec.js

Merged a commit that seems to have been lost
Fixes #835
Also Fixes #881

Reveal Opponent's Hand (lost code)

---

server/game/cards/03-WC/Gebuk.js
test/server/cards/03-WC/Gebuk.spec.js

Fixed Gebuk being replaced by Artifact

---

server/game/cards/03-WC/PhalanxStrike.js
test/server/cards/03-WC/PhalanxStrike.spec.js

Fix PhalanxStrike not triggering twice

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/03-WC/TheGrimReaper.js
test/server/cards/03-WC/TheGrimReaper.spec.js

Adding reaping hook to reaper's hand

---

server/game/gamesteps/handlermenuprompt.js

Prompt menu buttons should consider the card house

---

client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/CardTiledList.jsx
client/Components/GameBoard/Counter.jsx
client/Components/GameBoard/PlayerRow.jsx
client/archonMaker.js
server/game/cards/02-AoA/YzphyzKnowdrone.js
test/server/cards/02-AoA/YzphyzKnowdrone.spec.js

Fix some display issues with opponents archives
prevent cards that are facedown from being zoomed
add tests for knowdrone
Fixes #128

Allow the opponent's archives to be opened

---

server/game/GameActions/FightGameAction.js
server/game/triggeredability.js
test/server/cards/02-AoA/BonerotVenom.spec.js

Raise an onUseCard event when a fight is triggered by an FightGameAction

---

server/game/GameActions/HealAction.js
server/game/cards/01-Core/CleansingWave.js
server/game/cards/01-Core/Protectrix.js
test/server/cards/01-Core/Protectrix.spec.js
test/server/cards/03-WC/SelfBolsteringAutomata.spec.js

Bug fix for SBA

---

server/game/cards/03-WC/CreedOfNature.js

Bugfix for Creed of Nature

---

server/game/cards/03-WC/TheShadowCouncil.js

The Shadow Council bug fix

---

server/game/cards/03-WC/GleefulMayhem.js
test/server/cards/03-WC/GleefulMayhem.spec.js

Rework Gleeful Mayhem

---

server/game/costs.js
test/server/cards/02-AoA/BrobnarAmbassador.spec.js

Fix ambassador not paying play/use costs

---

server/game/cards/03-WC/JVinda.js

Add J. Vinda stealing message

---

server/game/Card.js
server/game/cards/03-WC/Infurnace.js
test/server/cards/03-WC/Infurnace.spec.js

Changed Card.js to use this.cardPrintedAmber instead of accessing this.cardData.amber
Fixes #961

Fix Infurnace and Ether Spider interaction

---

server/game/costs.js
test/server/cards/01-Core/Tentacus.spec.js
test/server/cards/03-WC/Molephin.spec.js

pay cost effect is now a transferAmber instead of steal
Fixes #933

Fix pay being treated as steal

---

server/game/GameActions.js
server/game/GameActions/ShuffleDeckAction.js
server/game/GameActions/index.js
server/game/cards/03-WC/BorrNit.js
test/server/cards/03-WC/BorrNit.spec.js

Add a Shuffle Action to fix Borr Nit

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/03-WC/Malison.js

Fixes #908
Added some missing locale keys

Adjusted Malison effect message

---

server/game/cards/03-WC/Keyforgery.js
test/server/cards/03-WC/Keyforgery.spec.js

Keyforgery now logs the selected house

---

server/game/cards/03-WC/DracoPraeco.js

Fix Draco Praeco message

---

server/game/Card.js
test/server/cards/03-WC/Dexus.spec.js
test/server/cards/03-WC/Sinestra.spec.js

Fix isOnFlank to use creaturesInPlay

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/03-WC/Philophosaurus.js
test/server/cards/03-WC/Philophosaurus.spec.js

Fixes #844
Added missing locales (will probably will conflict - I will merge)

Philophosaurus should be optional and not display cards in game message

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/01-Core/DanceOfDoom.js
test/server/cards/01-Core/DanceOfDoom.spec.js

Fixes #928
Here is how the UI look like:
It goes from "0" to allow not killing any creature until the maximum creature's modified power.

Changed Dance of Doom to use new 'options' drop down

---

client/Components/Decks/DeckList.jsx
client/Components/Decks/ImportDeck.jsx
client/Components/Form/Input.jsx

This is my first React code so please let me know if there's an issue with using `React.createRef()`
Fixes #1002

Add focus on deck list and import UI

---

server/game/cards/03-WC/EeOnTheFringes.js
test/server/cards/03-WC/EeOnTheFringes.spec.js

E´e On The Fridge should be optional.

---

server/game/cards/03-WC/UnchartedLands.js
test/server/cards/03-WC/UnchartedLands.spec.js

Should allow only if has amber > 0

---

server/game/cards/01-Core/Gongoozle.js
test/server/cards/01-Core/Gongoozle.spec.js

Gongoozle actions should be sequential and conditional

---

server/game/cards/02-AoA/LethalDistraction.js
test/server/cards/02-AoA/LethalDistraction.spec.js

Lethal Destraction was not working after removal of multipleTrigger

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json

Fixed WC set name in PT
Fixed Saurian house name in PT

Fixed one locale key

---

test/server/cards/03-WC/Quadracorder.spec.js

tests for https://github.com/keyteki/keyteki/issues/875
unable to replicate

add quadacorder test

---

server/game/cards/03-WC/Quadracorder.js
test/server/cards/03-WC/Quadracorder.spec.js

A clunky test for a small fix 😅.
Fixes #1020.

Limit Quadracorder to increasing key costs by 3

---

server/game/player.js
test/server/cards/01-Core/SafePlace.spec.js
test/server/cards/03-WC/SenatorBracchus.spec.js
test/server/cards/03-WC/TheCallipygianIdeal.spec.js

Fix amber source/ending the game bug

---

server/game/gamesteps/DestroyedAbilityWindow.js

Fix destroyed abilities to track cards leaving play

---

server/game/cards/01-Core/ImperialTraitor.js

ImperialTraitor is optional and should show hand without Sanctum card

---

client/Components/GameBoard/Card.jsx

Cleaned up some card status that are not applicable to KF
Fixes #665
Fixes #998

Fixed glowing (can-play) while selected

---

server/game/cards/01-Core/CreepingOblivion.js
server/game/cards/03-WC/Infurnace.js
server/game/cards/03-WC/Noname.js
test/server/cards/03-WC/Noname.spec.js

Fixes #993
Fixes #392
Simplified Noname to avoid asking for Discard Pile for a single card.

Fixed purging from a single discard pile

---

client/Components/Decks/DeckList.jsx

* Fixes the search functionality of decks. Searches through all decks and not just the ones that appear on the current page of pagination.
* Re-paginates results after searching

Deck search applies to all search pages

---

server/game/gamesteps/forcedtriggeredabilitywindow.js

Remove Done button unless all abilities are optional

---

server/game/cards/03-WC/CityStateInterest.js
test/server/cards/03-WC/CityStateInterest.spec.js

Fix for City State Interest

---

server/game/Events/EventWindow.js
server/game/ThenAbility.js
server/game/cards/03-WC/ObsidianForge.js
test/server/cards/03-WC/ObsidianForge.spec.js

Obsidian Forge bugfix

---

client/Components/GameBoard/PlayerStats.jsx
server/game/game.js

number of keys in brackets and saving to clipboard

---

server/game/cards/01-Core/NumquidTheFair.js
test/server/cards/01-Core/NumquidTheFair.spec.js

Fix Numquid vs Ward

---

server/game/cards/01-Core/BouncingDeathQuark.js
server/game/cards/03-WC/GiantGnawbill.js
server/game/cards/03-WC/TheFloorIsLava.js
test/server/cards/03-WC/GiantGnawbill.spec.js
test/server/cards/03-WC/TheFloorIsLava.spec.js

Fixes #1104
Fixes #1091
Fixes #1082

Fixes a few game messages. Using targetting instead of promptForSelect

---

server/game/cards/03-WC/Gargantodon.js
test/server/cards/03-WC/Gargantodon.spec.js

Fixes Gargantodon

---

client/Components/GameBoard/ActivePlayerPrompt.jsx

Handling "!isNaN" before "not" check

---

server/game/cards/02-AoA/ShardOfPain.js
test/server/cards/02-AoA/ShardOfPain.spec.js

Fixes shard of pain not allocating damage

---

test/server/cards/01-Core/Poltergeist.spec.js

Test Poltergeist on own artifact is working.

---

test/server/cards/01-Core/TheWarchest.spec.js

Added a new test for The Warchest and Poltergeist

---

server/game/cards/03-WC/CincinnatusRex.js
test/server/cards/03-WC/CincinnatusRex.spec.js

Fix for warded CincinnatusRex

---

server/game/cards/03-WC/TheFloorIsLava.js
test/server/cards/03-WC/TheFloorIsLava.spec.js

Fixes Floor is Lava timing

---

client/Components/Decks/DeckList.jsx

feat: allow users to filter decks by set

---

client/Components/Decks/DeckList.jsx

feat: reset to 1st page on page size change

---

client/Components/Decks/DeckList.jsx

Problems
1. When searching by name, page size is ignored and all matching decks are shown
2. Pages are created before expansion filters are applied
The above problems can be fixed by simplifying the existing code. First filter decks, next clip to the page size, then create deck elements.

Fix interaction between name and expansion filters

---

client/ReduxActions/game.js
client/menus.js
client/pages/Matches.jsx
client/reducers/games.js
client/routes.js
public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/api/games.js
server/api/index.js
server/services/GameService.js

Add page to show previous user matches

---

server/game/cards/04-MM/Sinder.js
test/server/cards/03-WC/PowerOfFire.spec.js
test/server/cards/04-MM/Sinder.spec.js

Card Text: Taunt.\nReap: Destroy a friendly creature.

Implement MM:Sinder to initiate MM work

---

server/game/cards/04-MM/SubjectKirby.js
test/server/cards/04-MM/SubjectKirby.spec.js

feat: implement subject kirby

---

server/game/cards/04-MM/BotBookton.js
test/server/cards/04-MM/BotBookton.spec.js

feat: implement bot bookton

---

server/game/cards/04-MM/Umbra-Fiend.js
test/server/cards/04-MM/Umbra-Fiend.spec.js

feat: implement umbra-fiend

---

server/game/cards/04-MM/SquireAlys.js

feat: implement squire alys

---

server/game/cards/04-MM/HedonisticIntent.js

feat: implement hedonistic intent

---

server/game/CardSelectors/ExactlyXCardSelector.js
server/game/CardSelectors/UpToXCardSelector.js
server/game/cards/02-AoA/MasterTheTheory.js
test/server/cards/01-Core/NaturesCall.spec.js
test/server/cards/02-AoA/MasterTheTheory.spec.js

Alright, 3rd attempt.
Updated the Master The Theory per the issue here:
https://github.com/keyteki/keyteki/issues/375
In this update I have:
* Updated the UpToCardSelector to take a function for num cards
* Updated Master The Theory to use upTo
* Added a test case for Master The Theory
* Added a test case for Natures Call
Testing I have done:
* I confirmed Natures Call works correctly (since it uses upTo)
* Confirmed Master The Theory works correctly
* Lint & Test cases pass

Master The Theory Fix to support 'may'

---

server/game/cards/04-MM/DiametricCharge.js

feat: implement diametric charge

---

server/game/cards/04-MM/Bull-wark.js
test/server/cards/04-MM/Bull-wark.spec.js

feat: implement bull-wark

---

server/game/cards/04-MM/WakingNightmare.js
test/server/cards/04-MM/WakingNightmare.spec.js

feat: implement waking nightmare

---

server/game/cards/02-AoA/Fetchdrones.js
test/server/cards/02-AoA/FetchDrones.spec.js

Fix for FetchDrones (1202)

---

server/game/cards/04-MM/DinoBot.js
server/game/cards/04-MM/DæmoBot.js
server/game/cards/04-MM/LycoBot.js
server/game/cards/04-MM/UmbraBot.js
test/server/cards/04-MM/DinoBot.spec.js
test/server/cards/04-MM/DæmoBot.spec.js
test/server/cards/04-MM/LycoBot.spec.js
test/server/cards/04-MM/UmbraBot.spec.js

https://github.com/keyteki/keyteki/issues/1168

MM: Logos Dino-Bot, Dæmo-Bot, Lyco-Bot, and Umbra-Bot

---

server/game/cards/04-MM/BlastShielding.js
test/server/cards/04-MM/BlastShielding.spec.js

Adding "Blasting Shield" card per https://github.com/keyteki/keyteki/issues/1172
* Added card
* Added test
* lint and tests pass

adding blasting shield

---

server/game/cards/04-MM/AccessDenied.js
test/server/cards/04-MM/AccessDenied.spec.js

Adding Access Denied Card.
* Added Card
* Added Test
* lint and tests pass

adding access denied card

---

server/game/cards/04-MM/OppositionResearch.js

feat: implement opposition research

---

server/game/cards/04-MM/StirringGrave.js
test/server/cards/04-MM/StirringGrave.spec.js

feat: implement stirring grave

---

server/game/cards/04-MM/Hystricog.js
test/server/cards/04-MM/Hystricog.spec.js

feat: implement hystricog

---

server/game/cards/04-MM/Snarette.js
test/server/cards/04-MM/Snarette.spec.js

feat: implement snarette

---

server/game/cards/04-MM/GizelhartsWrath.js
test/server/cards/04-MM/GizelhartsWrath.spec.js

feat: implement gizelharts wrath

---

server/scripts/build_archons.js

build_archon script fix

---

test/server/cards/02-AoA/SirMarrows.spec.js

Added test for Sir Marrows

---

server/game/cards/04-MM/Munchling.js
test/server/cards/04-MM/Munchling.spec.js

https://github.com/keyteki/keyteki/issues/1168

MM: Logos Munchling

---

server/game/cards/04-MM/DoubleDoom.js
test/server/cards/04-MM/DoubleDoom.spec.js

MM: Dis - Double Doom

---

server/game/cards/03-WC/Fidgit.js
test/server/cards/03-WC/Fidgit.spec.js

Fix for Fidgit taking into account potential own cards in opponents archives

---

server/game/cards/04-MM/DinoFiend.js
server/game/cards/04-MM/LycoFiend.js
server/game/cards/04-MM/TechnoFiend.js

MM: Dis - Dino-Fiend, Lyco-Fiend, Techno-Fiend

---

client/Components/GameBoard/PlayerStats.jsx
less/gameboard.less
server/game/player.js

adding key cost readout to PlayerStats

---

docs/card_tutorial.md

This commit contains no code, instead a doc on how to make a card.

Added Card Tutorial

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/04-MM/NovuDynamo.js
test/server/cards/04-MM/NovuDynamo.spec.js
test/server/cards/cancreatecards.spec.js

cancreatecards.spec.js updated to use that thing Romano told me to do
https://github.com/keyteki/keyteki/issues/1168

MM: Logos - Novu Dynamo

---

server/game/cards/04-MM/Lust.js
test/server/cards/04-MM/Lust.spec.js

MM: Dis - Lust

---

server/game/cards/04-MM/Ant110ny.js
test/server/cards/04-MM/Ant110ny.spec.js

MM: Star Alliance - Ant1-10ny

---

server/game/cards/03-WC/IntoTheNight.js
test/server/cards/03-WC/IntoTheNight.spec.js

Fix Into the Night

---

server/game/cards/04-MM/EssenceScale.js
test/server/cards/04-MM/EssenceScale.spec.js

MM: Dis - Essence Scale

---

server/game/cards/03-WC/ShatteredThrone.js
test/server/cards/03-WC/ShatteredThrone.spec.js

fix Shattered Throne timing for realsies/update test

---

server/game/cards/03-WC/InformationExchange.js
test/server/cards/03-WC/InformationExchange.spec.js

fix for information exchange/qincan interaction && update test

---

test/server/cards/03-WC/ComOfficerKirby.spec.js

update kirby test to verify spears interaction 

---

server/game/cards/04-MM/ParticleSweep.js
test/server/cards/04-MM/ParticleSweep.spec.js

Added Particle Sweep per:
* new test pass
* lint passes

MM: Star Alliance - Particle sweep

---

test/server/cards/02-AoA/Replicator.spec.js

When we refactor replicator to allow for reap ability choice, test can be enabled.

updated replicator test (left xit'd for now)

---

server/game/cards/01-Core/WordOfReturning.js
test/server/cards/01-Core/WordOfReturning.spec.js

Sequential:  Word of Returning

---

server/game/cards/01-Core/PositronBolt.js
test/server/cards/01-Core/PositronBolt.spec.js

Sequential: Positron Bolt

---

server/game/cards/02-AoA/TheyreEverywhere.js
test/server/cards/02-AoA/TheyreEverwhere.spec.js

Sequential: They're Everywhere

---

server/game/cards/03-WC/HitAndRun.js
test/server/cards/03-WC/HitAndRun.spec.js

Sequential: Hit and Run

---

client/pages/HowToPlay.jsx
server/game/GameActions.js
server/game/GameActions/DiscardTopOfDeckAction.js
server/game/GameActions/index.js
server/game/chatcommands.js

add /discardtopofdeck

---

test/server/cards/02-AoA/Smite.spec.js

Sequential: Smite

---

server/game/cards/01-Core/TendrilsOfPain.js
test/server/cards/01-Core/TendrilsOfPain.spec.js

https://youtu.be/0NbXUv8TSr4?t=635

Sequential: Tendrils of Pain

---

server/game/cards/03-WC/Tribute.js
test/server/cards/03-WC/Tribute.spec.js

Tribute fix

---

server/game/game.js
server/game/gamesteps/setup/AdaptiveDeckSelectionPrompt.js
server/game/gamesteps/setup/setupphase.js

there were derps, i am sorry and i will do better.

Adaptive Fix

---

server/api/account.js

I suspect it's done correctly but I can't actually test it locally.
Fixes #1162 & #1279

added username to password reset email

---

server/game/game.js
server/game/gamesteps/setup/FirstPlayerSelection.js
server/game/gamesteps/setup/GameStartPrompt.js
server/game/gamesteps/setup/setupphase.js
server/game/player.js
server/gamenode/gameserver.js
server/lobby.js
server/pendinggame.js

OnRematch: Losers Choosers

---

client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerRow.jsx
client/archonMaker.js
server/game/gamesteps/setup/AdaptiveDeckSelectionPrompt.js
server/game/player.js
test/server/cards/01-Core/WordOfReturning.spec.js

Decklist Cleanup

---

client/Components/GameBoard/GameBoard.jsx

Rage Quit Losers

---

client/Components/GameBoard/PlayerStats.jsx
server/game/Card.js
server/game/GameActions.js
server/game/GameActions/DrawAction.js
server/game/GameActions/MulliganAction.js
server/game/GameActions/index.js
server/game/MenuCommands.js
server/game/chatcommands.js
server/game/game.js
server/game/gamesteps/setup/mulliganprompt.js
server/game/gamesteps/setup/setupphase.js
server/game/player.js

fixed up draw messaging Fixes #773 
all manual messaging to danger alerts
add mulligan gameaction
added give power tokens in card
added ability to set active house in manual mode by clicking on house icons
Fixes #1087

Manual Enhancements

---

server/game/cards/03-WC/ImperialRoad.js
test/server/cards/03-WC/ImperialRoad.spec.js

fixes imperial road issue and updates test

---

server/game/CardVisibility.js
server/game/player.js

unhide archives for spectators when hands are revealed

---

client/Components/GameBoard/CardMenu.jsx
server/game/Card.js

Card manual nest

---

server/game/cards/04-MM/ConsulPrimus.js
test/server/cards/04-MM/ConsulPrimus.spec.js

MM: Saurian Consul Primus

---

test/server/cards/01-Core/Hecatomb.spec.js

Ref #925 - cannot reproduce issue

Add Hecatomb Test

---

test/server/cards/01-Core/TooMuchToProtect.spec.js
test/server/cards/03-WC/OdoacThePatrician.spec.js

Added tests for TMTP and Odoac the Patrician

---

server/game/cards/04-MM/TeleporterChiefTink.js
test/server/cards/04-MM/TeleporterChiefTink.spec.js

Per this issue, I've implemented Teleporter Chief Tink:
* New test case passes
* Lint passes

MM: Star Alliance - Teleporter Chief Tink

---

server/game/cards/04-MM/Berinon.js
test/server/cards/04-MM/Berinon.spec.js

MM - Sanctum Berinon

---

server/game/cards/04-MM/UmbraSaurus.js
test/server/cards/04-MM/UmbraSaurus.spec.js

MM : Added test for UmbraSaurus.js

---

server/game/cards/04-MM/SeekerOfTruth.js
test/server/cards/04-MM/SeekerOfTruth.spec.js

MM - Seeker of Truth

---

server/game/cards/04-MM/DarkCenturion.js
test/server/cards/04-MM/DarkCenturion.spec.js

Creating Dark Centurion as part of:
https://github.com/keyteki/keyteki/issues/1170
This PR in includes:
* New Card
* Test Case
Validation:
* Test cases pass
* Lint passes
* In game testing

MM: Saurian - Dark Centurion

---

server/game/cards/04-MM/DaemoBeast.js
server/game/cards/04-MM/DinoBeast.js
server/game/cards/04-MM/DinoBot.js
server/game/cards/04-MM/DinoFiend.js
server/game/cards/04-MM/KeyFrog.js
server/game/cards/04-MM/TechnoBeast.js

https://decksofkeyforge.com/spoilers/1806958
https://decksofkeyforge.com/spoilers/1806975
https://decksofkeyforge.com/spoilers/1806976
https://decksofkeyforge.com/spoilers/1757707
https://github.com/keyteki/keyteki/issues/1173

MM: Untamed 

---

server/game/cards/04-MM/DarkMinion.js

MM: Dis - Dark Minion

---

client/Application.jsx
client/Components/Decks/DeckList.jsx
client/Components/Decks/DeckRow.jsx
client/Components/Games/SelectDeckModal.jsx
client/ReduxActions/deck.js
client/pages/Decks.jsx
client/reducers/cards.js
keyteki.code-workspace
server/api/decks.js
server/lobby.js
server/scripts/importstandalonedecks.js
server/services/DeckService.js

Fixed decks not loading when cards are loaded after decks
Updated to latest json submodule
Added script for importing standalone decks
Added standalone decks to client

Add standalone decks

---

server/game/cards/04-MM/SpoilsOfBattle.js
test/server/cards/04-MM/SpoilsOfBattle.spec.js

Implementation and tests for Spoils of Battle, per issue:
https://github.com/keyteki/keyteki/issues/1170
Includes:
* New card Spoils of Battle
* New test case
* Test cases pass
* Lint passes
Notes:
This implementation is mostly a copy with small updates to [Pandemonium](https://github.com/keyteki/keyteki/blob/master/server/game/cards/01-Core/Pandemonium.js)

MM: Saurian - Spoils of Battle

---

server/game/cards/04-MM/EclecticInquiry.js
server/game/cards/04-MM/MutagenicSerum.js
test/server/cards/04-MM/EclecticInquiry.spec.js
test/server/cards/04-MM/MutagenicSerum.spec.js

Logos EclecticInquiry and MutagenicSerum

---

server/game/cards/01-Core/KeyHammer.js
server/game/cards/01-Core/SmilingRuth.js
server/game/cards/01-Core/TendrilsOfPain.js
server/game/cards/02-AoA/Nightforge.js
server/game/cards/04-MM/BreakKey.js
server/game/chatcommands.js
server/game/player.js
test/server/cards/04-MM/BreakKey.spec.js

Along with a rename of keyForged in player to keysForgedThisRound

Mm break key

---

server/game/cards/04-MM/KeyFrog.js
test/server/cards/04-MM/Keyfrog.spec.js

Added test to validate who gets the prompt to forge a key

MM - Fixed Keyfrog name

---

server/game/cards/04-MM/DarkWave.js
server/game/cards/04-MM/SafeHouse.js
test/server/cards/04-MM/DarkWave.spec.js
test/server/cards/04-MM/SafeHouse.spec.js

Shadows Dark Wave and Safe House

---

server/game/Card.js
test/server/cards/03-WC/OdoacThePatrician.spec.js

I didn't break TCO again... Okay, I did and I'm sorry

Fixed missing manual mode option

---

test/server/cards/03-WC/OdoacThePatrician.spec.js

There was a lint problem in master

Fixed a lint problem

---

client/Components/Games/GameLobby.jsx
test/server/cards/03-WC/OdoacThePatrician.spec.js

you can send game-link for passworded games now

fix for game-links and passwords

---

client/Components/GameBoard/PlayerRow.jsx

no one can really be blamed for this......

fix redux actions "mishap"

---

client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerStats.jsx

adding matchRecord to PlayerStats

---

client/Application.jsx
client/ReduxActions/lobby.js
client/ReduxActions/misc.js
client/reducers/lobby.js
package-lock.json

added redux blurredWindow.bool
added tab title cycling if active player has the window blurred
https://media.discordapp.net/attachments/563737400745132042/703034083546103879/My_new_video_project.gif

blurred tab title cycling

---

server/game/cards/04-MM/Commandeer.js
server/game/cards/04-MM/DaemoSaurus.js
server/game/cards/04-MM/FangsOfGizelhart.js
server/game/cards/04-MM/LycoSaurus.js
server/game/cards/04-MM/TechnoSaurus.js
server/game/cards/04-MM/UmbraSaurus.js
test/server/cards/04-MM/Commandeer.spec.js
test/server/cards/04-MM/FangsOfGizelhart.spec.js

https://github.com/keyteki/keyteki/issues/1169

MM: Sanctum - Comandeer - Fang of Gizelhart

---

server/game/cards/04-MM/MercyMalkinQueen.js
server/game/cards/04-MM/MushroomWithAView.js
test/server/cards/04-MM/MercyMalkinQueen.spec.js
test/server/cards/04-MM/MushroomWithAView.spec.js

MM Mushroom with a view and Mercy, Malkin Queen

---

server/game/cards/04-MM/MadProphetGizelhart.js
test/server/cards/04-MM/MadProphetGizelhart.spec.js

https://github.com/keyteki/keyteki/issues/1169

MM: Sanctum - Mad Prophet gizelhart

---

server/game/cards/04-MM/LookOverThere.js
test/server/cards/04-MM/LookOverThere.spec.js

https://github.com/keyteki/keyteki/issues/1171

MM: Shadows - Look Over There!

---

server/game/GameActions/ExhaustAction.js
server/game/cards/04-MM/Humble.js
test/server/cards/03-WC/SelfBolsteringAutomata.spec.js
test/server/cards/04-MM/Humble.spec.js

MM Saurian Humble

---

server/game/cards/04-MM/MiasmaBomb.js
server/game/cards/04-MM/SubtleOtto.js
test/server/cards/04-MM/MiasmaBomb.spec.js
test/server/cards/04-MM/SubtleOtto.spec.js

MM Shadows Miasma Bomb

---

server/game/cards/04-MM/Mole.js
server/game/effects.js
server/game/player.js
test/server/cards/04-MM/Mole.spec.js

MM Shadows Mole

---

server/game/cards/04-MM/RecklessRizzo.js
server/game/cards/04-MM/TemptingOffer.js
test/server/cards/04-MM/RecklessRizzo.spec.js
test/server/cards/04-MM/TemptingOffer.spec.js

RR will fail test due to MM.json bug (pending PR: https://github.com/keyteki/keyteki-json-data/pull/30)

MM Shadows Tempting Offer and Reckless Rizzo

---

server/game/cards/04-MM/Resurgence.js
test/server/cards/04-MM/Resurgence.spec.js

MM Untamed Resurgence

---

server/game/Card.js
server/game/GameActions/PlaceUnderAction.js
server/game/GameActions/PutIntoPlayAction.js
server/game/GameActions/SearchAction.js
server/game/cards/01-Core/SpanglerBox.js
server/game/cards/04-MM/Deusillus.js
server/game/cards/04-MM/Deusillus2.js
server/game/cards/04-MM/ItSComing.js
server/game/cards/04-MM/NiffleKong.js
server/game/cards/04-MM/NiffleKong2.js
server/game/cards/04-MM/UltraGraviton.js
server/game/cards/04-MM/UltraGraviton2.js
server/game/chatcommands.js
server/game/player.js
test/server/cards/01-Core/SpanglerBox.spec.js
test/server/cards/04-MM/Deusillus.spec.js
test/server/cards/04-MM/ItSComing.spec.js
test/server/cards/04-MM/NiffleKong.spec.js
test/server/cards/04-MM/UltraGraviton.spec.js

Deusillus et al in master branch
Also Fixes #1079 
163 commits, but it says it is able to merge :)

Deusillus et al in master branch

---

server/game/cards/01-Core/Poltergeist.js
test/server/cards/01-Core/Poltergeist.spec.js

Fixes Poltergeist and artifacts that sacrifice themselves.

---

server/game/cards/03-WC/Timequake.js
test/server/cards/03-WC/Timequake.spec.js

Fix Timequake not working with warded cards

---

server/game/Card.js
server/game/GameActions/DrawAction.js
server/game/cards/04-MM/Chronus.js
test/server/cards/04-MM/Chronus.spec.js

I am assuming that the current Amber will continue to come as amber in cardData.
Need to check load deck process for consistency.

Implement Chronus and fix a small glitch on get bonusIcon()

---

server/api/account.js
server/services/UserService.js

Fix bugs with patreon sql queries
Refactor horrendously overcomplicated patreon checking code

Couple of patreon fixes

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/04-MM/EnsignElSamra.js
server/game/cards/04-MM/ReclaimedbyNature.js
test/helpers/deckbuilder.js
test/server/cards/04-MM/EnsignElSamra.spec.js
test/server/cards/04-MM/ReclaimedByNature.spec.js

https://keyforge-card-images.s3-us-west-2.amazonaws.com/spoiler-imgs/512/reclaimed-by-nature.jpg

MM Ensign El-Samra and Reclaimed by Nature

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/GameActions/ResolveBonusIconsAction.js
server/game/cards/04-MM/AmphoraCaptura.js
server/game/cards/04-MM/CyberClone.js
server/game/cards/04-MM/ScrivenerFavian.js
server/game/cards/04-MM/UltraGraviton.js
server/game/cards/04-MM/WildBounty.js
server/game/effects.js
test/server/cards/04-MM/AmphoraCaptura.spec.js
test/server/cards/04-MM/CyberClone.spec.js
test/server/cards/04-MM/ScrivenerFavian.spec.js
test/server/cards/04-MM/UltraGraviton.spec.js
test/server/cards/04-MM/WildBounty.spec.js

MM Wild Bounty, Amphora, Scrivener and Cyber Clone

---

client/Components/GameBoard/Card.jsx
server/game/deck.js

Fix bonus icons

---

server/game/GameActions/SearchAction.js
server/game/cards/04-MM/ItSComing.js
test/server/cards/04-MM/ItSComing.spec.js

MM: Rolled back a change in SearchAction.js to fix It's Coming

---

server/game/cards/04-MM/SaurianEgg.js
test/server/cards/04-MM/SaurianEgg.spec.js

Supersedes #1245 
Added a gigantic logic

MM Saurian egg in master (merged and simplified a bit)

---

server/game/cards/04-MM/SacroSaurus.js
test/server/cards/04-MM/LycoSaurus.spec.js
test/server/cards/04-MM/SacroSaurus.spec.js

Also, added test cases
Supersedes #1382
Fixes #1396

Missing play effect on Sacro Saurus (without fight)

---

server/game/cards/04-MM/ExchangeOfficer.js

Fix Exchange Office

---

server/game/cards/04-MM/EssenceScale.js

Essense Scale was readying itself

---

server/game/cards/03-WC/Timequake.js
test/server/cards/03-WC/Timequake.spec.js

Timequake should shuffle upgrades too

---

server/game/cards/03-WC/BerserkerSlam.js
test/server/cards/03-WC/BerserkerSlam.spec.js

Fixes Bezerker Slam on controlled creatures

---

server/game/GameActions/LastingEffectAction.js
server/game/cards/01-Core/Blypyp.js
server/game/cards/01-Core/CrystalHive.js
server/game/cards/01-Core/FullMoon.js
server/game/cards/01-Core/LibraryAccess.js
server/game/cards/01-Core/LootTheBodies.js
server/game/cards/01-Core/LooterGoblin.js
server/game/cards/01-Core/SoftLanding.js
server/game/cards/01-Core/Warsong.js
server/game/cards/02-AoA/LethalDistraction.js
server/game/cards/03-WC/BarnRazing.js
server/game/cards/03-WC/Ragnarok.js
server/game/cards/04-MM/Commandeer.js
server/game/cards/04-MM/WildBounty.js
server/game/effects.js
server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/triggeredability.js
test/server/cards/01-Core/KeyHammer.spec.js
test/server/cards/01-Core/LootTheBodies.spec.js
test/server/cards/01-Core/WildWormhole.spec.js
test/server/cards/03-WC/Ragnarok.spec.js
test/server/cards/04-MM/WildBounty.spec.js

Change delayed effects to ability triggers

---

server/game/cards/04-MM/SpoilsOfBattle.js
test/server/cards/02-AoA/Duskwitch.spec.js
test/server/cards/04-MM/SpoilsOfBattle.spec.js

Fixes 'Spoils of Battle' not capture amber correctly

---

server/game/BaseActions/PlayUpgradeAction.js

Bug fix for upgrades not displaying target

---

server/game/cards/04-MM/CyberClone.js

Enhance Cyber-Clone game message

---

server/game/cards/04-MM/FaustTheGreat.js
test/server/cards/04-MM/FaustTheGreat.spec.js

Using context.source to be able to interact with Mimic gel
Fixes #1420

Fix Faust the Great capture from friends

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json

Add Scout Pete button to locale

---

test/server/cards/03-WC/MimicGel.spec.js

Removed all xit's.
Proved https://github.com/keyteki/keyteki/issues/1394 is fixed.

Mimic Gel tests are passing... Yay!!!

---

server/game/cards/04-MM/Survey.js

Fixes Survey game message

---

client/Components/GameBoard/Card.jsx
server/game/Card.js

Fix creature played as upgrade with "taunt" keyword

---

server/game/cards/01-Core/Blypyp.js
test/server/cards/01-Core/Blypyp.spec.js

Fixed Blypyp self-ready

---

test/server/cards/03-WC/SenatorBracchus.spec.js

Adding more tests to Bracchus

---

server/game/cards/01-Core/GreyMonk.js
test/server/cards/01-Core/GreyMonk.spec.js

Fix Grey Monk not applying +1 armor to all friendly creatures

---

server/game/cards/01-Core/DanceOfDoom.js
test/server/cards/01-Core/DanceOfDoom.spec.js

Fixes: KEYTEKI-165
Fixes #1450

Fixes Dance of Doom when no creature is in play

---

server/game/TerminalCondition.js
server/game/cards/03-WC/Weasand.js
test/server/cards/03-WC/Weasand.spec.js

Fixed TerminalCondition to pass context to condition

---

server/game/cards/03-WC/EDAIEdie4x4.js
test/server/cards/03-WC/EDAIEdie4x4.spec.js

Fixes Mimic Gel and EDAIEdie4x4

---

server/game/GameActions/ForgeAction.js

removed key cost from forge key action to simplify log

---

client/Components/GameBoard/GameBoard.jsx
client/Components/Site/NavBar.jsx
client/Components/Site/ServerStatus.jsx
client/ReduxActions/game.js
client/ReduxActions/socket.js
client/middleware/api-middleware.js
client/reducers/games.js
client/reducers/lobby.js
less/site.less

Add server ping to the connectivity display in the navbar
Show lobby status when not in a game, and game status when in a game
Refactor server status into a component
Refactor some messy reducers
Fix a couple of issues with authentication causing the client not to reconnect properly

Network reporting improvements

---

server/game/cards/01-Core/Charge.js
test/server/cards/01-Core/Charge.spec.js

Fixed Charge! - with the help of Jadiel :)

---

test/server/cards/02-AoA/ScowlyCaper.spec.js

Scowly Caper not ignoring skirmish

---

client/Components/Games/GameList.jsx
less/gamelist.less
server/lobby.js
server/pendinggame.js

Highlight private games to admins
allow admins to watch any game
hide private games from non admins instead of filtering on the ui

don't close a tournament game if the last player leaves/disconnects

---

server/game/cards/03-WC/GamblingDen.js

Add house to Gambling Den message

---

client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerRow.jsx

Hide decklist for spectators when in a "hide decklist" game

---

index.js
server/api/cards.js
server/gamenode/gamesocket.js
server/lobby.js
server/scripts/fetchdata/CardImport.js
server/scripts/importstandalonedecks.js
server/services/CardService.js
server/services/ServiceFactory.js

Fetch from redis if present, fill it if not
Remove CARDDATA message as no longer necessary
Make node server fetch from redis too

Use redis to store card data

---

server/game/GameActions/ReturnToHandAction.js
server/game/GameActions/RevealAction.js
server/game/cards/04-MM/NiffleKong.js
test/server/cards/04-MM/NiffleKong.spec.js

Fix Niffle-Kong to select card

---

server/game/cards/04-MM/DetentionCoil.js
server/game/cards/04-MM/HadronCollision.js
test/server/cards/04-MM/DetentionCoil.spec.js
test/server/cards/04-MM/HadronCollision.spec.js

MM Star Alliance Detention Coil and Hadron Collision

---

server/game/cards/04-MM/Commune.js
server/game/cards/04-MM/Lumilu.js
server/game/cards/04-MM/Trimble.js
test/server/cards/04-MM/Commune.spec.js
test/server/cards/04-MM/Lumilu.spec.js
test/server/cards/04-MM/Trimble.spec.js

MM Untamed - Commune, Lumilu, Trimble

---

server/game/cards/04-MM/Brabble.js
server/game/cards/04-MM/SagittariisGaze.js
test/server/cards/04-MM/Brabble.spec.js
test/server/cards/04-MM/SagittariisGaze.spec.js

MM Dis Brabble and Saurian Sagittarii's Gaze

---

server/game/cards/03-WC/AutoLegionary.js
test/server/cards/03-WC/AutoLegionary.spec.js

Fixes #1519 
we should get a future effect that sets a cards power to X and use it here

Auto-leg fix for applying +5 power every action

---

server/game/cards/04-MM/Aemberheart.js
server/game/cards/04-MM/CallToAction.js
server/game/cards/04-MM/GizelhartsStandard.js
test/server/cards/04-MM/Aemberheart.spec.js
test/server/cards/04-MM/CallToAction.spec.js
test/server/cards/04-MM/GizelhartsStandard.spec.js

MM Sanctum Call to Action, Aemberheart, Gizelheart's Standard

---

server/game/cards/04-MM/CrewmanJorg.js
server/game/cards/04-MM/LCdrTrigon.js
server/game/cards/04-MM/Stealthster.js
test/server/cards/04-MM/CrewmanJorg.spec.js
test/server/cards/04-MM/LCdrTrigon.spec.js

MM StarAlliance Crewman Jörg, LCdr. Trigon and Stealthster

---

server/game/cards/04-MM/HaplessCadet.js
server/game/cards/04-MM/ZForceAgent14.js
server/game/cards/04-MM/ZParticleTracker.js
server/game/cards/04-MM/ZRayBlaster.js
server/game/cards/04-MM/ZWaveEmitter.js
test/server/cards/04-MM/HaplessCadet.spec.js
test/server/cards/04-MM/ZForceAgent14.spec.js
test/server/cards/04-MM/ZParticleTracker.spec.js
test/server/cards/04-MM/ZRayBlaster.spec.js
test/server/cards/04-MM/ZWaveEmitter.spec.js

MM Star Alliance Hapless Cadet and Z-* cards

---

server/game/cards/03-WC/SauryAboutThat.js

it seems some copy and paste error, weird it did not affect functionality

Code cleanup of Saury About That

---

server/game/cards/01-Core/LostInTheWoods.js
server/game/cards/04-MM/ImpLosion.js

Adjusted Imp-losion and Lost in the Woods message

---

server/game/cards/04-MM/FontOfTheEye.js
test/server/cards/04-MM/FontOfTheEye.spec.js

Fixes Font of the Eye having a condition

---

server/game/cards/02-AoA/Extinction.js
test/server/cards/02-AoA/Extinction.spec.js

Fixes Extinction and warded creatures

---

server/game/cards/04-MM/BaldricTheBold.js
server/game/cards/04-MM/NewFrontiers.js
server/game/cards/04-MM/TechnoKnight.js
test/server/cards/04-MM/BaldricTheBold.spec.js
test/server/cards/04-MM/NewFrontiers.spec.js

MM Star Alliance - New Frontiers and Sanctum Baldric the Bold and Techno Knight

---

server/game/cards/04-MM/Chronus.js
test/server/cards/04-MM/Chronus.spec.js

Fixes Chronus

---

server/game/GameActions/UseAction.js
server/game/cards/04-MM/AmbassadorLiu.js
server/game/cards/04-MM/HoldTheLine.js
server/game/cards/04-MM/Kartanoo.js
test/server/cards/04-MM/AmbassadorLiu.spec.js
test/server/cards/04-MM/HoldTheLine.spec.js
test/server/cards/04-MM/Kartanoo.spec.js

MM StarAlliance: Hold the Line, Kartanoo and Ambassador Liu

---

server/game/cards/04-MM/DinoKnight.js
server/game/cards/04-MM/DinoThief.js
test/server/cards/04-MM/DinoKnight.spec.js
test/server/cards/04-MM/DinoThief.spec.js

MM Dino-Thief and Dino-Knight

---

server/game/Card.js
server/game/CardAbility.js
server/game/cards/04-MM/PurifierOfSouls.js

(MM) Purifier Of Souls

---

server/game/cards/01-Core/PositronBolt.js
server/game/cards/01-Core/TendrilsOfPain.js
server/game/cards/02-AoA/TheyreEverywhere.js
test/server/cards/01-Core/PositronBolt.spec.js
test/server/cards/01-Core/TendrilsOfPain.spec.js
test/server/cards/02-AoA/TheyreEverwhere.spec.js

https://www.youtube.com/watch?v=_aqQWA8IAeA

reverting sequential damage ruling

---

server/game/BaseActions/PlayUpgradeAction.js
test/server/cards/03-WC/QuixxleStone.spec.js
test/server/cards/04-MM/MatterMaker.spec.js

Alternative upgrades fix

---

server/game/GameActions/PutIntoPlayAction.js
server/game/cards/02-AoA/ScowlyCaper.js
test/server/cards/01-Core/OverlordGreking.spec.js
test/server/cards/02-AoA/ScowlyCaper.spec.js

I made an update to PutIntoPlay, but maybe it is better elsewhere. 
For review...
Fixes #1500

Fixed event not being applied when creature was put into play under 'mycontrol'

---

server/game/cards/03-WC/ReassemblingAutomaton.js

Reassembling Automaton bug fix

---

server/api/account.js
server/services/UserService.js

Fixes https://github.com/keyteki/keyteki/issues/1441

Make sure all times are in utc before hashing or comparing them

---

server/game/cards/04-MM/CommanderDhrxgar.js
server/game/cards/04-MM/JONCargo.js
test/server/cards/04-MM/AccessDenied.spec.js
test/server/cards/04-MM/CommanderDhrxgar.spec.js
test/server/cards/04-MM/JONCargo.spec.js

MM last two cards Commander Dhrxgar and J.O.N. Cargo

---

server/game/GameActions/RandomDiscardAction.js
server/game/cards/03-WC/NogiSmartfist.js
server/game/cards/04-MM/LadyLoreena.js
server/game/cards/04-MM/Mindfire.js
test/server/cards/04-MM/LadyLoreena.spec.js
test/server/cards/04-MM/Mindfire.spec.js

Fixed also a glitch with Nogi Smartfist

MM Mindfire and Lady Loreena

---

server/game/cards/04-MM/MutationOfCunning.js
server/game/cards/04-MM/MutationOfFury.js
server/game/cards/04-MM/MutationOfInstinct.js
server/game/cards/04-MM/VaultsBlessing.js
test/server/cards/04-MM/MutationOfCunning.spec.js
test/server/cards/04-MM/MutationOfFury.spec.js
test/server/cards/04-MM/MutationOfInstinct.spec.js
test/server/cards/04-MM/VaultsBlessing.spec.js

Mm Untamed "Mutation *" and Vault's Blessing

---

server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/triggeredability.js

Only change hasTriggered when the ability resolves

---

server/game/cards/04-MM/DaemoThief.js
server/game/cards/04-MM/SacroFiend.js
server/game/cards/04-MM/TechnoThief.js
test/server/cards/04-MM/DaemoThief.spec.js

MM Thiefs and SacroFiend - split from the MM Alien PR

---

test/server/cards/01-Core/Blypyp.spec.js
test/server/cards/01-Core/SoftLanding.spec.js

Tests for Blypyp/SL interactions with creatures entering the field

---

client/Components/GameBoard/ActivePlayerPrompt.jsx
server/db/schema/99 - Data.sql
server/game/AbilityTargets/AbilityTargetCardName.js
server/game/Card.js
server/game/EffectSource.js
server/game/baseability.js
server/game/cards/04-MM/EtansJar.js
server/game/cards/04-MM/MarkOfDis.js
server/game/cards/04-MM/Picaroon.js
server/game/cards/04-MM/RelentlessCreeper.js
server/game/chatcommands.js
server/services/CardService.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/04-MM/EtansJar.spec.js
test/server/cards/04-MM/MarkOfDis.spec.js
test/server/cards/04-MM/Picaroon.spec.js
test/server/cards/04-MM/RelentlessCreeper.spec.js

Add some dis mm cards

---

server/game/GameActions/RemoveTokenAction.js
server/game/cards/02-AoA/EntropicManipulator.js
server/game/cards/02-AoA/Equalize.js
server/game/cards/04-MM/CrystalSurge.js
server/game/cards/04-MM/CurseOfVanity.js
server/game/cards/04-MM/DefenseInitiative.js
server/game/cards/04-MM/Patronage.js
test/server/cards/02-AoA/EntropicManipulator.spec.js
test/server/cards/02-AoA/Equalize.spec.js
test/server/cards/04-MM/CrystalSurge.spec.js
test/server/cards/04-MM/CurseOfVanity.spec.js
test/server/cards/04-MM/DefenseInitiative.spec.js
test/server/cards/04-MM/Patronage.spec.js

Also fixes a cosmetic issue : 
Fixes #525

MM Crystal Surge, Patronage, Curse of Vanity and Defense Initiative

---

server/game/cards/04-MM/DarkHarbinger.js
test/server/cards/04-MM/DarkHarbinger.spec.js

MM Untamed Dark Harbinger

---

server/game/cards/04-MM/DaemoKnight.js
test/server/cards/04-MM/DaemoBeast.spec.js
test/server/cards/04-MM/DaemoKnight.spec.js

MM Sanctum Daemo-Knight

---

server/game/cards/04-MM/CuriaSaurus.js
server/game/cards/04-MM/DreadboneDecimus.js
server/game/cards/04-MM/ForumOfGiants.js
server/game/cards/04-MM/Gladiodontus.js
server/game/cards/04-MM/LegionsMarch.js
server/game/cards/04-MM/MonumentToLudo.js
server/game/cards/04-MM/SenatorQuintina.js
server/game/cards/04-MM/SirenHorn.js
test/server/cards/04-MM/CuriaSaurus.spec.js
test/server/cards/04-MM/DreadboneDecimus.spec.js
test/server/cards/04-MM/ForumOfGiants.spec.js
test/server/cards/04-MM/Gladiodontus.spec.js
test/server/cards/04-MM/LegionsMarch.spec.js
test/server/cards/04-MM/MonumentToLudo.spec.js
test/server/cards/04-MM/SenatorQuintina.spec.js
test/server/cards/04-MM/SirenHorn.spec.js

@jeremylarner Can you have a look at what I'm doing wrong with Legion's March please?

Add some saurian mm cards

---

server/game/cards/04-MM/BossZarek.js
server/game/cards/04-MM/DoomSigil.js
server/game/cards/04-MM/LiamSay.js
server/game/cards/04-MM/Pincerator.js
test/server/cards/04-MM/BossZarek.spec.js
test/server/cards/04-MM/DoomSigil.spec.js
test/server/cards/04-MM/LiamSay.spec.js
test/server/cards/04-MM/Pincerator.spec.js

MM Shadows: Boss Zarek, Doom Sigil, Liam Say, Pincerator

---

server/game/cards/04-MM/GrowthSurge.js
test/server/cards/04-MM/GrowthSurge.spec.js

Related to #1173 
This is pretty much a copy/paste of Positron Bolt replacing damage with power counters.

MM Untamed - Growth surge

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/GameActions/RearrangeCardsAction.js
server/game/cards/04-MM/Vandalize.js
test/server/cards/03-WC/LayOfTheLand.spec.js
test/server/cards/04-MM/Vandalize.spec.js

MM Shadows Vandalize

---

server/game/cards/03-WC/InformationExchange.js

Information Exchange fix

---

server/game/cards/04-MM/DarkQueenGloriana.js
test/server/cards/04-MM/DarkQueenGloriana.spec.js

MM Dark Queen Gloriana

---

server/game/GameActions.js
server/game/cards/03-WC/Opportunist.js
server/game/cards/04-MM/Borrow.js
server/game/cards/04-MM/Mastermindy.js
test/server/cards/04-MM/Borrow.spec.js
test/server/cards/04-MM/Mastermindy.spec.js
test/server/cards/04-MM/Opportunist.spec.js

MM Shadows Borrow, Opportunist and Mastermindy

---

server/game/cards/04-MM/Chonkers.js
server/game/cards/04-MM/Eunoia.js
test/server/cards/04-MM/Chonkers.spec.js
test/server/cards/04-MM/Eunoia.spec.js

Implement Chonkers and Eunoia Mass Mutation

---

client/Components/Games/GameList.jsx
client/Components/Games/PendingGame.jsx
client/pages/UserAdmin.jsx
less/common.less
server/db/schema/99 - Data.sql
server/game/gamechat.js
server/game/gamesteps/setup/FirstPlayerSelection.js
server/models/User.js
server/services/MessageService.js
server/services/UserService.js

Fix some places where the colour should show up but doesnt
fixes Chat colours do not show for game actions, only chat messages #1635

Add the previous tournament winner role

---

server/game/GameActions/AllocateDamageAction.js
server/game/cards/02-AoA/OrtannuTheChained.js
server/game/gamesteps/AllocateDamagePrompt.js
server/game/playerpromptstate.js
test/server/cards/04-MM/OrtannuTheChained.spec.js

Fixes Ortannu The Chained allocate damage with splash against warded creatures

---

server/game/cards/04-MM/LuckyDice.js
test/server/cards/04-MM/LuckyDice.spec.js

MM Shadows Lucky Dice

---

server/game/cards/04-MM/DarkAmberVault.js
test/server/cards/04-MM/DarkAmberVault.spec.js

MM Dark Amber Vault

---

server/game/cards/04-MM/Painmail.js
test/server/cards/04-MM/Painmail.spec.js

MM Painmail

---

server/game/GameActions/DealDamageAction.js
server/game/GameActions/ResolveBonusIconsAction.js
server/game/cards/04-MM/Maleficorn.js
test/server/cards/04-MM/Maleficorn.spec.js

MM Maleficorn

---

server/game/cards/04-MM/Charybdis.js
server/game/cards/04-MM/Nerotaurus.js
server/game/cards/04-MM/Scylla.js
test/server/cards/04-MM/Charybdis.spec.js
test/server/cards/04-MM/Nerotaurus.spec.js
test/server/cards/04-MM/Scylla.spec.js

MM Nerotaurus, Charybdis and Scylla

---

server/game/cards/04-MM/Gluttony.js
server/game/cards/04-MM/Greed.js
server/game/cards/04-MM/Sloth.js
test/server/cards/04-MM/Gluttony.spec.js
test/server/cards/04-MM/Greed.spec.js
test/server/cards/04-MM/Sloth.spec.js

MM Gluttony, Greed and Sloth

---

server/game/cards/04-MM/Turnkey.js
test/server/cards/04-MM/Turnkey.spec.js

Quick implementation of turnkey for #1167  :

Implemented Turnkey

---

server/game/cards/04-MM/Skixuno.js
test/server/cards/04-MM/Skixuno.spec.js

Implemented skixuno

---

server/game/BaseActions/BasePlayAction.js
server/game/BaseActions/PlayAction.js
server/game/BaseActions/PlayArtifactAction.js
server/game/BaseActions/PlayCreatureAction.js
server/game/BaseActions/PlayUpgradeAction.js
server/game/cards/01-Core/SpeedSigil.js
server/game/cards/01-Core/TreasureMap.js
server/game/costs.js
server/game/effects.js
test/server/cards/01-Core/Poltergeist.spec.js

This is prep for a bigger alpha fix and removes some duplication
ETA: Also now includes support for effects which send action cards somewhere other than your discard pile

Add to cardsPlayed only when the card is played

---

server/game/cards/04-MM/OptioGorkus.js
test/server/cards/04-MM/OptioGorkus.spec.js

MM Saurian Optio Gorkus

---

server/game/Card.js
server/game/cards/03-WC/AutoLegionary.js
server/game/cards/04-MM/Animator.js
server/game/cards/04-MM/CyberClone.js
server/game/cards/04-MM/ThePaleStar.js
server/game/effects.js
test/server/cards/04-MM/ThePaleStar.spec.js

MM Dis The Pale Star

---

server/game/GameActions/PlayCardAction.js
test/server/cards/02-AoA/Exhume.spec.js
test/server/cards/03-WC/Explo-rover.spec.js

Fixes Exhume and Explo-rover and Lifeward/Quixxle Stone

---

server/game/cards/04-MM/BlastShielding.js
test/server/cards/04-MM/BlastShielding.spec.js

Fixes MM Blast Shielding

---

server/services/DeckService.js

Fixes #1683
Fixes #1682
Fixes #1679

make sure only 1 copy of a enhanced card is added

---

client/Components/Decks/DeckStatus.jsx
client/Components/Decks/DeckStatus.scss
client/Components/Decks/DeckStatusSummary.jsx
client/Components/Decks/DeckStatusSummary.scss
client/redux/reducers/cards.js
server/lobby.js
server/services/DeckService.js

Flag decks that have not had their enhancements set

---

server/db/schema/13 - DeckHouses.sql

Fix starter db scripts

---

client/Components/Decks/IdentityCard.jsx
client/Components/GameBoard/GameBoard.scss
server/game/GameActions/ResolveBonusIconsAction.js
webpack.common.js

Fixes #1658
Fixes #1697
Fixes #1694

Fixes UI Glitches

---

server/game/deck.js
server/lobby.js

Make sure correct images are rendered on the board

Pass the overridden house from lobby to game server

---

server/game/cards/04-MM/LadyLoreena.js
test/server/cards/04-MM/LadyLoreena.spec.js

Lady Loreena rework

---

server/game/cards/04-MM/DarkQueenGloriana.js
server/game/cards/04-MM/Fandangle.js
test/server/cards/04-MM/DarkQueenGloriana.spec.js
test/server/cards/04-MM/Fandangle.spec.js

MM Untamed card fixes

---

server/game/cards/04-MM/HighPriestTorvus.js
test/server/cards/04-MM/HighPriestTorvus.spec.js

MM High Priest Torvus

---

server/game/GameActions/ResolveFightAction.js
server/game/cards/04-MM/ArdentHero.js
test/server/cards/04-MM/ArdentHero.spec.js

I wrote a lot of test cases. Handling the fight defense damage was the most complex. Still thinking if I can simplify...

MM Ardent Hero

---

server/services/DeckService.js

See decks:
https://www.keyforgegame.com/deck-details/fe274c61-71d3-46bf-99d0-ad3248a975a6
https://www.keyforgegame.com/deck-details/b0a6287e-901a-4d3c-ada5-3ec151c6246c
https://www.keyforgegame.com/deck-details/0a4bf86c-37bf-4d13-a575-de0506a58ed3
Fixes #1529
This is very common with MM Exchange Officer.

Anomaly and Maverick may happen multiple time

---

server/game/cards/03-WC/SauryAboutThat.js
test/server/cards/03-WC/SauryAboutThat.spec.js

Fixes Saury About That and warded creature

---

server/services/DeckService.js

Add orb of wonder as a special card to get correct house data

---

server/game/cards/04-MM/NiffleKong.js
test/server/cards/04-MM/NiffleKong.spec.js

Fixes Niffle Kong reap/fight to be optional

---

server/game/Card.js
server/game/cards/03-WC/AutoLegionary.js
server/game/cards/04-MM/Animator.js
server/game/cards/04-MM/CyberClone.js
server/game/cards/04-MM/LieutenantGorvenal.js
server/game/cards/04-MM/ThePaleStar.js
server/game/effects.js
test/server/cards/03-WC/AutoLegionary.spec.js
test/server/cards/03-WC/Quadracorder.spec.js
test/server/cards/04-MM/ArdentHero.spec.js
test/server/cards/04-MM/LieutenantGorvenal.spec.js
test/server/cards/04-MM/ThePaleStar.spec.js

The Pale Star: Implements #1676 and add a test for #1677 - unable to reproduce
Auto-Legionary Errata #1664
Lieutenant Gorvenal's extra tests, but stiil unable to reproduce #1669
Removed fdescribe from Ardent Hero

The Pale Star and some random fixes

---

client/Components/GameBoard/CardImage.jsx
client/pages/Enhancements.jsx
server/scripts/fetchdata/CardImport.js
server/services/DeckService.js

Tweaked enhancement page to make it a bit more user friendly
fix bug with images that are not enhanced

Changed images to always download rather than refer to ffg servers

---

client/Components/Decks/DeckSummary.jsx
client/Components/GameBoard/GameConfiguration.jsx
client/Components/Games/PendingGamePlayers.jsx
client/Components/Navigation/LanguageSelector.jsx
client/Components/Navigation/Navigation.jsx
public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json

Minor layout changes, fixed Chinese language and locale keys

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/CardVisibility.js
server/game/cards/04-MM/TheArchivist.js
server/game/effects.js
server/game/gamesteps/house/HousePhase.js
test/server/cards/03-WC/Quadracorder.spec.js
test/server/cards/04-MM/TheArchivist.spec.js

MM The Archivist

---

server/game/cards/04-MM/Drecker.js
test/.eslintrc.js
test/server/cards/04-MM/Drecker.spec.js

Implement drecker

---

server/game/cards/04-MM/ForumOfGiants.js
test/server/cards/04-MM/ForumOfGiants.spec.js

Fixes and removes TODO from Forum of Giants

---

server/game/cards/04-MM/BurningGlare.js

Fixes Burning Glare prompt message

---

server/game/cards/04-MM/MonumentToShrix.js

Fixes Monument to Shrix message

---

client/pages/Enhancements.jsx
client/pages/Enhancements.scss
server/api/decks.js

Refactor enhancements to a table
Add server side validation for enhancements
Fixes #1733

Fix bug causing enhancements to freak out

---

server/game/cards/01-Core/GrimReminder.js
test/server/cards/04-MM/GrimReminder.spec.js

Grim Reminder not giving 1 chain

---

server/game/cards/04-MM/DarkCenturion.js

Fixes Dark Centurion add token instead of ward

---

server/game/cards/04-MM/ExchangeOfficer.js
server/game/cards/04-MM/NiffleKong.js
test/server/cards/04-MM/NiffleKong.spec.js

Fixes Niffle Kong and Exchange Officer

---

client/Components/Games/NewGame.jsx

Pass expansions for sealed games to the server

Fix sealed games

---

server/game/cards/04-MM/AmbassadorLiu.js
test/server/cards/04-MM/AmbassadorLiu.spec.js

Ambassador Liu should gain 2A when discarding Logos or Untamed

---

server/game/cards/04-MM/Munchling.js
server/game/cards/04-MM/SecuriDroid.js
server/game/cards/04-MM/UltraGravitron.js
test/server/cards/04-MM/Munchling.spec.js
test/server/cards/04-MM/UltraGravitron.spec.js

Fixes #1774
Fixes #1782
Fixes #1779

Securi-Droid, Munchling and UG fix

---

server/game/cards/04-MM/BlastFromThePast.js

Updated Blast from the Bast message

---

server/game/cards/03-WC/Ghosthawk.js
test/server/cards/03-WC/Ghosthawk.spec.js

Fix for Gladiodontus and GH

---

client/Components/Lobby/LobbyChat.jsx
client/Components/Lobby/LobbyChat.scss

Improve UX around scrolling
Fixes #1813

Refactor lobbychat component to use functions

---

client/archonMaker.js

setting crossorigin to anonymous https://github.com/fabricjs/fabric.js/issues/6367 maybe that'll help
setup more try/catches for circular text

calm the sentry errors from fabric AWESOMENESS

---

client/archonMaker.js

MOAR decklist fixes

---

package-lock.json
package.json
server/api/account.js

avatar importer -> fabric

---

server/game/cards/04-MM/CitizenShrix.js

Fixed game message of Citizen Shrix

---

server/game/cards/03-WC/AutoLegionary.js
test/server/cards/03-WC/AutoLegionary.spec.js

Fixes #1843
Straightforward fix to Auto-Legionary

Fix autolegionary applying effects to other creatures

---

client/archonMaker.js

bumped down the image a quality a smidge

added await curvetext and fixed mav icons

---

server/game/cards/04-MM/Shadowsaurus.js
test/server/cards/04-MM/Shadowsaurus.spec.js

Shadowsaurus bugfix

---

server/scripts/fetchdata/CardImport.js

Fixes #1871
I sort the card DB in newest -> oldest so TCO will grab the newest images

WTF, they update images

---

client/styles/index.scss

Unless this is considered too small for the text in other buttons.

Fixes #1808

---

server/game/cards/04-MM/Drecker.js
test/server/cards/04-MM/Drecker.spec.js

Fixes #1699 
Fixes #1793 
Fixes #1771

Change Drecker to an interrupt

---

server/game/gamesteps/setup/AdaptiveDeckSelectionPrompt.js
server/game/gamesteps/setup/ChainBiddingPrompt.js
server/game/gamesteps/setup/setupphase.js

Project "they brought whaaaaaaa?"

---

server/game/Card.js
test/server/cards/02-AoA/ShadowOfDis.spec.js

Fixes #1867 
Fixes #1455 
Fixes #1666 
Fixes #1624

Blanked effects fix

---

server/game/GameActions/ResolveFightAction.js
server/game/cards/04-MM/LieutenantGorvenal.js
test/server/cards/04-MM/LieutenantGorvenal.spec.js

Fixes #1822
Alternative fix to #1823

Add attackerClone to onFight

---

server/game/Effects/CopyCard.js
test/server/cards/03-WC/MimicGel.spec.js

Fix 2x Mimic Gel error

---

server/game/cards/04-MM/NovuDynamo.js
test/server/cards/04-MM/NovuDynamo.spec.js

Dynamo Fix

---

client/Components/Decks/DeckStatus.jsx
server/lobby.js
server/services/DeckService.js

Update submodule
Add support for tagging impossible decks

Impossible decks

---

server/game/cards/04-MM/EssenceScale.js
test/server/cards/04-MM/EssenceScale.spec.js

Essence Scale fix

---

server/game/GameActions/ForgeAction.js
server/game/cards/01-Core/EpicQuest.js
server/game/cards/02-AoA/MightMakesRight.js
server/game/cards/02-AoA/Redacted.js
server/game/cards/03-WC/Triumph.js
server/game/cards/04-MM/Turnkey.js
test/server/cards/02-AoA/Redacted.spec.js
test/server/cards/04-MM/Turnkey.spec.js

Turnkey - Add context to forgeKey action to apply a more recent modifier to forge at no cost

---

server/game/Card.js
server/game/GameActions/DealDamageAction.js
test/server/cards/04-MM/ShoulderId.spec.js

Remove old ward code

---

client/Components/Games/NewGame.jsx

Fixes a bug where sealed games don't work for tournaments

Send the expansions info with a tournament game too

---

client/Components/GameBoard/Messages.jsx
client/Components/GameBoard/Messages.scss
server/game/game.js
server/game/gamechat.js
server/pendinggame.js

New styles to distinctly colour each player's portion of the game log 

---

server/game/cards/01-Core/OneLastJob.js
server/game/cards/03-WC/HarvestTime.js
test/server/cards/01-Core/OneLastJob.spec.js
test/server/cards/03-WC/HarvestTime.spec.js

Fixes Harvest Time and One Last Job not considering warded creatures

---

client/Components/Profile/ProfileMain.jsx
client/constants.js
client/pages/Lobby.jsx
server/db/index.js
server/services/UserService.js

Fix unlink
Fix client id
remove banner

More patreon fixes

---

.vscode/launch.json
client/Components/GameBoard/Card.jsx
client/Components/GameBoard/PlayerRow.jsx
client/redux/actions/game.js
client/redux/reducers/lobby.js
package-lock.json
package.json
server/game/Card.js
server/game/game.js
server/game/gamechat.js
server/gamenode/gameserver.js

Replace the current system of just sending the entire game state every update with one that uses a diff/patch system. The resulting network traffic is considerably reduced and is now flat throuought a game, rather than getting worse as time goes on

Incremental messaging

---

client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerRow.jsx
client/archonMaker.js
client/pages/Privacy.jsx
client/redux/reducers/lobby.js
server/game/GameObject.js
server/game/game.js
server/lobby.js
server/pendinggame.js

Fix card backs not showing
Fix images being rebuilt when the deck has not changed
Fix deck popup disappearing when not clicked
Fix spectating a game more than once
Remove redundant references to factions
Fix top card of deck showing incorrectly

Various UI fixes

---

client/Components/Decks/DeckList.jsx
server/services/DeckService.js

Also, make it case insensitive
Fixes #1972

Fix deck name search to actually look at the name column

---

server/game/cards/02-AoA/DirectorOfZyx.js
server/game/cards/03-WC/GamblingDen.js
server/game/cards/03-WC/GeneralOrder24.js
server/game/cards/03-WC/TheFloorIsLava.js
server/game/cards/04-MM/ForumOfGiants.js
server/game/cards/04-MM/LiamSay.js
server/game/cards/04-MM/NovuDynamo.js
server/game/cards/04-MM/ZWaveEmitter.js
test/server/cards/03-WC/GamblingDen.spec.js
test/server/cards/04-MM/LiamSay.spec.js

Fix tests
Fixes #1714
Fixed #1920

Replace onPhaseStart == 'key' with onBeginRound

---

client/Components/GameBoard/Keys.jsx

Sort keys by forgedness, then name

---

client/Components/GameBoard/Keys.jsx

Key forged order fix

---

client/pages/Lobby.jsx

Also, refactor whole lobby component :D

Remove tournament banner

---

server/game/cards/04-MM/CuriaSaurus.js

Fixes Curia Saurus considering artifacts

---

client/Components/Games/GameLobby.jsx

gamelink twerk

---

client/Components/Games/GameOptions.jsx

Renamed "Hide deck list" option

---

client/Components/Games/TournamentLobby.jsx

fix tournament participant names

---

client/Components/Decks/CardBack.jsx
client/Components/Decks/IdentityCard.jsx
client/Components/GameBoard/CardImage.jsx
client/Components/GameBoard/IdentityCard.jsx
client/archonMaker.js

fabric error handling

---

client/Components/Decks/CardBack.jsx
client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardImage.jsx
client/Components/GameBoard/IdentityCard.jsx
client/archonMaker.js

cards only.  i'll rework cardbacks and decklist in another PR

Shitty monitor fix

---

client/Components/Decks/IdentityCard.jsx
client/archonMaker.js

This will lower the number of filters used
manually activate the webGl filters

ReFabric Redo sizing
