.vscode/launch.json
package.json

* outDir deprecated in launch.json  (Removed - not used)
* "the options [safe] is not supported" (Updated monk to version 4)

Fix two warnings that were occurring during development.

---

docker-compose.yml

According to [1] Mapping data to your harddrive does not work on Windows & OS X.
Using data-volumes we can achieve persistent storage and it should work cross-platform.
Persistent against docker-compose down.
Will be wiped by docker-compose down -v
[1] https://hub.docker.com/_/mongo (scroll down to Caveats)

mongodb: use data-volume for x-platform compat

---

server/game/cards/02-AoA/AncientYurk.js
server/game/cards/02-AoA/OldYurk.js

Action can still be cancelled, but cannot be confirmed without selecting 2 cards (old yurk) or 3 cards (ancient yurk)
https://github.com/keyteki/keyteki/issues/153

Forced 'exact' on Old/Ancient Yurk play effect.

---

server/game/gamesteps/handlermenuprompt.js

HandlerMenuPrompt should use properties.source as a return value in getAdditionalPromptControls.
It is a small change, but it has impact, since this is an UiPrompt. I am testing locally more.

Fixed SpanglerBox where control source is different then properties source

---

client/Components/Decks/DeckSummary.jsx

Fixed an issue where the deck summary card list was breaking to another column. ( Fixes #283)
Fixed the order which the houses are displayed to be consistent with the house images. (enhancement)
Added dataset to <div> to avoid comparison with card name (div text). It is more robust and prepared for future i18n (enhancement)

UI: Fix deck summary with long creature list

---

server/game/GameActions.js
server/game/GameActions/TransferAmberAction.js
server/game/cards/01-Core/InterdimensionalGraft.js
server/game/cards/02-AoA/AnahitaTheTrader.js
test/server/cards/02-AoA/AnahitaTheTrader.spec.js

Done as two separate game actions because arraying them in one lastingEffect was throwing errors.
Fixes #288

Change IG from "steal" to "gain/lose" so it behaves properly when things that affect steal are in play

---

server/game/cards/02-AoA/DestructiveAnalysis.js
server/game/player.js
test/server/cards/01-Core/SampleCollection.spec.js
test/server/cards/02-AoA/DestructiveAnalysis.spec.js

If you have an opponents creature in your archive, and it leaves, it will now return to their hand in all cases (including if removed by dysania or tantadlin).
modified destructive analysis to only deal damage based on actual purged creatures (aka your own) rather than *all* creatures, as if it is an opponent's, it doesn't get purged and no damage is dealt.
added test for destructive analysis.
Modified test for sample collection for Tantadlin edge case.
Fixes #308

fix for archived opp creature behaviour

---

client/Components/Decks/DeckSummary.jsx
less/deckbuilder.less

DeckSummary.jsx to use table CSS instead of columns and 'page-break: avoid' (#342)
It handles DIV expansion better. Useful for large card names (when i18n is in place)

DeckSummary.jsx to use table CSS (#342)

---

server/game/cards/01-Core/NerveBlast.js

Added message to Nerve Blast to show which creature was targeted when dealing damage.
Fixes #407

Fix for Nerve Blast does not inform which creature took damage (#407)

---

server/game/Card.js
server/game/cards/02-AoA/MightMakesRight.js
test/server/cards/02-AoA/MightMakesRight.spec.js

Added modifiedPower field to card clone/snapshot, to capture actual effective power of card (including modifiers) at time of snapshot, and updated Might Makes Right to consider this value instead of printed power.
Also updated Might Makes Right test to consider this case (modified power of selected cards > 25, printed power < 25)
Fixes #264 
Fixes #332 
Fixes #414

Fix for Might Makes Right not considering power modifiers

---

less/deckbuilder.less

Moved the padding to cards-no-break to enable browser calculation no-break
Fixes #416

Fixed deck card list layout

---

client/Components/GameBoard/PlayerRow.jsx

We are now able to see opponent's card in own archive (fixed by previous Card.js commit)
Fixes #212

Fixed archive being clickable by opponent (all cards were face down)

---

server/game/GameActions/DealDamageAction.js

Update armor token while dealing damage if action says no game state update. It is consistent with damage token being added
Do you think it is better to put this in the event bellow?
Fixes #441

Update armor token while dealing damage

---

server/game/Card.js

, but delay implementation of ignoring state change for damage (noGameStateCheck )

Handle onDamageDealt with ward

---

server/game/cards/03-WC/DoctorDriscoll.js
test/server/cards/03-WC/DoctorDriscoll.spec.js

Would we want to skip the prompt to select a creature to heal when nothing is damaged?
This is how Guardian Demon behaves, but I wasn't sure how to still allow you to use the action in this case. Similar to how you can use Mindwarper's action when your opponent has no aember or no creatures.

Doctor Driscoll

---

test/server/cards/01-Core/ChaosPortal.spec.js

Tests added to cover the Chaos Portal + Duskwitch (omega cards) interaction mentioned in #690.
It appears that the underlying issue was actually fixed by b393d6c and just hasn't made it to production yet.

Add tests for Chaos Portal

---

server/game/cards/03-WC/FangtoothCavern.js

Fangtooth Cavern reads "At the end of your turn, destroy the least powerful creature.". Controller should be "any". I've not yet tested it, as I have a while must yet see how to setup keyteki :) But I suspect that this simple change is correct.

Fangtooth Cavern fix

---

test/server/cards/03-WC/FangtoothCavern.spec.js

Switched controller of mighty-tiger & dust-pixie, to check if controller of card doesn't matter for Fangtooth cavern effect.
Switched selected house to logos, to check if cavern passive effect is working regardless of chosen house.

Added additional tests for Fangtooth cavern

---

Dockerfile
docker-compose.yml
server/gamenode/Dockerfile

This PR includes a few updates - I've left the individual commits for each un-squashed in case we didn't want keep some of those changes. There are more details with each commit, but briefly:
- We pin the node major version to 10. This avoids an incompatibility between ZMQ and node@13. We also get to match up versions with production.
- Minor change to tag the lobby and game nodes with different image names (rather than distinguishing with versions). It looks like the images being built are actually identical (just different start-up commands and ports exposed) - if there's interest we could speed up build times considerably by having a single image that gets referenced by both services (i.e. still two containers, but just one image). This might be nice as the images are fairly large, …

Docker-Compose Updates

---

server/game/GameActions/MoveOnBattlelineAction.js
test/server/cards/03-WC/ThoriumPlasmate.spec.js
test/server/cards/03-WC/Weasand.spec.js

MoveOnBattlelineAction was determining a new index for moved cards based on a battleline with the card being moved still in it.
The "move" happens by first splicing out the card to be moved then splicing it back it. This means we should calculate our "slice back in" index assuming the moved card is not in the battleline.
Fixes #939

Fix to Thorium Plasmate

---

client/Components/Decks/DeckList.jsx

Currently in the deck selection screen, if you press the <return> key the page is submitted, and the UI reloads. This fix adds a form submit handler so that the submit action is avoided.

Adding handler for <return> for deck component. 

---

server/game/cards/03-WC/ChantOfHubris.js
test/server/cards/03-WC/ChantOfHubris.spec.js

Card text says "Play: Move 1 A from a creature to another creature.",

Fix chant of hubris allowing the same card as second target

---

server/game/cards/04-MM/ScoutPete.js
test/server/cards/04-MM/ScoutPete.spec.js

Per this issue, I've implemented Scout Pete:
* New test case passes
* Lint passes
* In game testing works (overwrote other creature temporarily to test this)
Note, I looked for a more elegant way to support this card- this was the best compromise that I could find after many hours of trials.

MM: Star Alliance - Scout Pete

---

server/game/cards/03-WC/UnitedAction.js
server/game/game.js
test/server/cards/03-WC/UnitedAction.spec.js

Fixes #1150
This was a bit trickier as upgrades are only counted on cardsInPlay, so I cannot pass player.cardsInPlay to getHousesInPlay. I added a new player filter to the game's getHousesInPlay function

Fixes UnitedAction not considering upgrades

---

client/Components/GameBoard/Messages.jsx

Allows "amber." to relabel to 'Æmber.'
Fixes #1056

fix for 'amber.' relabel

---

server/game/GameActions/DestroyAction.js
server/game/cards/04-MM/Bonesaw.js
server/game/player.js
test/server/cards/04-MM/Bonesaw.spec.js

I mimicked the approach used for Alaka and added a `creatureDestroyed` attribute to players.

feat: implement bonesaw

---

server/game/cards/04-MM/MatterMaker.js
test/server/cards/04-MM/MatterMaker.spec.js

Added Matter Maker card per issue:
* New test case passes
* Lint passes
Note: I could not find documentation that "*" would work for 'house:', but it does. 
I also tried:
* leaving it out
* the value ''
* providing a function doing something like done in Val Jerico - like: `(card, context) => context.player.activeHouse`. But it seems that "house" does not accept a function. 
However, using "*" does pass the test for both Star Alliance and Non-Star Alliance turns.

MM: Star Alliance - Matter Maker

---

server/game/GameActions/RemoveTokenAction.js
server/game/cards/04-MM/MonumentToPrimus.js
test/server/cards/04-MM/MonumentToPrimus.spec.js

It allows picking from creatures without amber
Changed ConsulPrimus to also allow picking from creatues without amber

MM Monument to Primus

---

server/game/GameActions/RemoveTokenAction.js
server/game/cards/03-WC/ChantOfHubris.js
server/game/cards/03-WC/Mug.js
test/server/cards/03-WC/ChantOfHubris.spec.js

According to https://archonarcana.com/Mug , Mug allows picking creatures without amber
I believe Chant of Hubris should follow the same guide as the text is the same.

Fix Chant of Hubris not allowing to pick a creature without amber

---

server/gamenode/gameserver.js

Redis switch broke the onCardData hook.
Previous call returned a object with a cardData attribute,
new version now directly returns the card array.

Redis retuns array directly, not an object

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/01-Core/GrimReminder.js
server/game/cards/04-MM/BurningGlare.js
server/game/cards/04-MM/EtansJar.js
test/server/cards/04-MM/BurningGlare.spec.js

A few small fixes:
- Burning glare text did not fit on a button (Not sure about with the new UI anyway, though)
- Etan's jar didn't tell the opponent what card they were banned from playing
- Grim reminder archived actions etc. as well as creatures.

Minor fixes to mass mutation cards

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/ko.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/gamesteps/handlermenuprompt.js

This feature used to work for mavericks, but with Enhancements, it become more complex to aggregate, so it is better to have duplicate buttons.
Fixes #1791 
Screenshots bellow shows a prompt with 3 buttons:
- Exchange Officer in "native" house SA
- Exchange Officer maverick Shadows with Enhancements 
- Exchange Officer maverick Shadows without Enhancements
I think a good enhancement would be:
1) Put a house icon next to the card name when it is maverick
2) Write a blue text when the card has Enhancement
What do you think, @cryogen ?

Using card.uuid as prompt identifier, instead of aggregating quantities.

---

server/game/cards/04-MM/Sinder.js

Sinder
Reap: Destroy a friendly creature.
Currently allows selecting an artifact (or upgrade to be destroyed)

Sinder should only allow selecting a creature

---

client/Components/GameBoard/Messages.jsx
client/Components/GameBoard/Messages.scss
server/game/game.js

Hopefully makes reading back through game log much easier as the start and end of each turn is much easier to see:
**NOTE:** The `startofround` div doesn't currently appear for turn 1 of player 1. This would make more sense if that was added.

Added more distinct headers to the start of each round in message log.

---

server/game/cards/03-WC/FinchCloak.js
test/server/cards/03-WC/FinchCloak.spec.js

I believe that the array of game actions could eventually be played in incorrect order or a race condition on the triggeredSteal could cause an incorrect order of execution.
Fixes #1950

Finch Cloak was behaving incorrectly in some situations

---

client/Components/GameBoard/GameBoard.scss
client/styles/index.scss

Several components cause the play area to exceed 100% body height. This leads to an unsightly (and useless) scrollbar that sits next to the message log (which has it's own scrollbar). Suppress the outer scrollbar as it's never of any use.
before:
after:

Suppress vertical scrollbar on whole play area

---

client/Components/GameBoard/GameBoard.scss
client/styles/_variables.scss

Fixes #2076
Not sure if there's a reason we've avoided layering things in this order before now? 
Changes this:
To this:

Display own upgrades over the top of opponents battleline.

---

client/pages/NodesAdmin.jsx
client/styles/index.scss

It's a tiny bit squished on the edges, but better here than every single player prompt version being stretched.

Fix background image scaling on node admin page "refresh" button.

---

server/game/DelayedEffect.js
server/game/GameActions/LastingEffectAction.js
server/game/cards/04-MM/Commandeer.js
server/game/cards/04-MM/WildBounty.js
test/server/cards/04-MM/Commandeer.spec.js

Fixes #2109 
Commandeer:
```javascript
2020-12-04 16:39:43 player1 plays Commandeer
2020-12-04 16:39:43 player1 gains an amber due to Commandeer's bonus icon
2020-12-04 16:39:43 player1 uses Commandeer to capture an amber after playing a card for the remainder of the turn
2020-12-04 16:39:43 player1 plays Sequis
2020-12-04 16:39:43 player1 uses Commandeer to capture amber from their opponent and place on Sequis
```
Wild Bounty (message was not being printed)
```javascript
2020-12-04 16:40:10 player1 plays Wild Bounty
2020-12-04 16:40:10 player1 uses Wild Bounty to apply a lasting effect
2020-12-04 16:40:10 player1 plays Fertility Chant
2020-12-04 16:40:10 player1 gains an amber due to Fertility Chant's bonus icon
2020-12-04 16:40:10 player1 gains an amber due to Fertility Chant's bonus …
```

Fixes messaging of delayed effect + gameaction

---

server/game/cards/03-WC/StiltKin.js
test/server/cards/03-WC/StiltKin.spec.js

Fixes #2123
```javascript
2020-12-09 13:52:01 ==================== House phase - player1 ====================
2020-12-09 13:52:01 player1 chooses brobnar as their active house this turn
2020-12-09 13:52:01 ==================== Main phase - player1 ====================
2020-12-09 13:52:01 player1 uses Stilt-Kin to reap with Stilt-Kin
2020-12-09 13:52:01 player1 plays Cowfyne
2020-12-09 13:52:01 player1 uses Stilt-Kin to ready and fight with Stilt-Kin
2020-12-09 13:52:01 player1 uses Stilt-Kin to make Stilt-Kin fight Troll
```

Fixes Stilt Kin message

---

server/game/cards/04-MM/Ransack.js
test/server/cards/04-MM/Ransack.spec.js

Fixes #1944
Sample game message:
```
2021-01-05 16:25:46 ==================== House phase - player1 ====================
2021-01-05 16:25:46 player1 chooses shadows as their active house this turn
2021-01-05 16:25:46 ==================== Main phase - player1 ====================
2021-01-05 16:25:46 player1 plays Ransack
2021-01-05 16:25:46 player1 uses Ransack to steal 1 amber from player2; and discard Urchin
2021-01-05 16:25:46 player1 uses Ransack to resolve its effect again
2021-01-05 16:25:46 player1 uses Ransack to steal 1 amber from player2; and discard Miasma Bomb
2021-01-05 16:25:46 player1 uses Ransack to resolve its effect again
2021-01-05 16:25:46 player1 uses Ransack to steal 1 amber from player2; and discard Miasma
2021-01-05 16:25:46 player1 uses Ransack to resolve its …
```

Fixes Ransack not discarding when stealing didn't trigger

---

server/game/GameActions.js
server/game/GameActions/ResetTideAction.js
server/game/GameActions/index.js
server/game/cards/05-DT/TrialByWater.js
test/helpers/integrationhelper.d.ts
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/05-DT/TrialByWater.spec.js

Renamed "neutralize" to "reset" tide to match card text, state is still called NEUTRAL, which I believe is a good term.

DT: Trial by Water

---

server/game/cards/02-AoA/ShardOfGreed.js
server/game/cards/02-AoA/ShardOfHate.js
server/game/cards/02-AoA/ShardOfHope.js
server/game/cards/02-AoA/ShardOfKnowledge.js
server/game/cards/02-AoA/ShardOfLife.js
server/game/cards/02-AoA/ShardOfPain.js
server/game/cards/02-AoA/ShardOfStrength.js
test/server/cards/02-AoA/ShardOfGreed.spec.js
test/server/cards/02-AoA/ShardOfHate.spec.js
test/server/cards/02-AoA/ShardOfHope.spec.js
test/server/cards/02-AoA/ShardOfKnowledge.spec.js
test/server/cards/02-AoA/ShardOfLife.spec.js
test/server/cards/02-AoA/ShardOfPain.spec.js
test/server/cards/02-AoA/ShardOfStrength.spec.js

Calculate the number of shards as "1 + other shards". By doing this, cards such as Remote Access will count the used shard as theirs.
Fixes #2274
Fixes #2278

Fixes Shards vs. Remote Access and Borrow

---

server/game/cards/02-AoA/YzphyzKnowdrone.js
server/game/player.js
test/server/cards/02-AoA/YzphyzKnowdrone.spec.js

Fixes #2272
Message when archived card is actually purged:
```
2021-03-08 13:31:21 ==================== Main phase - player1 ====================
2021-03-08 13:31:21 player1 plays Yzphyz Knowdrone
2021-03-08 13:31:21 player1 uses Yzphyz Knowdrone to archive a card
2021-03-08 13:31:21 player1 uses Yzphyz Knowdrone to purge Troll
2021-03-08 13:31:21 player1 uses Yzphyz Knowdrone to stun Hunting Witch
```
Message when archived card is not purged (but returned to owner's hand):
```
2021-03-08 13:31:21 ==================== Main phase - player1 ====================
2021-03-08 13:31:21 player1 plays Yzphyz Knowdrone
2021-03-08 13:31:21 player1 uses Yzphyz Knowdrone to archive a card
2021-03-08 13:31:21 player1 uses Yzphyz Knowdrone to purge Zorg
2021-03-08 13:31:21 Zorg leaves the archives and …
```

Fixes Yzphyz Knowdrone's logging which card was purged / creature was stunned

---

server/game/Effects/cannotrestriction.js
server/game/cards/02-AoA/Lamindra.js
server/game/cards/03-WC/MimicGel.js
server/game/cards/04-MM/ArdentHero.js
test/server/cards/03-WC/EDAIEdie4x4.spec.js
test/server/cards/03-WC/MimicGel.spec.js
test/server/cards/04-MM/Chronus.spec.js
test/server/cards/04-MM/CyberClone.spec.js
test/server/cards/04-MM/ThePaleStar.spec.js

Also fixes cards that did not go well with Mimic Gel due to $this: Lamindra and Ardent Hero
(Possibly fixes MG and Scowly Caper, but needs validation)
Fixes #2178

Fixes Mimic Gel not copying Deploy keyword

---

public/locales/de.json
public/locales/en.json
public/locales/es.json
public/locales/fr.json
public/locales/it.json
public/locales/ko.json
public/locales/pl.json
public/locales/pt.json
public/locales/th.json
public/locales/zhhans.json
public/locales/zhhant.json
server/game/cards/05-DT/SelectivePreservation.js
test/server/cards/05-DT/SelectivePreservation.spec.js

This pr updates Selective Preservation to prompt for each unique power level, instead of all creatures at once.
Note, I added the ```effect: 'Select creatures for each power to not destroy.',``` so that I could have a no-op for the pre-then block.

updated Selective Preservation to prompt for each power

---

server/game/GameActions/MoveToBottomAction.js
server/game/cards/05-DT/DrawnByTheDepths.js

In this PR I've updated MoveToBottomAction to determine which players deck to update based on the owner of the card being moved. This makes sense since moving a card to bottom of a deck implies the card should stay in the same deck. 
From feedback in this PR;
https://github.com/keyteki/keyteki/pull/2370
(Great idea Romano)

update MoveToBottomAction to determine player using card.owner

---

server/game/cards/05-DT/GrandAllianceCouncil.js
test/server/cards/05-DT/GrandAllianceCouncil.spec.js

fixes the issue reported here: https://github.com/keyteki/keyteki/issues/2427
I fixed this by making it so that creatures can't be targeted for destruction if there is only 1 creature of that house in play, with this in the filter:
`context.game.creaturesInPlay.filter((card) => card.hasHouse(house)).length > 1`

fix for issue 2427

---

server/game/costs.js
test/server/cards/01-Core/PhaseShift.spec.js
test/server/cards/02-AoA/HelperBot.spec.js
test/server/cards/03-WC/CaptainValJericho.spec.js
test/server/cards/03-WC/ComOfficerKirby.spec.js
test/server/cards/04-MM/MatterMaker.spec.js

This PR is made to fix the Helper Bot task in [this list](https://github.com/keyteki/keyteki/issues/2153). I added tests to Helper Bot's, Com. Officer Kirby's, and Jericho's specs to cover this interaction. It should also apply to CXO Taber, but I didn't add tests for that. Should I?
What is `noActiveHouseForPlay`? Does there need to be a case before the effects part to cover the positive case of this effect?
In this PR, I could see:
- adding comments in costs.js to justify why effects go above active house (i.e. a rules reference)
- moving the "beforeEach" in Helper Bot and Jericho specs into the `it` because there's only one test
- deleting the Jericho test because it's redundant (because I think they all count as a `StaticEffect`?)
What do you think?
EDIT (2021/10/16):
I added a prompt …

Costs: paying w/ effects & effect selection prompt

---

Dockerfile

Some javascript functions used are not available in node 10, such as [Array.prototype.flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) and [Array.prototype.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat).
These functions are used in the following cards:
https://github.com/keyteki/keyteki/blob/eca831ec8ba43ebb231c098275f131e06c445bdb/server/game/cards/05-DT/ExploratoryCraft.js#L17
https://github.com/keyteki/keyteki/blob/eca831ec8ba43ebb231c098275f131e06c445bdb/server/game/cards/05-DT/WipeClear.js#L12
Upgrade to node 12 addresses this.
Fixes #2833
Testing done:

Update node to 12 in Dockerfile

---

server/game/GameActions/PlaceUnderAction.js
test/server/cards/01-Core/Masterplan.spec.js
test/server/cards/02-AoA/Jargogle.spec.js

Fixes #2758
I've always asked myself why PlaceUnderAction marked the card in "purged", even though not put in purge pile. I changed it to under without a corresponding pile.

Change PlaceUnderAction location from purged to under

---

server/game/cards/05-DT/GroundbreakingDiscovery.js
test/server/cards/05-DT/GroundbreakingDiscovery.spec.js

Previously, upgrades on warded creatures would remain if the creature they were attached to managed to survive GBD.
It might have been cleaner to go upstream and include upgrades in whatever is initially populating `context.game.cardsInPlay`, I wasn't sure if upgrades were being left out of that list intentionally.
Fixes #2826

Make Groundbreaking Discovery  destroy upgrades

---

server/game/cards/01-Core/Hecatomb.js
server/game/cards/02-AoA/MartyrsEnd.js
test/server/cards/01-Core/Hecatomb.spec.js
test/server/cards/02-AoA/MartyrsEnd.spec.js

make Hecatomb sequential so destroyed effects trigger at the same time, and also does not award amber for creatures that were not destroyed

---

client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/GameBoard.scss
client/Components/GameBoard/PlayerStats.jsx
client/constants.js
server/constants.js
server/game/player.js
test/server/tide.spec.js

Mostly reverts https://github.com/keyteki/keyteki/pull/2813/files.
The `raiseTide` game action still raises the tide even if neither player requires the tide. I added a disabled test for this because I think we should consider changing the game action to prevent that.
Why is the id for the expansions a string on the client and an integer on the server? I think if we were to write a test for this I need to include the expansion id in the game setup.
Demo:

only show the tide card when a dark tidings deck is being played

---

server/game/cards/03-WC/BlasterCard.js
test/server/cards/03-WC/ChansBlaster.spec.js
test/server/cards/03-WC/FranesBlaster.spec.js
test/server/cards/03-WC/GarciasBlaster.spec.js
test/server/cards/03-WC/IngramsBlaster.spec.js
test/server/cards/03-WC/KhrkharsBlaster.spec.js
test/server/cards/03-WC/KirbysBlaster.spec.js
test/server/cards/03-WC/MolinasBlaster.spec.js
test/server/cards/03-WC/QincasBlaster.spec.js
test/server/cards/03-WC/WallsBlaster.spec.js

You can still choose the option, but all targets are invalidated.
I did not expect to have to change the text in Ingram's Blaster's spec line 238. "Choose a creature" -> "Choose a creature to heal"

disallow moving blasters once attached to their associated officer

---

server/game/GameActions/CaptureAction.js
server/game/cards/06-WoE/YxlTheIronCaptain.js
test/server/cards/06-WoE/YxlTheIronCaptain.spec.js

This is the first time multiple creatures are capturing an amount that is more than 1, so it required a change to make sure too much amber wasn't taken from the opponent.  For now the leftover just goes to the last-clicked creature, but maybe we want to improve that interface a bit in the future.
Issue: #2903

WoE: implement Yxl the Iron Captain

---

server/game/cards/06-WoE/BatarielOfTheGrey.js
test/server/cards/06-WoE/BatarielOfTheGrey.spec.js

Marking as a draft - wasn't seeing opposing disciples show up as cards in play for player 2, i.e. `this.player2.player.cardsInPlay.length === 0` in the test below. I'll revisit but figured I'd toss up the draft in case it was related to something not fully implemented with tokens (non-token cards seemed to show up as I expected).
See: #2904

WoE: Implement Batariel of the Grey

---

server/game/cards/01-Core/EtherSpider.js
server/game/cards/06-WoE/Braindart.js
server/game/cards/06-WoE/CelestialGorm.js
server/game/cards/06-WoE/CornerTheMarket.js
server/game/cards/06-WoE/EndlessHordes.js
server/game/cards/06-WoE/EpicPoem.js
server/game/cards/06-WoE/FleaMarket.js
server/game/cards/06-WoE/GedHammer.js
server/game/cards/06-WoE/GemcoatVendor.js
server/game/cards/06-WoE/GezdrutyoTheArcane.js
server/game/cards/06-WoE/Initiation.js
server/game/cards/06-WoE/Kaboom.js
server/game/cards/06-WoE/KelpingHands.js
server/game/cards/06-WoE/MagistrateCrispus.js
server/game/cards/06-WoE/MembershipDrive.js
server/game/cards/06-WoE/MightClub.js
server/game/cards/06-WoE/Muster.js
server/game/cards/06-WoE/StrongerTogether.js
server/game/cards/06-WoE/Symposium.js
server/game/cards/06-WoE/TalentScout.js
server/game/cards/06-WoE/TheAmberRoad.js
server/game/cards/06-WoE/TokenOfAppreciation.js
server/game/cards/06-WoE/Trader.js
test/server/cards/06-WoE/EpicPoem.spec.js

closes #3233
Add `effect` messages to cards which use `gameActions.sequential`. Tested using the environemnt variable `DEBUG_TEST=1` to show messages.
Before:
`"[player] uses [card] to do several things"`
After:
Card-specific text
n.b., for Corner the Market, I could not figure out how to show specific messages based on discard vs archive
https://github.com/keyteki/keyteki/blob/9b522d7e14f6114cab5f9c7bffd4bc40bcf8d7ed/server/game/cards/06-WoE/CornerTheMarket.js#L49-L54

Add effect messages

---

server/game/cards/06-WoE/CloneHome.js
server/game/cards/06-WoE/HireOn.js
server/game/cards/06-WoE/Muster.js
server/game/cards/06-WoE/PressGang.js
server/game/cards/06-WoE/Recruit.js
server/game/cards/06-WoE/Teamwork.js
test/server/cards/06-WoE/CloneHome.spec.js

These all need to be sequential actions, in case making a token effects the archive condition.  Clone Home (and its test) was broken.
Fixes #3274

WoE: fix and clean up the "make a token" cards in each house

---

server/game/cards/06-WoE/Friendship.js
test/server/cards/06-WoE/Friendship.spec.js

~~Not working yet. The result of the last `it` show that none of the creatures take damage. I think using applyDamage to redirect the divided damage is likely the problem.~~
EDIT: [this commit](https://github.com/keyteki/keyteki/pull/3178/commits/a5527ccd9d0822991d82c11adf27169f84f4f8da) add tokens instead of applying damage, and this allows the neighboring Friendship test to pass.

Woe friendship

---

server/game/CardVisibility.js
server/game/GameActions/RevealAction.js
server/game/cards/04-MM/TheArchivist.js
server/game/cards/06-WoE/NearFutureLens.js
server/game/effects.js
server/game/player.js
test/server/cards/06-WoE/NearFutureLens.spec.js

Basic idea here is to print a message for the new top card every time
the top card of the deck changes, and to always have that top card
marked as not "facedown".  Currently unable to test it in the actual
UI but hopefully it works???
Fixes #3170

WoE: implement Near-Future Lens

---

server/game/GameActions/PlaceUnderAction.js
test/server/cards/06-WoE/ReplayPod.spec.js

Until Replay Pod, it was never used on cards in the play area.
Fixes #3309
Fixes #3311

WoE: using placeUnder from the play area should return amber

---

server/game/costs.js
server/game/game.js
test/server/cards/06-WoE/EndlessHordes.spec.js

Because tokens that die end up changing their name back to their printed name, and then would no longer count.
Fixes #3328

WoE: use card names to apply the rule of 6, not cards themselves

---

server/game/GameActions/MakeTokenCreatureAction.js
server/game/cards/06-WoE/TheVisibleHand.js
test/server/cards/06-WoE/TheVisibleHand.spec.js

If you have no deck, the make token action should still fire so that we can print the cards to the chat.
Fixes #3330

WoE: The Visible Hand should always reveal your hand

---

server/game/GameActions/MoveUpgradeToFlank.js
test/server/cards/06-WoE/Pupgrade.spec.js

Otherwise, it gets treated like an upgrade and is never removed from `cardsInPlay`.
Fixes #3331

WoE: clear Pupgrade parent when moved to battleline

---

server/game/GameActions/ReturnToDeckAction.js
server/game/player.js

If cards are being put on top of the deck just before a shuffle, there is no need to print them.
Fixes #3365

WoE: NFL shouldn't print card names before a shuffle

---

server/game/cards/06-WoE/ThePromisedBlade.js
test/server/cards/06-WoE/ThePromisedBlade.spec.js

It was treating `then:` as another target.
Fixes #3383

WoE: don't let The Promised Blade target any artifact

---

server/game/cards/06-WoE/ChancellorDexterus.js
test/server/cards/06-WoE/ChancellorDexterus.spec.js

It didn't work when Dexterus was on the left flank.
And add another test for duration of effect.

WoE: fix Chancellor Dextrus to find the correct right neighbor

---

server/game/deck.js
server/game/game.js
server/game/gamesteps/setup/AdaptiveDeckSelectionPrompt.js
test/helpers/deckbuilder.js
test/helpers/gameflowwrapper.js
test/helpers/integrationhelper.js
test/server/tokens.spec.js

The deckdata was dropping the `isNonDeck` trait for the token card.

server: actually fix the adaptive token-swap issue

---

server/game/cards/05-DT/GrandMelee.js
test/server/cards/05-DT/GrandMelee.spec.js

It just requires one house fulfills the condition, not that some house does not fulfill the condition.  Previously, if the creature had 2 houses (like with Badge of Unity), the logic required it to have neighbors of both houses, but the card doesn't require that.

Fix Grand Melee logic to work with Badge of Unity

---

test/server/cards/04-MM/SenatorQuintina.spec.js

this is only needed when there are multiple reap effects (e.g. for troll and citizen shrix)

remove unneeded "click card"

---

server/game/cards/03-WC/Gargantodon.js
server/game/cards/06-WoE/RogueOperation.js

Fixes #3498
- Updated rogue operation message with amount of aember being stolen
- Update gargantodon message with replacement effect
It did not seem easy to have gargantodon replace the steal message, but the double message seems like an improvement.

Fix: rogue operation and gargantodon messaging

---

server/game/GameActions/ArchiveAction.js
server/game/cards/07-GR/CurseOfDisappearances.js
test/server/cards/07-GR/CurseOfDisappearances.spec.js

It is the first card that lets you add your card to your opponent's archive on your turn.
Closes: #3815

GR: fix Curse of Disappearances archiving to owner's archive

---

server/game/cards/07-GR/ParadoxShield.js
test/server/cards/07-GR/ParadoxShield.spec.js

Because of "do as much as you can", Paradox Shield should still discard cards even if there are fewer cards left in deck than the creature's power.
Also, move it to the right directory, oops.

GR: fix Paradox Shield to discard even with not enough cards

---

server/game/GameActions/PlaceUnderAction.js
test/server/cards/07-GR/Plan10.spec.js

If we call `onLeavesPlay` first, the controller of the card will revert back to the owner, and the owner will be the one to remove it from the corresponding pile (even if the card is actually currently controlled by the opponent).  The result is that the card will remain in the original pile and also be a child card of the new parent, which causes chaos.
Closes: #3825

GR: `placeUnder` should remove from pile before `onLeavesPlay`

---

server/game/cards/07-GR/LiftingBuddy.js
test/server/cards/07-GR/LiftingBuddy.spec.js

It cannot target itself twice.

GR: Lifting Buddy's second effect is for _another_ creature

---

server/game/cards/07-GR/GrislyExchange.js

Apparently it still evaluates the true game action's target even if
the condition is false.

GR: fix Grisly Exchange for solo play

---

server/game/cards/07-GR/DontBelieveYourEyes.js
test/server/cards/07-GR/DontBelieveYourEyes.spec.js

When not haunted, the creature should just do a normal capture from the controller's opponent.
Closes: #3837

GR: fix Don't Believe Your Eyes for non-haunted case

---

server/game/cards/07-GR/CurseOfCowardice.js
test/server/cards/07-GR/CurseOfCowardice.spec.js

The clause of Curse of Cowardice that destroys itself if there are no creatures in play is part of the overall end of turn effect.  This means that the player still loses 2 amber if they didn't fight that turn, even if Curse of Cowardice is destroyed.

GR: Curse of Cowardice should only destroy self at end of turn

---

server/game/BaseActions/PlayUpgradeAction.js
server/game/GameActions.js
server/game/GameActions/PlayUpgradeOnParentAction.js
server/game/GameActions/index.js
server/game/cards/07-GR/3LLI0T.js
test/server/cards/07-GR/3LLI0T.spec.js

This card is the first card that forces a specific parent for an upgrade on
play (as opposed to re-attaching an existing upgrade).  I was able
to make this work by allowing a parent to be passed into
`PlayUpgradeAction` from a new `GameAction` but it's not my
favorite code in the world and I'm happy to change it however
anyone else suggests.

GR: implement 3LL-I0T

---

server/game/Card.js
server/game/GameActions/PlaceUnderAction.js
server/game/player.js
test/server/cards/06-WoE/ReplayPod.spec.js
test/server/cards/07-GR/Plan10.spec.js

Specifically for Replay Pod and Plan 10, cards in play should lose their upgrades, lose their child cards, and triggers any "leaves play" abilities.

Handle upgrades, child cards, and leave play events on placeUnder()

---

server/game/cards/01-Core/TheCommonCold.js
test/server/cards/01-Core/TheCommonCold.spec.js

Previously, if it didn't deal damage to any creatures, the player would not get an option to destroy Mars creatures.  So for example if all creatures were warded, the player wouldn't be able to get the second effect.

GR: The Common Cold should destroy warded Mars creatures

---

server/game/cards/07-GR/ShrinkRayTechnician.js
test/server/cards/07-GR/ShrinkRayTechnician.spec.js

Instead of applying to all enemy cards.

GR: fix scrap ability to apply to targetted card

---

server/game/cards/07-GR/LoyalPackmate.js
server/game/cards/07-GR/PsychicHaze.js
test/server/cards/07-GR/LoyalPackmate.spec.js

'self' is not a valid `targetController` value; it should be 'current' for some reason.
Closes: #3855

GR: fix Loyal Packmate and Psychic Haze target controller

---

server/game/player.js

This makes the card show facedown in the draw pile, and lets the player know what card is second in their deck.
This faceup/facedown thing for Near-Future Lens never worked anyway; the card is revealed in the chat log and that's good enough.

Near-Future Lens shouldn't make the 2nd card in draw pile facedown

---

server/game/GameActions/PutIntoPlayAction.js
server/game/TerminalCondition.js
test/server/cards/07-GR/BeOurGeist.spec.js

`treachery`/`entersPlayUnderOpponentControl` was always using the card's owner's opponent as the new controller, but that is not correct in cases like Be Our Geist or Lateral Shift, where you're playing someone else's creature as if it were in your hand.  Instead, use the active player's opponent (if they would otherwise be taking control of the put-into-played creature).
Similarly, "entersPlay" effects like `entersPlayReady`, which have a player-dependent condition (such as the tide being high, or being haunted) need to calculate their effects taking into account the active player / new controller of the card. This requires updating the game state to recalculate all the new conditions.
Closes: #3863

GR: make Be Our Geist work for treachery and enters play abilities

---

server/game/GameActions/SequentialPlayAction.js
server/game/cards/07-GR/Cauldron.js
test/server/cards/07-GR/Cauldron.spec.js

If the cards under Cauldron can't be played for a turn, it's possible to get more than 3 cards under it.  However, only three cards (of the active player's choice) can be played with one activation in a later turn.
Closes: #3878

GR: Cauldron should work for more than 3 cards under it

---

server/game/player.js

It makes it facedown in the draw pile for the controller, which is useless and harmful.

GR: don't mark any cards facedown for Near-Future Lens

---

server/game/cards/07-GR/Legerdemain.js
test/server/cards/07-GR/MissileOfficerMyers.spec.js

For some reason, the `gameAction` in Legerdemain's `then:` ability is fully evaluated when it's play effect is triggered by Missile Officer Myers's scrap ability.  When there are no creatures to target, this leads to a crash trying to resolve `preThenContext.target.controller`. This doesn't happen when it's played normally and there are no creatures to target though, so something else weird is going on but this is just a quick fix for now.

GR: fix crash when Legerdemain is discarded by Myers

---

server/game/cards/07-GR/CorporalBridger.js
server/game/costs.js
server/game/effects.js
test/server/cards/07-GR/CorporalBridger.spec.js

The existing out-of-house-use effect allowed for artifact use as well, so a new effect was needed.

GR: Corporal Bridger only allows creature use, not card use

---

server/game/cards/07-GR/AberrantWarpEvent.js
test/server/cards/07-GR/AberrantWarpEvent.spec.js

Yet another case of the action being evaluated even though the conditional already failed.

GR: fix Aberrant Warp Event when there are no cards in deck

---

server/game/BaseActions/BasePlayAction.js
server/game/cards/06-WoE/Bryozoarch.js
test/server/cards/06-WoE/Bryozoarch.spec.js

1. If an action card has a damage pip that is used to kill Bryo, that action's Play ability should still resolve.  This required: a. Re-updating the cards ability events after resolving bonus icons. b. Having Bryo trigger during a new event: `onCardPlayedAfterBonusIcons`.
2. If there are two Bryos on in a battleline, the replacement effect should only happen once.  In the code, this is done by canceling the `onCardPlayedAfterBonusIcons` event.
Closes: #3539
Closes: #3798
Closes: #3436

GR: fix some tricky situations for Bryozoarch

---

server/game/GameActions/ReturnToDeckAction.js
server/game/cards/01-Core/LostInTheWoods.js
server/game/cards/01-Core/MatingSeason.js
server/game/cards/03-WC/KymoorEclipse.js
server/game/cards/07-GR/3LLI0T.js
server/game/cards/07-GR/FutureIsPast.js
server/game/cards/07-GR/LostInTheWild.js
server/game/cards/07-GR/TillTheEarth.js
server/game/cards/07-GR/Warfaline.js

If the action targets 0 cards, and the opponent happened to have an empty discard pile, `ReturnToDeckAction` would incorrectly shuffle the opponent's deck rather than the active player's deck.
Instead, fix it to explicitly specify the player whose deck is supposed to be shuffled, if it's not the active player's deck.  Do this in all the cards that shuffle the opponent's deck.
This also fixes a few cards that are supposed to shuffle both player's decks, but wouldn't if no cards from a player were being shuffled back in.  Also fixes a bug in Mating Season that was awarding amber by control, rather than by ownership.
Closes: #3960

Fix shuffling on ReturnToDeckAction

---

server/scripts/fetchdata/CardImport.js
server/services/DeckService.js

The Grim Reaper will be fixed on the next fetchdata run.
Near-Future Lens must be fixed by updating every row in `DeckCards` where "ImageURL" is "near-future-lens-star-alliance" to "near-future-lens-staralliance" instead.
Closes: #3942

GR: fix non-anomaly images for Grim Reaper and Near-Future Lens

---

server/game/cards/08-AS/RefinedAdhesive.js
test/server/cards/08-AS/RefinedAdhesive.spec.js

Refined Adhesive should cancel discard events, making scrap events not
fire.

AS: move Refined Adhesive to right directory, and fix for scrap

---

server/game/cards/08-AS/ReapTheWildWind.js

I guess the default log message re-evaluates the randomness of the revealed cards when constructing the log message. Who knew?
Closes: #4190

AS: fix Reap the Wild Wind so it doesn't log random cards

---

server/game/GameActions/SwapDiscardWithHandAction.js
server/game/cards/08-AS/ShardOfChange.js
test/server/cards/08-AS/ShardOfChange.spec.js

If you had a card in your hand that didn't match any cards in your discard, you shouldn't be able to select it.  Before, selecting it just caused a crash.

AS: fix Shard of Change to disallow cards with no matching types

---

server/game/AbilityTargets/AbilityTargetCard.js
server/game/AbilityTargets/AbilityTargetSelect.js
server/game/CardSelectors/BaseCardSelector.js
server/game/baseability.js
server/game/cards/08-AS/Doppelganger.js
server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/gamesteps/selectcardprompt.js
server/game/optional.js
server/game/triggeredability.js
test/server/cards/08-AS/Doppelganger.spec.js

2 Doppelgangers next to each other can keep choosing each other, and keep giving each other a new copy of their text box, leading to an infinite loop that can only be broken by the choice of the player, under Keyforge's Infinite Loops clause.  So in this situation, give the user the optional to break out of the loop by making copying a neighbor optional only if one of those neighbors is also a shapeshifter.
Unfortunately, `properties.optional` is not something that could previously be evaluated dynamically, so that needed to be added.

AS: fix Doppelganger infinite loop

---

server/game/Card.js
server/game/cards/06-WoE/Befuddle.js
test/server/cards/06-WoE/Befuddle.spec.js

This fixes 2 issues with Befuddle:
1. It should prevent cards with house enhancements from being played, since they always belong to a house other than the one that was called.
2. It should _not_ prevent cards of that house from being played by an in-play card from the chosen house (for example, Sandhopper playing a card from the house that was called).  The play restriction code here is being too strict and was applying the play restriction to the source doing the playing.
Closes: #3416.

Fixes for Befuddle: house enhancements and playing cards using in-play cards

---

server/game/Card.js
server/game/effects.js
test/server/cards/02-AoA/ShadowOfDis.spec.js
test/server/cards/07-GR/FortuneReverser.spec.js

Blanking did not previously apply to keywords granted to cards, or effects granted to cards by an unblanked card.  For example, when an upgrade is attached to a blanked creature that grants it a keyword, it should not do anything.
There was a Shadow of Dis test that explicitly was testing for the opposite of what it should be doing.
It is a bit brittle to specify the difference between effects that relate to the text box of a creature, and those that do not (which would not be blanked by other effects), ubt I do my best here with an explicit list of those that should be unblankable.
Closes: #4308

Blank effects to extend to all effects related to text box

---

server/services/DeckService.js

If a card from a different house in an old set became a Redemption card in ToC, the `HouseId` for that card (either Redemption for ToC, or the old house for old decks) will be explicitly marked for newly-imported decks.  However for old decks it is still blank, but since Redemption is in the newest pack data it will default to Redemption incorrectly.
Instead, explicitly list default houses for these old cards.

Fix the default house for Redemption cards

---

server/game/cards/08-AS/BarterAndGames.js

It must somehow run this function even before the context is selected.

AS: fix Barter and Games when there's no opponent

---

server/game/cards/06-WoE/ThePromisedBlade.js
test/server/cards/06-WoE/ThePromisedBlade.spec.js

When The Promised Blade is a creature, and the players have an equal number of creatures (including The Promised Blade), it could trigger twice at the start of the round if it moved, because the condition on the second reaction became true after it moved.  Instead, make sure it only triggers once each round.
Closes: #4374

The Promised Blade should only trigger once each turn as creature

---

server/game/cards/06-WoE/MirrorShell.js
server/game/cards/06-WoE/PhalanxLeader.js
server/game/cards/07-GR/TheBodySnatchers.js
test/server/cards/07-GR/TheBodySnatchers.spec.js

This fixes a situation where The Body Snatchers can incorrectly take control of non-creatures when they are destroyed.
Closes: #3897

Lasting effects don't use `cardType`

---

server/game/Card.js
server/game/game.js
test/server/cards/04-MM/Animator.spec.js
test/server/cards/08-AS/DeAnimator.spec.js

Per the rulebook, upgrades stay attached until the card leaves play, even if a creature changes type to an artifact.
However, upgrades that cause a creature to gain an effect while attached do not affect artifacts.
Closes: #4403

Upgrades can stay attached to artifacts

---

server/game/player.js
test/server/houseenhancements.spec.js

If a card in play has a house enhancement on it that is not one of the three houses in the deck, TCO doesn't currently allow you to choose that house.  Not sure why anyone would want this but apparently it's an alliance edge case.

Allow house choice for all houses of cards in play

---

server/game/GameActions/CardGameAction.js
server/game/GameActions/MakeTokenCreatureAction.js
test/server/cards/06-WoE/FOFTransponder.spec.js
test/server/tokens.spec.js

For some actions, their targets can change as a result of another simultaneous action.  Allow that to happen specifically for making a token creature with an empty deck.  There may be other actions that need this in the future, but the general solution is too onerous (it would require ordering assault vs hazardous for every fight, even when those values are 0).

server: allow ordering a make token action even if deck is empty

---

server/game/GameActions/ChosenDiscardAction.js
server/game/GameActions/DeactivateProphecyAction.js
server/game/GameActions/DiscardCardAction.js
server/game/GameActions/DiscardTopOfDeckAction.js
server/game/GameActions/RandomDiscardAction.js
server/game/GameActions/ResolveBonusIconsAction.js
server/game/GameActions/SearchAction.js
server/game/cards/12-PV/ParallelThinking.js

Random discards shouldn't print message until target is fully set in stone.
Fixes: #4556

PV: fix Parallel Thinking log messages

---

server/game/Events/Event.js
server/game/player.js
test/server/cards/01-Core/AnnihilationRitual.spec.js
test/server/cards/05-DT/Bombyx.spec.js
test/server/cards/05-DT/KaupeEvilTwin.spec.js
test/server/cards/12-PV/GeneticStrain.spec.js

Otherwise tokens that have gone through `onLeavesPlay` will already not be tokens, and thus not be purged by Annihilation Ritual.
Closes: #4577

server: onCardPlaced events should track clone as the original card

---

server/game/GameActions/DiscardCardAction.js

If the discards are caused by a fate, then 'self' is not the active player.
Fixes: #4601

Fix discard selector -- 'self' might not be active player

---

server/game/cardaction.js
server/game/cards/06-WoE/FriendlyGuide.js
test/server/cards/03-WC/NogiSmartfist.spec.js
test/server/cards/06-WoE/FriendlyGuide.spec.js

Fixes #4421 - using copilot we found that for action abilities the cloning process was happening after the ability resolves, whereas for fight/reap its before. Moved the clone to happen first.

fix: set up clone before action resolves

---

server/game/cards/03-WC/CityStateInterest.js
server/game/cards/04-MM/AutoVac5150.js
server/game/cards/04-MM/CurseOfVanity.js
server/game/cards/04-MM/Deusillus.js
server/game/cards/04-MM/Humble.js
server/game/cards/04-MM/VaultsBlessing.js
server/game/cards/06-WoE/CovetousHema.js
server/game/cards/07-GR/MemorializeTheFallen.js
server/game/cards/07-GR/TriangulatorNewsome.js
server/game/cards/12-PV/UnityPrism.js
test/server/cards/04-MM/AutoVac5150.spec.js

Several log message updates:
- Triangulator Newsom: add total amount and creatures
```
2025-10-01 09:32:14 player1 uses Triangulator Newsome to reap with Triangulator Newsome
2025-10-01 09:32:14 player1 uses Triangulator Newsome to move all 5 amber from Triangulator Newsome's neighbors to their pool: Medic Ingram and CPO Zytar
```
- Unity Prism: add total amber and reword play
```
2025-10-01 09:35:40 player1 discards Unity Prism
2025-10-01 09:35:40 player1 uses Unity Prism to reveal their hand (Ember Imp, Ancient Bear, Poke, Draining Touch, and Batdrone) and gain 1 amber for each house represented in it, gaining a total of 3 amber
```
- Vault's Blessing: add total amber and creatures
```
2025-10-01 09:45:35 player1 plays Vault’s Blessing
2025-10-01 09:45:35 player1 gains an amber due to …
```

Log message updates 3
