- client/Components/GameBoard/Messages.jsx
- client/Components/GameBoard/PlayerStats.jsx
- client/Components/GameBoard/PlayerStats.scss
- client/Components/Games/PendingGame.scss
A few little tweaks and twiddles.
> Style tidyup

- client/Components/GameBoard/AbilityTargeting.jsx
- client/Components/GameBoard/ActivePlayerPrompt.jsx
- client/archonMaker.js
there shall be all the COLOURS
> Various CardImage fixes

- client/Components/GameBoard/CardCounters.jsx
- client/Components/GameBoard/CardImage.jsx
- client/archonMaker.js
- client/constants.js
> armor tokens -> fabric

- client/archonMaker.js
> error fixes that i swear weren't my fault

- client/Components/GameBoard/Keys.jsx
- client/Components/GameBoard/PlayerBoard.jsx
- client/Components/GameBoard/PlayerBoard.scss
- client/Components/GameBoard/PlayerRow.jsx
- client/Components/GameBoard/PlayerStats.jsx
- client/Components/GameBoard/PlayerStats.scss
- server/game/Card.js
- server/game/MenuCommands.js
move keys horizontal into PlayerStats
added names to the rows in PlayBoard
centered creatures in playerboard
simplified the ward/enrage token menu in manual mode.
> Redo do field a smidge

- server/game/player.js
- test/server/cards/04-MM/MarkOfDis.spec.js
> update house selection to make cannot overrule must

- server/game/cards/01-Core/Commpod.js
- test/server/cards/01-Core/Commpod.spec.js
> Fixes commpod allowing to select non-mars to ready

- client/Components/Decks/DeckSummary.jsx
- client/archonMaker.js
- client/constants.js
resize and filter is now done on the same canvas so memory usage should be lower
> Remove a canvas

- server/game/BaseActions/RemoveStun.js
- server/game/Card.js
- server/game/GameActions/FightGameAction.js
- server/game/GameActions/ResolveFightAction.js
- server/game/GameActions/ResolveReapAction.js
- server/game/GameActions/UseAction.js
- server/game/cardaction.js
- server/game/cards/01-Core/EvasionSigil.js
- server/game/cards/03-WC/Alaka.js
- server/game/cards/03-WC/BarnRazing.js
- server/game/cards/03-WC/PeaceAccord.js
- server/game/cards/03-WC/Ragnarok.js
- server/game/cards/04-MM/LieutenantGorvenal.js
- test/server/cards/01-Core/EvasionSigil.spec.js
- test/server/cards/02-AoA/BonerotVenom.spec.js
- test/server/cards/03-WC/Alaka.spec.js
- test/server/cards/03-WC/BarnRazing.spec.js
- test/server/cards/03-WC/Irestaff.spec.js
- test/server/cards/03-WC/PeaceAccord.spec.js
- test/server/cards/03-WC/Ragnarok.spec.js
- test/server/cards/03-WC/Shorty.spec.js
- test/server/cards/04-MM/BlastShielding.spec.js
- test/server/cards/04-MM/LegionsMarch.spec.js
- test/server/cards/04-MM/LieutenantGorvenal.spec.js
A somewhat hacky approach to fixing onUseCard events and Containment Field  / Bonerot issues
Fixes #268
Fixes #398
Fixes #560
Fixes #1148
Fixes #1338
Fixes #1473
Fixes #1481
Fixes #1647
Fixes #1815 
Fixes #1936
Fixes #1953
Fixes #1996
Fixes #2062
> Fixes onUseCard events

- server/game/cards/04-MM/ForumOfGiants.js
- test/server/cards/04-MM/ForumOfGiants.spec.js
Fixes #2000
(there is a drawback here, which is it is now always prompting)
> Fixes Forum of Giants not prompting for most powerful creature when there is a tie

- test/server/cards/03-WC/Overrun.spec.js
It does not fix #1603 and does fix #1149 directly but it shows they are not failing anymore.
They might have been fixed by https://github.com/keyteki/keyteki/pull/1465.
> Added more test cases for Overrun

- server/game/cards/01-Core/Mimicry.js
- test/server/cards/01-Core/Mimicry.spec.js
> Fix Mimicry and Alpha

- server/game/cards/03-WC/Overrun.js
> Reset both players counters on main Phase for Overrun

- server/game/Events/Event.js
- server/game/GameActions/ResolveFightAction.js
- server/game/GameActions/ResolveReapAction.js
- server/game/cards/02-AoA/LittleNiff.js
- server/game/cards/03-WC/BarnRazing.js
- server/game/cards/03-WC/Molephin.js
- server/game/cards/03-WC/PeaceAccord.js
- server/game/cards/04-MM/LieutenantGorvenal.js
- test/server/cards/01-Core/ArmageddonCloak.spec.js
- test/server/cards/02-AoA/LittleNiff.spec.js
Fixes #2024 
Contains one condition not thought in onUseCard
Remove a clone in checkCondition of event, as it should not be needed <-- might need attention here?!
> Fixes Little Niff to be reaction. Pass attackerClone to onUseCard for fight

- server/game/GameActions/ModifyAmberAction.js
- server/game/GameActions/ResolveReapAction.js
- server/game/cards/02-AoA/SirMarrows.js
- test/server/cards/02-AoA/PoSPixies.spec.js
- test/server/cards/02-AoA/SirMarrows.spec.js
> Fixes Sir Marrows double capture and Po's Pixies interaction

- server/game/GameActions.js
- server/game/GameActions/DrawAction.js
- server/game/GameActions/PlayCardAction.js
- server/game/GameActions/RandomDiscardAction.js
- server/game/GameActions/RandomPlayCardAction.js
- server/game/GameActions/RandomPurgeAction.js
- server/game/GameActions/index.js
- server/game/cards/01-Core/WildWormhole.js
- server/game/cards/02-AoA/Murkens.js
- server/game/cards/03-WC/Fidgit.js
- server/game/cards/03-WC/WormholeTechnician.js
- server/game/cards/04-MM/BotBookton.js
- test/server/cards/01-Core/WildWormhole.spec.js
- test/server/cards/02-AoA/Exhume.spec.js
- test/server/cards/02-AoA/Murkens.spec.js
- test/server/cards/03-WC/Fidgit.spec.js
- test/server/cards/03-WC/WormholeTechnician.spec.js
- test/server/cards/04-MM/BotBookton.spec.js
Fixes #216 
Fixes #434
Fixes #1601 
Fixes #1610
Fixes #2070 
Fixes #2104
Sentry: 
Fixes KEYTEKI-1CA
Fixes #KEYTEKI-1CA
Fixes [KEYTEKI-1CA]
> Handling reveal at PlayCardACtion instead of Cards

- server/game/GameActions/DealDamageAction.js
- test/server/cards/01-Core/DumaTheMartyr.spec.js
> Fix Duma The Martyr when damage is protected by armor

- server/game/BaseActions/BasePlayAction.js
- server/game/cards/01-Core/Mimicry.js
- server/game/costs.js
- server/game/game.js
- server/game/gamesteps/phase.js
- test/server/cards/04-MM/NovuDynamo.spec.js
> Fix Novu Dynamo and alpha

- server/game/cards/04-MM/Deusillus.js
Fixes #1423
```
2020-12-04 15:25:00 player1 plays Deusillus
2020-12-04 15:25:00 player1 uses Deusillus to capture all amber and deal 5 damage to Narp
2020-12-04 15:25:00 player1 uses Deusillus to make Deusillus fight Zorg
2020-12-04 15:25:00 player1 uses Deusillus to remove 1 amber from Deusillus and deal 2 damage to all enemy creatures
```
> Improved Deusillus message

- server/game/GameActions/DestroyAction.js
> battlelineindex should consider artifacts for the purpose of putintoplay

- server/game/cards/02-AoA/Earthbind.js
- test/server/cards/02-AoA/Earthbind.spec.js
> Fix Earthbind ruling

- server/game/player.js
> Unforge message bug

- server/game/Card.js
- server/game/GameActions/ReapGameAction.js
- test/server/cards/03-WC/Ghosthawk.spec.js
> Ghosthawk cannot reap with enraged creatures, but can remove stun

- server/game/cards/02-AoA/Neffru.js
- test/server/cards/01-Core/Tolas.spec.js
> Test cases for Neffru/Tolas and Board Wipe

- server/game/Card.js
- server/game/GameActions/FightGameAction.js
- server/game/cards/01-Core/OneStoodAgainstMany.js
- test/server/cards/01-Core/ArmageddonCloak.spec.js
- test/server/cards/01-Core/OneStoodAgainstMany.spec.js
> Fixes for OSAM

- server/game/GameActions/ResolveFightAction.js
- server/game/cards/01-Core/EvasionSigil.js
- test/server/cards/01-Core/EvasionSigil.spec.js
> Fixes 2 Evasion Sigil and Hazardous/Assault interaction

- test/server/cards/02-AoA/DirectorOfZyx.spec.js
Unable to reproduce 787, but adding test cases
Fixes #787
> Adding test cases for Director of Z.Y.X

- server/game/cards/01-Core/KeyHammer.js
- server/game/player.js
- test/server/cards/01-Core/KeyHammer.spec.js
- test/server/cards/01-Core/TendrilsOfPain.spec.js
> Fixes key unforged this turn not counting for Tendrils of Pain

- server/game/CardVisibility.js
- server/game/cards/03-WC/Memolith.js
- test/server/cards/03-WC/Memolith.spec.js
> Grafted cards should be visible and Memolith should allow selecting not-controlled cards

- server/game/cards/01-Core/Tolas.js
> Fix Tolas message to match Neffru

- server/game/GameActions/DiscardCardAction.js
> Fixes discarded cards not counted for alpha check

- server/game/cards/04-MM/Resurgence.js
- test/server/cards/04-MM/Resurgence.spec.js
> Fixes Resurgence message

- server/game/Card.js
- test/server/cards/01-Core/YxilxDominator.spec.js
- test/server/cards/01-Core/Zorg.spec.js
> Fix Enter Play Stunned vs Take Control (Zorg or Yxilx Dominator vs. Hypnobeam)

- server/game/cards/01-Core/CollarOfSubordination.js
- server/game/effects.js
- test/server/cards/03-WC/LateralShift.spec.js
> Fixed takeControl to be a flexible effect

- server/game/GameActions/LastingEffectAction.js
- server/game/cards/03-WC/Ragnarok.js
- server/game/effects.js
- test/server/cards/03-WC/Ragnarok.spec.js
> Fixes Ragnarok happening "after" end of turn event

- server/game/cards/04-MM/NovuDynamo.js
- test/server/cards/04-MM/NovuDynamo.spec.js
> Fixes Novu Dynamo message

- server/game/cards/03-WC/FinchCloak.js
- test/server/cards/03-WC/FinchCloak.spec.js
> Fixes Finch Cloak message

- server/game/baseability.js
- server/game/costs.js
- test/server/cards/01-Core/CustomsOffice.spec.js
- test/server/cards/01-Core/EtherSpider.spec.js
> Fix for two Custom Offices and message to pay amber

- server/game/player.js
Attempt to help find a root cause for Senator Bracchus bug in the future( fix #889 )
> add game message to say how much amber used from a creature

- server/game/cards/04-MM/Fandangle.js
- test/server/cards/04-MM/Fandangle.spec.js
> fixes maverick fandangle entering ready

- server/game/player.js
- test/server/cards/01-Core/AnnihilationRitual.spec.js
> Fixes Annihilation Ritual and gigantic creature

- server/game/cards/04-MM/Amberheart.js
> Fixes Amberheart message

- client/Components/GameBoard/CardNameLookup.jsx
- client/Components/GameBoard/TypeaheadLookup.jsx
- server/game/ThenAbility.js
- server/game/cards/03-WC/HarvestTime.js
- test/server/cards/03-WC/HarvestTime.spec.js
It fixes a few things:
- Prompt closing when no selection
- preThenEvents not properly set in case of no events and alwaysTriggers: true
- Fixes it looking for controller instead of owner
Fixes #1919
Fixes #2064
Fixes #2200
> Fixes Harvest Time prompt

- server/game/cards/01-Core/VezymaThinkdrone.js
- server/game/cards/03-WC/Stunner.js
- test/server/cards/01-Core/VezymaThinkdrone.spec.js
- test/server/cards/03-WC/Stunner.spec.js
- test/server/cards/04-MM/Deusillus.spec.js
Standardize the optional prompt of these two cards.
Fixes #2089
> Remove 'may' from Vezyme and Stunner

- server/game/Card.js
- server/game/GameActions/ReapGameAction.js
- test/server/cards/03-WC/Ghosthawk.spec.js
> Rollback Enraged vs. Ghosthawk

- server/game/cards/01-Core/TirelessCrocag.js
- server/game/cards/03-WC/CincinnatusRex.js
- server/game/cards/04-MM/DoomSigil.js
- server/game/cards/04-MM/Shadowsaurus.js
- server/game/game.js
- test/server/cards/01-Core/TirelessCrocag.spec.js
- test/server/cards/03-WC/Weasand.spec.js
- test/server/cards/04-MM/Shadowsaurus.spec.js
> Fixes Terminal Condition and take control

- server/game/cards/04-MM/BlastFromThePast.js
> Fixes Blast From the Past power in message

- server/game/cards/05-DT/AbyssalZealot.js
- server/game/cards/05-DT/AmberfinShark.js
- server/game/cards/05-DT/BinaryMoray.js
- server/game/cards/05-DT/CaptainNoBeard.js
- server/game/cards/05-DT/CaptainNoBeardEvilTwin.js
- server/game/cards/05-DT/DryTheRiver.js
- server/game/cards/05-DT/LarieOfTheLake.js
- server/game/cards/05-DT/LarieOfTheLakeEvilTwin.js
- server/game/cards/05-DT/PiSwevenEvilTwin.js
- server/game/cards/05-DT/RocketeerTryskaEvilTwin.js
- server/game/cards/05-DT/SeabringerKekoa.js
- server/game/cards/05-DT/SleepWithTheFishes.js
- server/game/cards/05-DT/Taniwha.js
- server/game/cards/05-DT/TaniwhaEvilTwin.js
- server/game/cards/05-DT/TomwaOfTheGlowEvilTwin.js
- test/server/cards/05-DT/AbyssalZealot.spec.js
- test/server/cards/05-DT/AmberfinShark.spec.js
- test/server/cards/05-DT/BinaryMoray.spec.js
- test/server/cards/05-DT/CaptainNoBeard.spec.js
- test/server/cards/05-DT/CaptainNoBeardEvilTwin.spec.js
- test/server/cards/05-DT/DryTheRiver.spec.js
- test/server/cards/05-DT/LarieOfTheLake.spec.js
- test/server/cards/05-DT/LarieOfTheLakeEvilTwin.spec.js
- test/server/cards/05-DT/PISwevenEvilTwin.spec.js
- test/server/cards/05-DT/RocketeerTryskaEvilTwin.spec.js
- test/server/cards/05-DT/SeabringerKekoa.spec.js
- test/server/cards/05-DT/SleepWithTheFishes.spec.js
- test/server/cards/05-DT/Taniwha.spec.js
- test/server/cards/05-DT/TaniwhaEvilTwin.spec.js
- test/server/cards/05-DT/TomwaOfTheGlowEvilTwin.spec.js
> DT: Set of auto generated cards

- server/game/cards/03-WC/Keyforgery.js
- test/server/cards/03-WC/Keyforgery.spec.js
Fixes #2222
Fixes #1296 (using SkyJedi test cases)
> Fixes two keyforgery plus its errata

- server/game/cards/04-MM/BringLow.js
> Bring Low : check for opponent

- server/game/GameActions/ResolveFightAction.js
- server/game/cards/01-Core/BrainEater.js
- server/game/cards/01-Core/Tolas.js
- server/game/cards/02-AoA/Neffru.js
- server/game/cards/03-WC/Hapsis.js
- test/server/cards/01-Core/BrainEater.spec.js
- test/server/cards/01-Core/Tolas.spec.js
- test/server/cards/02-AoA/Neffru.spec.js
- test/server/cards/03-WC/Hapsis.spec.js
- test/server/cards/03-WC/Ragnarok.spec.js
Fixes Tolas timing to happen before after fight
Fixes Hapsis not checking for fight events and warding due to assault
Fixes #2232
Fixes #2233
> Fixes After a Creature is Destroyed effect timing

- server/game/GameActions/PlaceUnderAction.js
- server/game/GameActions/SequentialPutIntoPlayAction.js
- server/game/cards/01-Core/SpanglerBox.js
- server/game/cards/04-MM/Amberlution.js
- test/server/cards/01-Core/SpanglerBox.spec.js
- test/server/cards/04-MM/Amberlution.spec.js
- test/server/cards/04-MM/Deusillus.spec.js
Fixed my first submitted issue in August 2019 :)
Using SequentialPutIntoPlayAction in SpanglerBox.
Simplified it to avoid prompting to select the last creature (affects Amberlution.js)
Fixes #300
> Allow Spangler Box to select the order of placement

- server/game/cards/05-DT/OlPaddy.js
- server/game/cards/05-DT/OlPaddyEvilTwin.js
- test/server/cards/05-DT/OlPaddy.spec.js
- test/server/cards/05-DT/OlPaddyEvilTwin.spec.js
> DT: Ol' Paddy twins

- server/game/GameActions/AllocateDamageAction.js
- test/server/cards/02-AoA/ShardOfPain.spec.js
> Check for valid targets before starting allocate damage prompt

- client/Components/Form/ConfirmButton.jsx
Fixes #1445
I appreciate this might tread on the toes of New World(tm) - so feel free to bin this PR if so. That aside, I decided to finally _learn_ some React (rather than just keep staring it in the hope of guessing how it works). 
Is this a completely cack-handed way to tackle this?
> Toggle button text during confirm action (Delete/Cancel)

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/GameActions/SequentialAction.js
- server/game/cards/05-DT/5c077.js
- server/game/cards/05-DT/AmberVac.js
- server/game/cards/05-DT/SabotageMission.js
- server/game/cards/05-DT/_5c077.js
- test/server/cards/05-DT/5c077.spec.js
- test/server/cards/05-DT/AmberVac.spec.js
- test/server/cards/05-DT/SabotageMission.spec.js
> DT: Star Alliance cards

- server/game/GameActions/ArchiveAction.js
> Consider purged an open area and reveal name of archived card to fix Universal Recycle Bin

- server/game/GameActions/SearchAction.js
- test/server/cards/01-Core/BearFlute.spec.js
> Reset cardName in SearchAction to fix BearFlute

- server/game/player.js
- test/server/cards/04-MM/Deusillus.spec.js
> Gigantic cards not setting controller of composedPart

- server/game/cards/04-MM/LookWhatIFound.js
> Fixes "Look what I found!" messaging issue

- server/game/cards/05-DT/AgentSepdia.js
- server/game/cards/05-DT/CensorPhiloEvilTwin.js
- server/game/cards/05-DT/Ostracize.js
- server/game/cards/05-DT/Pestergrove.js
- server/game/cards/05-DT/Thundertow.js
- test/server/cards/05-DT/AgentSepdia.spec.js
- test/server/cards/05-DT/CensorPhilo.spec.js
- test/server/cards/05-DT/CensorPhiloEvilTwin.spec.js
- test/server/cards/05-DT/Ostracize.spec.js
- test/server/cards/05-DT/Pestergrove.spec.js
- test/server/cards/05-DT/Thundertow.spec.js
> DT: Ostracize, Pestergrove, Thundertow and 2more

- server/game/cards/05-DT/WitchOfTheDawn.js
- test/server/cards/05-DT/WitchOfTheDawn.spec.js
Created witch of the dawn with test, based on witch of the eye.
> implemented Witch of the Dawn

- server/game/GameActions/RemoveTokenAction.js
- server/game/cards/05-DT/Ambermancy.js
- test/server/cards/05-DT/Ambermancy.spec.js
To create this card, I also updated RemoveTokenAction, adding support for "upTo". Copied this code from the HealAction class.
> implemented Ambermancy (with tests), anding upTo support to RemoveTokenAction

- server/scripts/createteststub.js
This is a simple test stub creator script that I've been using to create stubs for new cards to use it:
node server/scripts/createteststub --name 'Witch Of The Dawn Evil Twin'
> created test stub script

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/05-DT/Butterfly.js
- server/game/cards/05-DT/Cocoon.js
- server/game/cards/05-DT/Larva.js
- test/server/cards/05-DT/Butterfly.spec.js
- test/server/cards/05-DT/Cocoon.spec.js
- test/server/cards/05-DT/Larva.spec.js
Note these creatures required references to cards by name that currently are not final. I added //TODO next to the names - like "Cocoon?".
Looks like this won't auto-merge - but I think that is because of the string locale changes.
> implemented Butterfly, Cocoon, and Larva with tests

- server/game/cards/05-DT/WayOfTheFairy.js
- test/server/cards/05-DT/WayOfTheFairy.spec.js
I noticed Way Of The Fairy was autogenerated, but was not yet pulled in. I brought it in, and added a test.
> implemented way of the fairy

- server/game/cards/01-Core/TheSting.js
- server/game/cards/05-DT/Mookling.js
- server/game/cards/05-DT/MooklingEvilTwin.js
- server/game/effects.js
- server/game/player.js
- test/server/cards/05-DT/Mookling.spec.js
- test/server/cards/05-DT/MooklingEvilTwin.spec.js
In this PR, I did the following:
1) Added onAmberSpentOnForge event (and improved the messaging)
2) updated The Sting to use this new event
3) Created Mookling and Mookling Evil Twin cards with tests
> created onAmberSpentOnForge event, and implemented Mookling

- server/game/cards/03-WC/ObsidianForge.js
- test/server/cards/03-WC/ObsidianForge.spec.js
Fixes #1842
Supersedes PR #1861
> Obsidian Forge bug fix when no creature is selected

- server/game/Card.js
- test/server/cards/04-MM/SaurianEgg.spec.js
> Should be able to Remove stun offhouse if creature has Omni ability

- server/game/cards/05-DT/EarlyBirds.js
- server/game/cards/05-DT/FreebooterFaye.js
- server/game/cards/05-DT/FreebooterFayeEvilTwin.js
- server/game/cards/05-DT/OneEyedWillaEvilTwin.js
- server/game/cards/05-DT/TheFlyinSpecter.js
- server/game/cards/05-DT/TrickleDownTheory.js
- test/server/cards/05-DT/EarlyBirds.spec.js
- test/server/cards/05-DT/FreebooterFaye.spec.js
- test/server/cards/05-DT/FreebooterFayeEvilTwin.spec.js
- test/server/cards/05-DT/OneEyedWillaEvilTwin.spec.js
- test/server/cards/05-DT/TheFlyinSpecter.spec.js
- test/server/cards/05-DT/TrickleDownTheory.spec.js
> DT: EarlyBirds, FreebooterFaye/ET, OneEyedWillaEvilTwin, TheFlyinSpecter, TrickleDownTheory

- server/game/cards/05-DT/AusteralisSeaborg.js
- server/game/cards/05-DT/BackupPlan.js
- server/game/cards/05-DT/Chronophage.js
- server/game/cards/05-DT/HonorsKeysis.js
- server/game/cards/05-DT/Portalmonger.js
- server/game/cards/05-DT/RecklessExperiment.js
- server/game/cards/05-DT/TalmageSteelheart.js
- server/game/cards/05-DT/TalmageSteelheartEvilTwin.js
- test/server/cards/05-DT/AusteralisSeaborg.spec.js
- test/server/cards/05-DT/BackupPlan.spec.js
- test/server/cards/05-DT/Chronophage.spec.js
- test/server/cards/05-DT/HonorsKeysis.spec.js
- test/server/cards/05-DT/Portalmonger.spec.js
- test/server/cards/05-DT/RecklessExperiment.spec.js
- test/server/cards/05-DT/TalmageSteelheart.spec.js
- test/server/cards/05-DT/TalmageSteelheartEvilTwin.spec.js
> Some logos cards

- server/game/cards/05-DT/Corrode.js
- server/game/cards/05-DT/CupOfWater.js
- server/game/cards/05-DT/DeepDive.js
- server/game/cards/05-DT/DeepPriestGlebe.js
- server/game/cards/05-DT/WikoliaEvilTwin.js
- test/server/cards/05-DT/Corrode.spec.js
- test/server/cards/05-DT/CupofWater.spec.js
- test/server/cards/05-DT/DeepDive.spec.js
- test/server/cards/05-DT/DeepPriestGlebe.spec.js
- test/server/cards/05-DT/WikoliaEvilTwin.spec.js
I did this, well Roro did most of it, but I committed it.  but really Roro did it
> DT: DeepDive, WikoliaEvilTwin, Corrode, CupOfWater, DeepPriestGlebe

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/AbilityTargets/AbilityTargetSelect.js
- server/game/Card.js
- server/game/cards/05-DT/HandCannon.js
- server/game/cards/05-DT/MontyBank.js
- server/game/cards/05-DT/MontyBankEvilTwin.js
- server/game/cards/05-DT/Ransom.js
- server/game/cards/05-DT/StirTrouble.js
- server/game/cards/05-DT/WalkThePlank.js
- test/server/cards/05-DT/HandCannon.spec.js
- test/server/cards/05-DT/LapisaurusEvilTwin.spec.js
- test/server/cards/05-DT/MontyBank.spec.js
- test/server/cards/05-DT/MontyBankEvilTwin.spec.js
- test/server/cards/05-DT/Ransom.spec.js
- test/server/cards/05-DT/StirTrouble.spec.js
- test/server/cards/05-DT/WalkThePlank.spec.js
> DT: Hand Cannon, Monty Bank/ET, Ransom, Stir Trouble, Walk the Plank

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/constants.js
- server/game/cards/05-DT/GrandAllianceCouncil.js
- test/server/cards/05-DT/GrandAllianceCouncil.spec.js
In this implementation I wanted to put the house name in the title, but I did not see away to do this without creating a localized string which included all of the house names. For now I have left it out.
> implemented Grand Alliance Council and tests, and added missing house to constants.js file

- server/game/cards/05-DT/Together.js
- test/server/cards/05-DT/Together.spec.js
https://archonarcana.com/Spoilers?cardnumber=287&order_by=Number
Related issue:
> implemented Together with tests

- server/game/BaseActions/BasePlayAction.js
- server/game/BaseActions/PlayCreatureAction.js
- server/game/GameActions/PlayCardAction.js
- server/game/GameActions/PutIntoPlayAction.js
- server/game/cards/05-DT/LightEverlasting.js
- test/server/cards/03-WC/MimicGel.spec.js
- test/server/cards/05-DT/LightEverlasting.spec.js
> DT: Light Everlasting

- server/game/GameActions/UnforgeAction.js
- server/game/cards/01-Core/KeyHammer.js
- server/game/cards/04-MM/BreakKey.js
- server/game/cards/04-MM/Skixuno.js
- server/game/cards/04-MM/Turnkey.js
- server/game/cards/05-DT/Card403.js
- server/game/cards/05-DT/CrushingCharge.js
- server/game/cards/05-DT/FinalAnalysis.js
- server/game/cards/05-DT/GroundbreakingDiscovery.js
- server/game/cards/05-DT/SLRSAusteralis.js
- server/game/player.js
- test/server/cards/05-DT/Card403.spec.js
- test/server/cards/05-DT/CrushingCharge.spec.js
- test/server/cards/05-DT/FinalAnalysis.spec.js
- test/server/cards/05-DT/GroundbreakingDiscovery.spec.js
- test/server/cards/05-DT/SLRSAusteralis.spec.js
> DT: Final Analysis, Groundbreaking Discovery, SLRS Austeralis, Card403, Crushing Charge

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/05-DT/Decadence.js
- server/game/cards/05-DT/Engulf.js
- test/server/cards/05-DT/Decadence.spec.js
- test/server/cards/05-DT/Engulf.spec.js
- test/server/cards/05-DT/SinkOrSwim.spec.js
> DT: Engulf, Decadence

- server/game/cards/05-DT/Lapisaurus.js
- test/server/cards/05-DT/Lapisaurus.spec.js
https://archonarcana.com/Spoilers?cardnumber=176&order_by=Number
Related issue:
> implemented Lapisaurus and tests

- server/game/cards/05-DT/Ch337aEvilTwin.js
- test/server/cards/05-DT/CH337AEvilTwin.spec.js
https://archonarcana.com/Spoilers?cardnumber=245
Related issue:
> CH-337A (Evil Twin) implemented with tests

- server/game/cards/05-DT/BiomeDiscovery.js
- test/server/cards/05-DT/BiomeDiscovery.spec.js
https://archonarcana.com/Spoilers?cardnumber=291&order_by=Number
Related issue:
Note, the impl is more complex than it should be because I could not get promptWithHandlerMenu to work when it is was nested in ability.actions.conditional.
> Biome Discovery impl

- server/game/cards/05-DT/ExplorationVessel.js
- test/server/cards/05-DT/ExplorationVessel.spec.js
https://archonarcana.com/Spoilers?cardnumber=265&order_by=Number
Related issue:
> implemented Exploration Vessel with tests

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/05-DT/SelectivePreservation.js
- test/server/cards/05-DT/SelectivePreservation.spec.js
https://archonarcana.com/Spoilers?cardnumber=283&order_by=Number
For this issue:
Note, looks like auto merge is having a conflict with localized strings.
> Implemented Selective Preservation with tests

- server/game/cards/05-DT/Dog.js
- test/server/cards/05-DT/Dog.spec.js
https://archonarcana.com/Spoilers?cardnumber=102&order_by=Number
Related Issue:
Note, the name on the spoilers page makes this creature look like it has a name "Holdfast" ?
> Dog dt card

- server/game/cards/05-DT/Card327.js
- test/server/cards/05-DT/Card327.spec.js
https://archonarcana.com/Spoilers?cardnumber=327&order_by=Number
Related Issue:
Note, this was created using the card auto-generator. Nice.
> implemented card 327

- server/game/cards/05-DT/LightsmithClarielEvilTwin.js
- test/server/cards/05-DT/LightsmithClarielEvilTwin.spec.js
https://archonarcana.com/Spoilers?cardnumber=067&order_by=Number
Related Issue:
> implemented Lightsmith Clariel Evil Twin with tests

- server/game/AbilityTargets/AbilityTargetCardName.js
- server/game/cards/05-DT/DarkDiscovery.js
- test/server/cards/05-DT/DarkDiscovery.spec.js
https://archonarcana.com/Spoilers?cardnumber=315&order_by=Number
Related Issue:
Note, to make this card work I needed to update AbilityTargetCardName.js  so that it would record the selected card in the context.targets object.
> implemented Dark Discovery and tests

- server/game/GameActions/MoveToBottomAction.js
- server/game/cards/05-DT/DrawnByTheDepths.js
- test/server/cards/05-DT/DrawnByTheDepths.spec.js
https://archonarcana.com/Spoilers?cardnumber=313&order_by=Number
Related Issue:
Note, to make this card, I updated MoveToBottomAction so that you can choose to impact the opponent's deck.
> implement Drawn By The Depths and test

- server/game/player.js
- test/server/cards/03-WC/SenatorBracchus.spec.js
Queue  forge key prompt sequentially, instead of all at once
Fixes #2206
> Fixes Bracchus and bypassing amber prompt

- server/game/GameActions/ArchiveAction.js
- server/game/cards/01-Core/IncubationChamber.js
- test/server/cards/01-Core/IncubationChamber.spec.js
> Fixes Incubation Chamber log message

- server/game/cards/03-WC/Ghosthawk.js
- test/server/cards/02-AoA/BonerotVenom.spec.js
- test/server/cards/03-WC/Ghosthawk.spec.js
> Ghosthawk should be optional

- server/game/GameActions/RandomPurgeAction.js
- test/server/cards/03-WC/Impspector.spec.js
> Fixes Impspector message when no cards are purged

- server/game/cards/02-AoA/Earthbind.js
- test/server/cards/04-MM/NovuDynamo.spec.js
> Fixes Novu Dynamo and Earthbind

- server/game/cards/05-DT/AllTideUp.js
- server/game/cards/05-DT/PourTal.js
- server/services/DeckService.js
> Fixes Evil Twin

- client/Components/GameBoard/Card.scss
- server/scripts/fetchdata/KeyForgeHalfSizeBuild.js
Evil twin half hint
fixed the bad corners on halfpints
> Et halfpints

- server/game/cards/05-DT/Ch337aEvilTwin.js
- server/game/cards/05-DT/SabotageMission.js
- server/game/cards/05-DT/SelectivePreservation.js
- server/game/cards/05-DT/T3r35a.js
- server/game/cards/05-DT/TheUlfberhtDevice.js
- server/game/cards/05-DT/Together.js
- test/server/cards/05-DT/TheUlfberhtDevice.spec.js
- test/server/cards/05-DT/Together.spec.js
> Fixes The Ulfberht Device blocking both players

- server/game/cards/05-DT/HarmonicRitual.js
I hope the build does not loop forever
> Fixes HarmonicRitual endless loop

- server/game/Card.js
- server/game/cards/05-DT/HarmonicRitual.js
- server/game/cards/05-DT/OfficersBlaster.js
- test/server/cards/05-DT/OfficersBlaster.spec.js
card.leftNeighbor()
.cardrightNeighbor()
probably backwards, who knows
> Get neighbors

- server/game/cards/05-DT/TrojanSauropod.js
- test/server/cards/05-DT/TrojanSauropod.spec.js
> Fix Trojan Sauropod not being destroyed

- server/game/cards/05-DT/Kaupe.js
- test/server/cards/05-DT/Together.spec.js
> Fixes Kaupe and Together (or any card that allow immediate play)

- server/game/cards/03-WC/Valoocanth.js
- server/game/cards/05-DT/LieutenantValmart.js
- server/game/cards/05-DT/Omnipus.js
- test/server/cards/03-WC/Valoocanth.spec.js
fixes #2423
fixes #2428
fixes #2431
> card fixes

- server/game/cards/02-AoA/AbondTheArmorsmith.js
- server/game/cards/05-DT/DarkDiscovery.js
- server/game/cards/05-DT/KiriGiltspine.js
- server/game/cards/05-DT/Pestergrove.js
- server/game/cards/05-DT/RooftopLaboratory.js
- server/game/cards/05-DT/TheChosenOne.js
- server/game/cards/05-DT/WitchOfTheDawn.js
- test/server/cards/05-DT/DarkDiscovery.spec.js
- test/server/cards/05-DT/RooftopLaboratory.spec.js
- test/server/cards/05-DT/TheChosenOne.spec.js
- test/server/cards/05-DT/WitchOfTheDawn.spec.js
Fixes #2417
Fixes #2418
Fixes #2419 
Fixes #2422 
Fixes #2424
> Fixes TCO, Rooftop, Dark Discovery, Pestergrave and Witch of Dawn

- server/game/cards/05-DT/T3r35a.js
- server/game/cards/05-DT/Wikolia.js
- test/server/cards/05-DT/T3r35a.spec.js
Using this (like Tireless Crocag)
It will fail with Mimic-gel
I will look into fixing it later
Tracked in https://github.com/keyteki/keyteki/issues/2253
> Fixes T3R-35A and Wikolia

- server/game/cards/05-DT/Omnipus.js
> DT: Omnipus fix

- server/game/GameActions/SequentialAction.js
- server/game/cards/05-DT/Badgemagus.js
- server/game/cards/05-DT/Sparkfist.js
- server/game/cards/05-DT/YoungestBearEvilTwin.js
- test/helpers/playerinteractionwrapper.js
- test/server/cards/05-DT/Badgemagus.spec.js
> Fixes YoungestBearEvilTwin not being optional and Badgemagus not readying

- server/game/cards/05-DT/CallOfTheVoid.js
- server/game/cards/05-DT/CrushingCharge.js
- server/game/cards/05-DT/DarkDiscovery.js
- server/game/cards/05-DT/StirUpTrouble.js
- test/server/cards/05-DT/StirUpTrouble.spec.js
Enhance CrushingCharge message
Enhance Dark Discovery message
> Fixes Stir Up Trouble and Shoulder Id

- client/archonMaker.js
- server/game/Card.js
- server/game/cards/03-WC/PrimusUnguis.js
> Fixes Primus Ungius and power/armor rendering

- server/game/cards/03-WC/SongOfTheWild.js
- server/game/cards/03-WC/UnitedAction.js
- test/server/cards/03-WC/SongOfTheWild.spec.js
- test/server/cards/03-WC/UnitedAction.spec.js
Fixes #1125
Filex #2500
Fixes #891
> Song of the Wild and United Action should consider new creatures / houses

- server/game/cards/05-DT/TheMysticeti.js
- test/server/cards/05-DT/TheMysticeti.spec.js
> Fixes The Mysticeti exhausting any creature, not only untamed

- server/game/cards/05-DT/HastatusRaptor.js
- server/game/cards/05-DT/Hornswoggle.js
- server/game/cards/05-DT/PrimalRelic.js
- server/game/cards/05-DT/SGSIlluminator.js
- server/game/cards/05-DT/TheUlfberhtDevice.js
- server/game/cards/05-DT/WashedAway.js
- server/game/effects.js
- test/server/cards/05-DT/HastatusRaptor.spec.js
- test/server/cards/05-DT/PrimalRelic.spec.js
- test/server/cards/05-DT/TheUlfberhtDevice.spec.js
- Hastatus Raptor does not work when one of them does not have amber
- The Ulfberht Device is now constant and not persisting effect
- Primal Relic should be exactly 3 (using string instead of number)
- SGS Illuminator should be exactly
- Washed away effect message
- Comments cleanup
> Fixes a few cards

- server/game/cards/04-MM/MonumentToPrimus.js
- server/scripts/updatecardtext.js
- test/server/cards/04-MM/MonumentToPrimus.spec.js
Fixes #2518
Add a script to update the card text (comment inline)
> Fixes MonumentToPrimus when only 1 friendly creature is in play

- client/Components/GameBoard/PlayerStats.jsx
- server/game/cards/05-DT/5c077.js
- server/game/cards/05-DT/5c077EvilTwin.js
- test/server/cards/05-DT/5c077.spec.js
- test/server/cards/05-DT/5c077EvilTwin.spec.js
Fixes 5c077 and ET using Cancel and prompt button
Fixes undefined Tide icon without opponent
> Enhance 5c077 message for better debugging

- server/game/cards/03-WC/GamblingDen.js
- server/game/game.js
- test/server/cards/03-WC/GamblingDen.spec.js
> Fixes GamblingDen message

- server/game/Card.js
- server/game/cards/05-DT/DiplomatAgung.js
- test/server/cards/05-DT/DiplomatAgung.spec.js
- test/server/cards/cancreatecards.spec.js
> Fixes Diplomat Agung and Academy Training

- client/Components/Decks/ImportDeck.jsx
- server/services/DeckService.js
TCO will auto assign enhancements when its simple to do so.
> Feature: easy enhancements

- server/services/DeckService.js
added addition auto enhance where 1 enhanced card gets all the enhancements
fix for not counting all the enhancements correct for auto enhance
> More Auto-Enhancements

- server/game/cards/05-DT/TheChosenOne.js
- server/game/gamesteps/ReadyPhase.js
- test/server/cards/05-DT/TheChosenOne.spec.js
> The Chosen One should not ready creatures after it is destroyed during ready phase

- server/game/cards/05-DT/Holdfast.js
- test/server/cards/05-DT/Holdfast.spec.js
Fixes #2534
Kept the current functionality without consideration of armor/ward
> Fixes Holdfast and Shoulder Id

- server/game/GameActions/SequentialPutIntoPlayAction.js
- server/game/cards/01-Core/SpanglerBox.js
- server/game/cards/04-MM/Amberlution.js
- server/game/cards/05-DT/DrawnDown.js
- server/game/cards/05-DT/GeneralSherman.js
- server/game/cards/05-DT/TrojanSauropod.js
> Fixes Drawn Down message and General Sherman revealing hand

- server/game/cards/05-DT/StormSurge.js
- test/server/cards/05-DT/StormSurge.spec.js
> Fixes Storm Gurge

- server/game/Effects/DynamicEffect.js
- server/game/Effects/StaticEffect.js
- server/game/cards/01-Core/EtherSpider.js
- server/game/effects.js
- test/server/cards/03-WC/MimicGel.spec.js
> Fixes Mimic Gel and Ether Spider

- client/archonMaker.js
> Archon's back for impossible decks

- server/game/GameActions/DiscardTopOfDeckAction.js
- server/game/cards/03-WC/FinchCloak.js
- server/game/cards/03-WC/Harmonia.js
- server/game/cards/04-MM/Ant110ny.js
- server/game/cards/04-MM/SpoilsOfBattle.js
- server/game/chatcommands.js
Fixes #2401
Fixes KEYTEKI-18V https://sentry.io/organizations/throneteki/issues/1703523215/?project=1515148
Fixes KEYTEKI-19Y https://sentry.io/organizations/throneteki/issues/1726489212/?project=1515148
Fixes KEYTEKI-1NQ https://sentry.io/organizations/throneteki/issues/1804707117/?project=1515148
Fixes KEYTEKI-2TY https://sentry.io/organizations/throneteki/issues/2126465331/?project=1515148
Fixes KEYTEKI-1AQ https://sentry.io/organizations/throneteki/issues/1742527926/?project=1515148
> Fixes discardtopofdeck chat command and a few sentry issues

- server/game/cards/02-AoA/CybergiantRig.js
- server/game/cards/04-MM/ZWaveEmitter.js
- server/game/cards/05-DT/AmberVac.js
- server/game/cards/05-DT/Ransom.js
- server/game/cards/05-DT/StaticCharge.js
- test/server/cards/02-AoA/CybergiantRig.spec.js
- test/server/cards/04-MM/ZWaveEmitter.spec.js
- test/server/cards/05-DT/AmberVac.spec.js
> Fixes AmberVac on opponent's creature

- server/game/game.js
- server/gamenode/gameserver.js
- server/lobby.js
Now spectators forwarded to next game and can join after
> Fix watch-rematch

- server/game/cards/05-DT/SubmersivePrinciple.js
> Message issue for Submersive Principle

- client/pages/HowToPlay.jsx
- server/game/chatcommands.js
- server/game/game.js
- server/game/gamesteps/setup/setupphase.js
Manual command to change first player (for triad matches for example)
> Add manual command to change first player

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/GameActions/PlayCardAction.js
- server/game/cards/05-DT/AnkyloFormation.js
- server/game/cards/05-DT/TrojanSauropod.js
- test/server/cards/04-MM/BotBookton.spec.js
- test/server/cards/05-DT/AnkyloFormation.spec.js
Fixes #2578
Fixes #2543
Attempt a fix for #2575 (unable to reproduce though)
> Fixes Trojan Sauropod message, Ankylo Formation and adjusted PlayCardAction to try fixing BotBookton

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/Card.js
- server/game/player.js
> Fixes Give Control menu command

- server/game/cards/03-WC/PowerOfFire.js
- server/game/cards/03-WC/SelfBolsteringAutomata.js
- test/server/cards/02-AoA/ShadowOfDis.spec.js
- test/server/cards/03-WC/PowerOfFire.spec.js
> Fixes Power of Fire on a Self-Bolstering Automata

- server/services/DeckService.js
> Fixes images for maverick anomalies on their real set

- server/game/cards/04-MM/Humble.js
> Fixes humble message. 

- client/Components/Decks/DeckSummary.jsx
- client/Components/Decks/DeckSummary.scss
> Enhancements on Deck Summary page

- server/game/GameActions/LastingEffectAction.js
- test/server/cards/04-MM/EtansJar.spec.js
> Fixes Ethan's Jar lasting for 1 round only

- server/services/DeckService.js
> Anomaly card fixes

- server/game/cards/01-Core/Mimicry.js
- test/server/cards/05-DT/RakuzelsChant.spec.js
> Fixes Mimicry copying only 1 play ability

- docker-compose.yml
- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/05-DT/BiomeDiscovery.js
- server/game/cards/05-DT/Bombyx.js
- server/game/cards/05-DT/Fifalde.js
- test/server/cards/05-DT/BiomeDiscovery.spec.js
> Fixes BiomeDiscovery  not being optional

- server/game/cards/01-Core/CrazyKillingMachine.js
- test/server/cards/01-Core/CrazyKillingMachine.spec.js
> Refactor Crazy Killing Machine to destroy simultaneously

- client/Application.jsx
- server/game/gamesteps/house/HousePhase.js
- test/server/cards/04-MM/TheArchivist.spec.js
> Fixes Alert Message and Archivist Prompt

- server/game/cards/01-Core/SpecialDelivery.js
- server/game/cards/01-Core/YxiloBolter.js
- test/server/cards/01-Core/SpecialDelivery.spec.js
- test/server/cards/01-Core/YxiloBolter.spec.js
> Fixes Rad Penny being purged by Special Delivery

- server/game/cards/03-WC/ImperialRoad.js
- test/server/cards/03-WC/ImperialRoad.spec.js
> Fixes Bestiarii Urso and Imperial Road interaction

- server/game/cards/01-Core/BearFlute.js
- test/server/cards/01-Core/BearFlute.spec.js
> Automate Bear Flute to avoid manually clicking on the ancient bears

- server/game/BaseActions/PlayCreatureAction.js
- server/game/GameActions/PutIntoPlayAction.js
- server/game/cards/03-WC/Dexus.js
- server/game/cards/03-WC/Sinestra.js
- test/server/cards/03-WC/CodeMonkey.spec.js
- test/server/cards/03-WC/Dexus.spec.js
- test/server/cards/03-WC/Sinestra.spec.js
> Fixes Code Monkey and Dexus / Sinestra interaction

- client/i18n.js
> setting cookieSecure: true and making localStorage preferable over cookie for i18n language preference

- server/game/cards/01-Core/SpanglerBox.js
- server/game/cards/05-DT/GeneralSherman.js
- test/server/cards/05-DT/GeneralSherman.spec.js
Fixes General Sherman and Spangler Box applying a lasting triggering effect to opponent
Fixes #2648
> Fixes General Sherman and Spangler Box applying a lasting triggering effect to opponent

- server/game/cards/03-WC/SensorChiefGarcia.js
> Fixes SCG key cost

- server/game/cards/05-DT/ForgiveOrForget.js
- test/server/cards/cancreatecards.spec.js
> Fixes Forgive or Forget message

- server/game/cards/01-Core/MackTheKnife.js
- server/game/cards/02-AoA/ScowlyCaper.js
- server/game/cards/03-WC/AutoLegionary.js
- test/server/cards/03-WC/AutoLegionary.spec.js
Fixes #2387
Fixes #2273
Fixes #1530
Also fixes Mack the Knife and Scowly Caper using this
> Fixes Auto-Legionary using a player effect as a lasting effect

- server/game/cards/01-Core/CustomVirus.js
- server/game/cards/01-Core/IncubationChamber.js
- test/server/cards/01-Core/CustomVirus.spec.js
- test/server/cards/01-Core/IncubationChamber.spec.js
> Custom Virus and Incubation Chamber are now optional

- server/game/game.js
> Fixes spectator joined message being displayed twice

- server/game/player.js
- test/server/cards/02-AoA/Hypnobeam.spec.js
> Fixes Mimic Gel house not showing on House Phase

- server/game/BaseActions/BasePlayAction.js
- server/game/BaseActions/PlayAction.js
- server/game/BaseActions/PlayArtifactAction.js
- server/game/BaseActions/PlayCreatureAction.js
- server/game/BaseActions/PlayUpgradeAction.js
- server/game/gamesteps/main/actionwindow.js
- test/server/cards/02-AoA/Duskwitch.spec.js
- test/server/cards/05-DT/Chronophage.spec.js
- test/server/cards/05-DT/OlPaddy.spec.js
> Omega refactor to consider gained effects

- server/game/GameActions/ResolveAbilityAction.js
- test/server/cards/03-WC/SciOfficerMorpheus.spec.js
> Fixes ResolveAbilityAction to check for condition earlier

- test/server/cards/03-WC/Weasand.spec.js
> Test to prove Weasand and Collar is working

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/game.js
- server/game/gamesteps/HouseTieBreakPrompt.js
- server/game/gamesteps/setup/FirstPlayerSelection.js
- server/game/player.js
- test/server/wincondition.spec.js
I think this basically cover 90% of going to time cases :)
Working on the house selection tie break
Fixes #2663
> Implement keys and amber rules when going to time

- server/game/cards/04-MM/Purify.js
> Fixes Purify not listing discarded cards

- server/game/game.js
- server/gamenode/gameserver.js
> Fixes spectator message

- server/game/Card.js
- server/game/cards/04-MM/CyberClone.js
- server/game/game.js
- test/server/cards/04-MM/Animator.spec.js
- test/server/cards/04-MM/CyberClone.spec.js
- test/server/cards/04-MM/ThePaleStar.spec.js
Fixes #2091
Fixes #2627
Fixes #2385
> Fixes Cyber-Clone and upgrade on Animator

- client/Components/GameBoard/Messages.jsx
- client/Components/Games/NewGame.jsx
- client/Components/Site/AlertPanel.jsx
- server/game/CardAbility.js
- server/game/ThenAbility.js
- server/game/cards/01-Core/Fogbank.js
- server/game/cards/01-Core/Foggify.js
- server/game/cards/01-Core/Lifeward.js
- server/game/cards/01-Core/ScramblerStorm.js
- server/game/cards/02-AoA/HideawayHole.js
- server/game/cards/02-AoA/SeismoEntangler.js
- server/game/cards/02-AoA/ShadowOfDis.js
- server/game/cards/03-WC/DiploMacy.js
- server/game/cards/03-WC/InkyGloom.js
- server/game/cards/03-WC/IntoTheNight.js
- server/game/cards/03-WC/SowSalt.js
- server/game/cards/03-WC/StealthMode.js
- server/game/cards/04-MM/LuckyDice.js
- server/game/cards/04-MM/OppositionResearch.js
- server/game/cards/05-DT/AllusionsOfGrandeur.js
- server/game/cards/05-DT/StormSurge.js
- server/game/cards/05-DT/TrialByWater.js
Fixes #2562
Fixes #2425
Fixes #1744
> Add an effectAlert to show a background and a bell

- server/game/GameActions/LastingEffectAction.js
- server/game/gamesteps/setup/setupphase.js
- test/server/cards/02-AoA/Replicator.spec.js
> Fixes Replicator and Quant (and opponent's creature with target)

- server/game/cards/04-MM/ZWaveEmitter.js
- server/game/cards/05-DT/AmberVac.js
- server/game/cards/05-DT/Ransom.js
- server/game/cards/05-DT/StaticCharge.js
> Fixes onBeginRound and gained ability to use reaction

- server/game/cards/01-Core/GormOfOmm.js
- test/server/cards/01-Core/GormOfOmm.spec.js
> Gorm of Omm should sacrifice itself before prompt for another artifact

- server/game/GameActions/RandomDiscardAction.js
- server/game/cards/04-MM/Mindfire.js
- test/server/cards/04-MM/Mindfire.spec.js
> Mindfire changed to show steal message

- server/game/cards/03-WC/ShatteredThrone.js
- test/server/cards/03-WC/ShatteredThrone.spec.js
> Fixes ShatteredThrone and Assault

- server/services/DeckService.js
> Fixes sorting Decks by name

- client/Components/GameBoard/CardPileLink.jsx
- client/Components/GameBoard/CardPileLink.scss
> Changed fond size of new card pile links

- client/Components/GameBoard/CardNameLookup.jsx
- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/AbilityTargets/AbilityTargetCardName.js
- server/game/cards/05-DT/DarkDiscovery.js
Clean the Card name after selection
Add two prompt titles for Dark Discovery
Fixes #2746
> Fixes for Name a Card prompt

- client/Components/GameBoard/GameBoard.jsx
- client/Components/GameBoard/TimeLimitClock.jsx
- client/Components/GameBoard/TimeLimitClock.scss
Possibly fixes #2761
Totally open to this not being merged if it's hated. Was something I'd toyed with in the past.
> Change position and style of game timer

- server/game/cards/01-Core/FuzzyGruen.js
- server/game/cards/02-AoA/PlagueRat.js
- server/game/cards/03-WC/Infurnace.js
- server/game/cards/05-DT/Malstrom.js
- server/game/cards/05-DT/Scooped.js
- test/server/cards/01-Core/FuzzyGruen.spec.js
Fixes #2723
Fixes #2727 
Fixes #2728 
Fixes #2729
Fixes #2736
> Fixes Fuzzy Gruen, Plague Rat, Infurnace, Maelstrom and Scooped's messages

- client/Components/GameBoard/MovablePanel.jsx
> fixes the cardpile popup so touch scrolling works

- server/game/gamesteps/forcedtriggeredabilitywindow.js
- server/game/gamesteps/triggeredabilitywindowtitles.js
- test/server/cards/01-Core/SoulSnatcher.spec.js
- test/server/gamesteps/forcedtriggeredabilitywindow.spec.js
It will reduce a lot the prompts for fights :)
Fixes #2722
> Fixes incorrect events being displayed in simultaneous prompt

- server/game/GameActions/FightGameAction.js
- server/game/GameActions/ReapGameAction.js
- test/server/cards/01-Core/Anger.spec.js
- test/server/cards/01-Core/Inspiration.spec.js
- test/server/cards/03-WC/Ghosthawk.spec.js
- test/server/cards/05-DT/ReapOrSow.spec.js
> Fixes unstun when using effects from other cards

- server/game/cards/05-DT/TheMysticeti.js
- test/server/cards/03-WC/AutoLegionary.spec.js
- test/server/cards/05-DT/TheMysticeti.spec.js
> Fixes Mysticeti used by opponent

- server/game/cards/01-Core/TheSting.js
- test/server/cards/01-Core/TheSting.spec.js
> Fixes double 'The Sting' taken amber twice

- server/game/cards/05-DT/MontyBank.js
Closes #2789
Couldn't find any Card spec that tested the message printed. But if anyone can point me towards one, I can write a test for this fix too.
> Fix monty bank exalt message

- client/archonMaker.js
> i make derp

- server/game/GameActions/AttachAction.js
- server/game/cards/01-Core/Lifeweb.js
- test/server/cards/01-Core/Lifeweb.spec.js
> Disregard creatures played as upgrade for Lifeweb

- server/game/cards/02-AoA/EntropicSwirl.js
- test/server/cards/02-AoA/EntropicSwirl.spec.js
> Fixes mimic gel and cyber clone versus entropic swirl

- server/game/gamesteps/forcedtriggeredabilitywindow.js
- test/server/cards/02-AoA/ContainmentField.spec.js
- test/server/cards/03-WC/ShatteredThrone.spec.js
- test/server/cards/04-MM/BlastShielding.spec.js
- test/server/cards/04-MM/LegionsMarch.spec.js
> Fixes onUseCard on upgrades versus simultaneous reap / fight abilities

- server/game/cards/04-MM/MonumentToShrix.js
> Improve MonumentToShrix's message

- server/game/cards/02-AoA/TyxlBeambuckler.js
- test/server/cards/02-AoA/TyxlBeambuckler.spec.js
> Fixes Tyxl Beambuckler targeting a creature next to Shadow Self

- server/game/cards/03-WC/Timequake.js
- test/server/cards/03-WC/Timequake.spec.js
> Timequake should consider friendly upgrades on enemy creatures

- server/game/cards/01-Core/VeylanAnalyst.js
- test/server/cards/01-Core/VeylanAnalyst.spec.js
> Fixes Veylan Analyst not considering only use of artifacts

- server/game/cards/05-DT/RuinsOfArchonis.js
- test/server/cards/05-DT/RuinsOfArchonis.spec.js
> Fix Ruins of the Archonis triggering at 6 cards and allowing simultaneous actions

- server/game/cards/05-DT/Lapisaurus.js
- test/server/cards/05-DT/Lapisaurus.spec.js
> Lapisaurus should be a fight interrupt only, instead of a lasting effect

- server/game/GameActions/DealDamageAction.js
- test/server/cards/05-DT/Undagnathus.spec.js
> Fixes DealDamageAction considering amountForCard instead of amount = 0 (!check)

- server/game/Card.js
- server/game/cards/03-WC/QuixxleStone.js
- test/server/cards/04-MM/BotBookton.spec.js
Fixes #2575
Fixes #2891
The fix is based on Lifeward implementation
> Fixes Bot Bookton vs. Quixxle Stone interaction

- server/game/cards/03-WC/TheColosseum.js
- server/game/cards/04-MM/LookOverThere.js
- test/server/cards/01-Core/SpecialDelivery.spec.js
- test/server/cards/03-WC/TheColosseum.spec.js
- test/server/cards/04-MM/LookOverThere.spec.js
> Fixes some interactions with Armageddon Cloak

- server/game/cards/04-MM/ReclaimedbyNature.js
- test/server/cards/04-MM/ReclaimedByNature.spec.js
> Fixes Reclaimed by Nature being simultaneous.

- server/game/GameActions/PutIntoPlayAction.js
- test/server/cards/02-AoA/ScowlyCaper.spec.js
> Fixes effects not being applied when creatures put in play under opponent control after being purged by Spangler Box or General Sherman

- server/game/Effects/StaticEffect.js
- server/game/Effects/Values/CanUse.js
- server/game/Effects/Values/CannotRestriction.js
- server/game/Effects/Values/ConditionValue.js
- server/game/Effects/Values/EffectValue.js
- server/game/GameActions/PutIntoPlayAction.js
- server/game/GameObject.js
- server/game/costs.js
- test/server/cards/01-Core/PhaseShift.spec.js
- test/server/cards/03-WC/MimicGel.spec.js
Refactor how EffectContext is passed to Condition effect values.
Fixes #2793
Fixes #2805
> Refactor how EffectContext is passed to Condition effect values.

- server/game/cards/04-MM/FissionBloom.js
- server/game/cards/04-MM/WildBounty.js
- test/server/cards/04-MM/FissionBloom.spec.js
- test/server/cards/04-MM/MasterOfTheGrey.spec.js
- test/server/cards/04-MM/WildBounty.spec.js
> Fixes wild bounty and fission bloom lasting effect

- server/game/GameActions/ResolveFightAction.js
- test/server/keywords.spec.js
> Elusive should be turned off if attacking creature is destroyed by opponent's hazardous

- server/game/cards/01-Core/EpicQuest.js
- test/server/cards/01-Core/VeylanAnalyst.spec.js
It was overridden when we merged DT
Fixes #2920
> Reapplied the fix to Epic Quest

- server/game/GameActions/CaptureAction.js
- server/game/GameActions/ExaltAction.js
- server/game/cards/06-WoE/Kretchee.js
- server/game/effects.js
- test/server/cards/06-WoE/Kretchee.spec.js
Added new effects for capturing and exalting one extra amber.
Seems like this might be a good one to have an extra log message for, but I haven't figured out how to do that yet.  Any tips would be appreciated!
> WoE: implement Kretchee

- server/game/cards/06-WoE/AntiquitiesDealer.js
- test/server/cards/06-WoE/AntiquitiesDealer.spec.js
> Antiques Dealer after merge

- server/game/cards/06-WoE/Outflank.js
- test/server/cards/06-WoE/Outflank.spec.js
> WoE: Outflank

- server/game/cards/06-WoE/Sandhopper.js
- test/server/cards/06-WoE/Sandhopper.spec.js
> WoE: implement Sandhopper

- server/game/cards/06-WoE/PuzzlingTrinket.js
- test/server/cards/06-WoE/PuzzlingTrinket.spec.js
> WoE: implement Puzzling Trinket

- server/game/cards/06-WoE/IkwikiOutpost.js
- test/server/cards/06-WoE/IkwikiOutpost.spec.js
Depends on https://github.com/keyteki/keyteki-json-data/pull/58
> WoE: implement Ikwiki Outpost

- server/game/cards/06-WoE/TradeSecrets.js
- test/server/cards/06-WoE/TradeSecrets.spec.js
> WoE: implement Trade Secrets

- server/game/cards/06-WoE/TradingFrenzy.js
- test/server/cards/06-WoE/TradingFrenzy.spec.js
> WoE: implement Trading Frenzy

- server/game/cards/06-WoE/AuctionOff.js
- test/server/cards/06-WoE/AuctionOff.spec.js
> WoE: implement Auction Off

- server/game/cards/06-WoE/MassBuyout.js
- test/server/cards/06-WoE/MassBuyout.spec.js
> WoE: implement Mass Buyout

- server/game/cards/06-WoE/BelligerentGuard.js
- test/server/cards/06-WoE/BelligerentGuard.spec.js
> WoE: implement Belligerent Guard

- server/game/cards/06-WoE/ClosedDoorNegotiation.js
- test/server/cards/06-WoE/ClosedDoorNegotiation.spec.js
> WoE: implement Closed-Door Negotiation

- server/game/GameActions.js
- server/game/GameActions/SwapDiscardWithHandAction.js
- server/game/GameActions/index.js
- server/game/cards/06-WoE/Scrapscrounger.js
- test/server/cards/06-WoE/Scrapscrounger.spec.js
> WoE: implement Scrapscrounger

- server/game/cards/06-WoE/GreenAeronaut.js
- server/game/cards/06-WoE/Nautilixian.js
- server/game/cards/06-WoE/PurpleAeronaut.js
- server/game/cards/06-WoE/RedAeronaut.js
- server/game/cards/06-WoE/WhiteAeronaut.js
- test/server/cards/06-WoE/GreenAeronaut.spec.js
- test/server/cards/06-WoE/Nautilixian.spec.js
- test/server/cards/06-WoE/PurpleAeronaut.spec.js
- test/server/cards/06-WoE/RedAeronaut.js
- test/server/cards/06-WoE/WhiteAeronaut.spec.js
> WoE: implement the power rangers

- .devcontainer/devcontainer.json
I also added a .devcontainer to use it on Github containers
> Merge from master

- server/game/cards/06-WoE/REvolution.js
- test/server/cards/06-WoE/REvolution.spec.js
> WoE: implement R-Evolution

- server/game/cards/06-WoE/NifflePaw.js
Suggested by romanogit.
Issue: #2984
> WoE: fix Niffle Paw message

- server/game/cards/06-WoE/ShrewdInvestor.js
- test/server/cards/06-WoE/ShrewdInvestor.spec.js
> WoE: implement Shrewd Investor

- server/game/GameActions/ReadyAction.js
- server/game/cards/05-DT/StormSurge.js
- server/game/cards/06-WoE/FrostGiant.js
- test/server/cards/06-WoE/FrostGiant.spec.js
It looks like the `readyDuringReadyPhase` wasn't actually used anywhere, so I took my best guess about how to hook it up.  Very open to changing this to something better!
> WoE: hook up `readiesDuringReadyPhase` and implement Frost Giant

- server/game/cards/06-WoE/PandulfTheProvoker.js
- test/server/cards/06-WoE/PandulfTheProvoker.spec.js
> WoE: Implement Pandulf the Provoker

- server/game/cards/06-WoE/ReplayPod.js
- test/server/cards/06-WoE/ReplayPod.spec.js
> WoE: implement Replay Pod

- server/game/cards/06-WoE/Retribution.js
- test/server/cards/06-WoE/Retribution.spec.js
> WoE: Implement Retribution

- server/game/cards/06-WoE/SuspendedAnimation.js
- test/server/cards/06-WoE/SuspendedAnimation.spec.js
> WoE: implement Suspended Animation

- server/game/cards/06-WoE/ReveredMonk.js
- test/server/cards/06-WoE/ReveredMonk.spec.js
> WoE: Implement Revered Monk

- server/game/cards/06-WoE/Zizok.js
- test/server/cards/06-WoE/Zizok.spec.js
> WoE: implement Zizok

- server/game/GameActions.js
- server/game/cards/06-WoE/RevoHooligans.js
- test/server/cards/06-WoE/RevoHooligans.spec.js
> WoE: implement Revo Hooligans

- server/game/cards/06-WoE/GeneticBlast.js
- test/server/cards/06-WoE/GeneticBlast.spec.js
> WoE: implement Genetic Blast

- server/game/cards/06-WoE/ScoopUp.js
- test/server/cards/06-WoE/ScoopUp.spec.js
> WoE: implement Scoop Up

- server/game/cards/06-WoE/MyxTheTallminded.js
- test/server/cards/06-WoE/MyxTheTallminded.spec.js
> WoE: implement Myx the Tallminded

- test/server/cards/06-WoE/MyxTheTallminded.spec.js
Implemented this before I saw you merged the other one. Works fine, might as well have it too!
> WoE: add Myx test with hypnobeam

- server/game/cards/06-WoE/BorkaRikk.js
- test/server/cards/06-WoE/BorkaRikk.spec.js
> WoE: implement Borka Rikk

- server/game/cards/06-WoE/MartianRevolution.js
- test/server/cards/06-WoE/MartianRevolution.spec.js
> WoE: implement Martian Revolution

- server/game/cards/06-WoE/NyyonOutpost.js
- test/server/cards/06-WoE/NyyonOutpost.spec.js
> WoE: implement Nyyon Outpost

- server/game/cards/06-WoE/CloneHome.js
- test/server/cards/06-WoE/CloneHome.spec.js
> WoE: implement Clone Home

- server/game/cards/06-WoE/Researcher.js
- test/server/cards/06-WoE/Researcher.spec.js
> WoE: implement Researcher

- server/game/cards/06-WoE/Absolve.js
- test/server/cards/06-WoE/Absolve.spec.js
> WoE: Implement Absolve

- server/game/cards/06-WoE/Disciple.js
- test/server/cards/06-WoE/Disciple.spec.js
> WoE: Implement Disciple

- server/game/cards/06-WoE/FeatsOfStrength.js
- test/server/cards/06-WoE/FeatsOfStrength.spec.js
> WoE: implement Feats of Strength

- server/game/cards/06-WoE/Stratosmack.js
- test/server/cards/06-WoE/Stratosmack.spec.js
> WoE: implement Stratosmack

- server/game/cards/06-WoE/PressGang.js
- test/server/cards/06-WoE/CloneHome.spec.js
- test/server/cards/06-WoE/PressGang.spec.js
Also fix up the Clone Home tests.
Issue: #2901
Fixes #3050
> WoE: implement Press Gang

- server/game/cards/06-WoE/TheGrandGord.js
- test/server/cards/06-WoE/TheGrandGord.spec.js
> WoE: implement The Grand Gord

- server/game/cards/06-WoE/ExoShellSystem.js
- test/server/cards/06-WoE/ExoShellSystem.spec.js
> WoE: implement Exo-shell System

- server/game/cards/06-WoE/MarketCrash.js
- test/server/cards/06-WoE/MarketCrash.spec.js
> WoE: implement Market Crash

- server/game/cards/06-WoE/DthoshraRecruiter.js
- test/server/cards/06-WoE/DthoshraRecruiter.spec.js
> WoE: implement Dthoshra, Recruiter

- server/game/cards/06-WoE/Diplomat.js
- test/server/cards/06-WoE/Diplomat.spec.js
> WoE: implement Diplomat

- server/game/cards/06-WoE/RequestDonations.js
- test/server/cards/06-WoE/RequestDonations.spec.js
> WoE: Implement Request Donations

- server/game/cards/06-WoE/TheVisibleHand.js
- test/server/cards/06-WoE/TheVisibleHand.spec.js
> WoE: implement The Visible Hand

- server/game/cards/04-MM/Commune.js
- server/game/cards/06-WoE/TokenOfAppreciation.js
- test/server/cards/06-WoE/TokenOfAppreciation.spec.js
And fix Commune's message (`sequential` seems to override `effectMsg`).
Issue: #2902
> WoE: implement Token of Appreciation

- server/game/cards/06-WoE/AedileTullia.js
- test/server/cards/06-WoE/AedileTullia.spec.js
> WoE: implement Aedile Tullia

- server/game/cards/06-WoE/HireOn.js
- server/game/cards/06-WoE/PressGang.js
- test/server/cards/06-WoE/HireOn.spec.js
And fix up the chat messages for the other versions of this card.
Issue: #2902
> WoE: implement Hire On

- server/game/cards/06-WoE/JarlSvend.js
- test/server/cards/06-WoE/JarlSvend.spec.js
> WoE: implement Jarl Svend

- server/game/cards/06-WoE/TyaArhiEsquire.js
- test/server/cards/06-WoE/TyaArhiEsquire.spec.js
> WoE: implement Tya-Arhi Esquire

- server/game/GameActions.js
- server/game/cards/06-WoE/Election.js
- test/server/cards/06-WoE/Election.spec.js
> WoE: implement Election

- server/game/GameActions.js
- server/game/GameActions/MakeTokenCreatureAction.js
- server/game/cards/06-WoE/SpaceInvaders.js
- test/server/cards/06-WoE/SpaceInvaders.spec.js
> WoE: implement Space Invaders

- server/game/cards/06-WoE/Conscription.js
- server/game/cards/06-WoE/Election.js
- test/server/cards/06-WoE/Conscription.spec.js
> WoE: implement Conscription

- server/game/cards/06-WoE/GeneralZaOrha.js
- test/server/cards/06-WoE/GeneralZaOrha.spec.js
> WoE: implement General Za Orha

- server/game/cards/06-WoE/EdictOfNerotaurus.js
- test/server/cards/06-WoE/EdictOfNerotaurus.spec.js
> WoE: implement Edict of Nerotaurus

- server/game/cards/06-WoE/Muster.js
- test/server/cards/06-WoE/Muster.spec.js
> WoE: Implement Muster

- server/game/cards/06-WoE/InspiringOration.js
- test/server/cards/06-WoE/InspiringOration.spec.js
> WoE: implement Inspiring Oration

- server/game/cards/06-WoE/MembershipDrive.js
- test/server/cards/06-WoE/MembershipDrive.spec.js
> WoE: Implement Membership Drive

- server/game/cards/06-WoE/LegionaryTrainer.js
- test/server/cards/06-WoE/LegionaryTrainer.spec.js
https://github.com/keyteki/keyteki/issues/2905
Changes:
* new card Legionary Trainer
* new test case for card Legionary Trainer
* Lint passed
> add legionary trainer

- server/game/cards/06-WoE/PaleIntoInsignificance.js
- test/server/cards/06-WoE/PaleIntoInsignificance.spec.js
https://github.com/keyteki/keyteki/issues/2905
Changes:
* new card Pale Into Insignificance 
* new test case for card Pale Into Insignificance 
* Lint passed
> added PaleIntoInsignificance card

- server/game/cards/06-WoE/EpicPoem.js
- test/server/cards/06-WoE/EpicPoem.spec.js
https://github.com/keyteki/keyteki/issues/2905
Changes:
* new card Epic Poem
* new test case for card Epic Poem
* added new test case with no creatures in play
* Lint passed
> add epic poem

- server/game/cards/06-WoE/PressGang.js
- server/game/cards/06-WoE/Recruit.js
- test/server/cards/06-WoE/PressGang.spec.js
- test/server/cards/06-WoE/Recruit.spec.js
Also fix and test a Press Gang issue that I noticed.
Issue: #2905
> WoE: implement Recruit

- server/game/cards/06-WoE/Symposium.js
- test/server/cards/06-WoE/Symposium.spec.js
> WoE: implement Symposium

- server/game/cards/06-WoE/PraetorMarius.js
- test/server/cards/06-WoE/PraetorMarius.spec.js
https://github.com/keyteki/keyteki/issues/2905
Changes:
* new card Praetor Marius
* new test case for card Praetor Marius
* Lint passed
> added Praetor Marius

- server/game/cards/06-WoE/Explorer.js
- test/server/cards/06-WoE/Explorer.spec.js
https://github.com/keyteki/keyteki/issues/2906
Changes:
* new card Explorer (largely copied from Scout Pete)
* new test case for card Explorer (largely copied from Scout Pete)
* Lint passed
> add explorer

- server/game/cards/06-WoE/SpecialistGuthrak.js
- test/server/cards/06-WoE/SpecialistGuthrak.spec.js
https://github.com/keyteki/keyteki/issues/2906
Changes:
* new card Specialist Guthrak
* new test case for card Specialist Guthrak
* Lint passed
> add Specialist Guthrak

- server/game/cards/06-WoE/ChancellorDexterus.js
- test/server/cards/06-WoE/ChancellorDexterus.spec.js
> WoE: implement Chancellor Dexterus

- server/game/cards/06-WoE/GreyAbess.js
- test/server/cards/06-WoE/GreyAbess.spec.js
> WoE: Implement Grey Abess

- server/game/cards/06-WoE/HoplitesDory.js
- test/server/cards/06-WoE/HoplitesDory.spec.js
> WoE: implement Hoplite's Dory

- server/game/cards/06-WoE/Cleric.js
- test/server/cards/06-WoE/Cleric.spec.js
> WoE: Implement Cleric

- server/game/cards/06-WoE/Chaosodon.js
- test/server/cards/06-WoE/Chaosodon.spec.js
> WoE: implement Chaosodon

- server/game/cards/06-WoE/ImperatorDrusilla.js
- test/server/cards/06-WoE/ImperatorDrusilla.spec.js
> WoE: implement Imperator Drusilla

- server/game/GameActions.js
- server/game/cards/06-WoE/Aristotlmimus.js
- server/game/cards/06-WoE/Platopelta.js
- server/game/cards/06-WoE/Socraterosaurus.js
- test/server/cards/06-WoE/Aristotlmimus.spec.js
- test/server/cards/06-WoE/Platopelta.spec.js
- test/server/cards/06-WoE/Socraterosaurus.spec.js
- test/server/cards/cancreatecards.spec.js
> WoE: implement the philosopher dinos

- server/game/cards/06-WoE/RecruitingStation.js
- test/server/cards/06-WoE/RecruitingStation.spec.js
> WoE: implement Recruiting Station

- server/game/cards/06-WoE/KaterinaTheSummoner.js
- test/server/cards/06-WoE/KaterinaTheSummoner.spec.js
> WoE: Implement Katerina the Summoner

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/06-WoE/TectonicShift.js
- test/server/cards/06-WoE/TectonicShift.spec.js
> WoE: implement Tectonic Shift

- server/game/cards/06-WoE/Camaraderie.js
- test/server/cards/06-WoE/Camaraderie.spec.js
> WoE: implement Camaraderie

- server/game/cards/06-WoE/StrongerTogether.js
- test/server/cards/06-WoE/StrongerTogether.spec.js
> WoE: implement Stronger Together

- server/game/cards/06-WoE/ShakedownSullivan.js
- test/server/cards/06-WoE/ShakedownSullivan.spec.js
> WoE: implement Shakedown Sullivan

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/06-WoE/GezrahiBlacksmith.js
- test/server/cards/06-WoE/GezrahiBlacksmith.spec.js
> WoE: implement Gezrahi Blacksmith

- server/game/cards/06-WoE/RogueOperation.js
- test/server/cards/06-WoE/RogueOperation.spec.js
Note, this is my first card using preThenEvents so take a close look please. 
https://github.com/keyteki/keyteki/issues/2906
Changes:
* new card Rogue Operation
* new test case for card Rogue Operation
* Lint passed
> add Rogue Operation

- server/game/cards/06-WoE/Amberling.js
- server/game/cards/06-WoE/NorbynsCavern.js
- server/game/effects.js
- server/game/player.js
- test/server/cards/06-WoE/Amberling.spec.js
- test/server/cards/06-WoE/NorbynsCavern.spec.js
> WoE: implement Amberling and Norbyn's Cavern

- server/game/cards/06-WoE/Grondal.js
- test/server/cards/06-WoE/Grondal.spec.js
> WoE: implement Grondal

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/06-WoE/ShizyokuBuggy.js
- test/server/cards/06-WoE/ShizyokuBuggy.spec.js
> WoE: implement Shizyoku Buggy

- server/game/cards/06-WoE/GruntWork.js
- test/server/cards/06-WoE/GruntWork.spec.js
> WoE: implement Grunt Work

- server/game/cards/06-WoE/GanymedeOutpost.js
- test/server/cards/06-WoE/GanymedeOutpost.spec.js
> WoE: implement Ganymede Outpost

- server/game/cards/06-WoE/Raider.js
- test/server/cards/06-WoE/Raider.spec.js
https://github.com/keyteki/keyteki/issues/2907
Changes:
* added code for Raider
* added test cases for Raider
* Test cases passed
* Lint passed
Note, I'm surprised that the onCardEntersPlay effect is does not impact other cards when played. But I added a test to confirm this case.
> add Raider

- server/game/cards/06-WoE/LongusaurLector.js
- test/server/cards/06-WoE/LongusaurLector.spec.js
> WoE: implement Longusaur Lector

- server/game/cards/06-WoE/PhotonBlast.js
- test/server/cards/06-WoE/PhotonBlast.spec.js
> WoE: implement Photon Blast

- server/game/cards/06-WoE/GiltspineSchool.js
- test/server/cards/06-WoE/GiltspineSchool.spec.js
> WoE: finish Giltspine School

- server/game/cards/06-WoE/RenewedLife.js
- test/server/cards/06-WoE/RenewedLife.spec.js
> Woe: Implement Renewed Life

- server/game/cards/06-WoE/QuintrinoWarp.js
- test/server/cards/06-WoE/QuintrinoWarp.spec.js
> WoE: add Quintrino Warp

- server/game/cards/06-WoE/FutureBooster.js
- test/server/cards/06-WoE/FutureBooster.spec.js
> WoE: implement Future Booster

- server/game/cards/06-WoE/SV3Lander.js
- test/server/cards/06-WoE/SV3Lander.spec.js
> WoE: implement SV3 Lander

- server/game/cards/06-WoE/CurseOfForgetfulness.js
- server/game/cards/06-WoE/EctoCharge.js
- test/server/cards/06-WoE/CurseOfForgetfulness.spec.js
- test/server/cards/06-WoE/EctoCharge.spec.js
> WoE - Anomalies

- server/game/Card.js
- server/game/cards/06-WoE/Bryozoarch.js
- test/server/cards/06-WoE/Bryozoarch.spec.js
> WoE: implement Bryozoarch

- server/game/cards/06-WoE/OfferingToKiligog.js
- server/game/cards/06-WoE/SpaceInvaders.js
- test/helpers/playerinteractionwrapper.js
- test/server/cards/06-WoE/OfferingToKiligog.spec.js
- test/server/cards/06-WoE/SpaceInvaders.spec.js
> WoE: implement Offering to Kiligog

- server/game/cards/06-WoE/SarielTheSteadfast.js
- test/server/cards/06-WoE/SarielTheSteadfast.spec.js
https://github.com/keyteki/keyteki/issues/3182
> Woe: implement Sariel the Steadfast

- server/game/cards/06-WoE/TimotiTheDammed.js
- test/server/cards/06-WoE/TimotiTheDammed.spec.js
> WoE: implement Timoti the Dammed

- server/game/cards/06-WoE/Flounderight.js
- server/game/cards/06-WoE/Soleft.js
- test/server/cards/06-WoE/Flounderight.spec.js
> WoE: implement Flounderight and fix Soleft

- server/game/cards/06-WoE/SunkCost.js
- test/server/cards/06-WoE/SunkCost.spec.js
> WoE: implement Sunk Cost

- server/game/cards/06-WoE/SibylWaimare.js
- test/server/cards/06-WoE/SibylWaimare.spec.js
> WoE: implement Sibyl Waimare

- server/game/cards/06-WoE/OstentatiousMount.js
- test/server/cards/06-WoE/OstentatiousMount.spec.js
> WoE: implement Ostentatious Mount

- server/game/cards/06-WoE/ZephonTheOpulent.js
- test/server/cards/06-WoE/ZephonTheOpulent.spec.js
> WoE: implement Zephon the Opulent

- server/game/cards/06-WoE/HaloOfEnlightenment.js
- test/server/cards/06-WoE/HaloOfEnlightenment.spec.js
> WoE: Implement Halo of Enlightenment

- server/game/cards/06-WoE/CollectorBoren.js
- test/server/cards/06-WoE/CollectorBoren.spec.js
Depends on https://github.com/keyteki/keyteki-json-data/pull/62 .
Issue: #2906
> WoE: implement Collector Boren

- server/game/cards/06-WoE/Plunder.js
- test/server/cards/06-WoE/Plunder.spec.js
> WoE: implement Plunder

- server/game/cards/06-WoE/BlorbHive.js
- server/game/cards/06-WoE/Cultist.js
- server/game/cards/06-WoE/PrimordialVault.js
- server/game/cards/06-WoE/Tangaika.js
- test/server/cards/06-WoE/Cultist.spec.js
- test/server/cards/06-WoE/PrimordialVault.spec.js
- test/server/cards/06-WoE/Tangaika.spec.js
> WoE: implement Primordial Vault, Tangaika, and finish Cultist

- server/game/cards/06-WoE/UncommonCurrency.js
- test/server/cards/06-WoE/UncommonCurrency.spec.js
> Uncommon Currency

- server/game/cards/06-WoE/BrikkNastee.js
- test/server/cards/06-WoE/BrikkNastee.spec.js
- test/server/cards/06-WoE/CelestialGorm.spec.js
- test/server/cards/06-WoE/ColonelMariana.spec.js
- test/server/cards/06-WoE/EchoReflector.spec.js
Updating cards and tests for:
https://github.com/keyteki/keyteki/issues/2911
Changes:
* fixed Brik Nastee (was giving amber when Brik was fighting)
* added test cards for Celestial Gorm, Colonel Mariana, Echo Reflector, Brikk Nastee
* Test cases passed
* Lint passed
> add fix Autogenerated  cards

- server/game/GameActions.js
- server/game/GameActions/CardListSelector.js
- server/game/GameActions/SequentialCardLastingEffectAction.js
- server/game/GameActions/index.js
- server/game/cards/06-WoE/MagistrateCrispus.js
- test/server/cards/06-WoE/MagistrateCrispus.spec.js
> WoE: implement Magistrate Crispus

- server/game/cards/06-WoE/CatchAndRelease.js
- test/server/cards/06-WoE/CatchAndRelease.spec.js
> WoE: implement Catch and Release

- server/game/CardSelectors/BaseCardSelector.js
- server/game/cards/06-WoE/RecordedHistory.js
- test/server/cards/06-WoE/RecordedHistory.spec.js
> WoE: implement Recorded History

- server/game/GameActions/LastingEffectAction.js
- server/game/cards/06-WoE/WatchYourStep.js
- test/server/cards/06-WoE/WatchYourStep.spec.js
Took @strib implementation and effect the 'then' property.
Overrides https://github.com/keyteki/keyteki/pull/3201
> Watch your Step

- server/game/Card.js
- server/game/GameActions/FightGameAction.js
- server/game/GameActions/ResolveFightAction.js
- server/game/cards/06-WoE/EndlessHordes.js
- server/game/effects.js
- test/server/cards/06-WoE/EndlessHordes.spec.js
> WoE: implement Endless Hordes

- server/game/cards/06-WoE/GedHammer.js
- test/server/cards/06-WoE/Fish.spec.js
- test/server/cards/06-WoE/ForcedRetirement.spec.js
- test/server/cards/06-WoE/FreshMarks.spec.js
- test/server/cards/06-WoE/GedHammer.spec.js
Updating cards and tests for:
https://github.com/keyteki/keyteki/issues/2911
Changes:
* fixed Gen Hammer (was only applying effect to itself)
* added tests for Fish, Forced Retirement, Fresh Marks, Ged Hammer
* Test cases passed
* Lint passed
> add fix Autogenerated cards

- server/game/GameActions.js
- server/game/GameActions/MoveUpgrade.js
- server/game/GameActions/index.js
- server/game/cards/06-WoE/BigMagnet.js
- test/server/cards/06-WoE/BigMagnet.spec.js
Used the code fro #3222, but created a MoveUpgrades action, tests passed
> Big Magnet

- server/game/cards/06-WoE/Grondal.js
- test/server/cards/06-WoE/Grondal.spec.js
> WoE: fix Grondal to destroy least powerful creature

- test/server/cards/06-WoE/Prospector.spec.js
> add Prospector test

- test/server/cards/06-WoE/PaxSauriana.spec.js
> add Pax Sauriana test

- server/game/Card.js
- server/game/Effects/Values/CopyCard.js
- test/server/cards/03-WC/MimicGel.spec.js
- test/server/cards/03-WC/WildSpirit.spec.js
- test/server/cards/06-WoE/Prospector.spec.js
- test/server/cards/06-WoE/Raider.spec.js
Fixes https://github.com/keyteki/keyteki/issues/3241
> Fixes ability sticking to token creatures after they are destroyed

- server/game/cards/06-WoE/RampagingBrutodon.js
- test/server/cards/06-WoE/RampagingBrutodon.spec.js
Not sure how I missed this before...
> WoE: give Rampaging Brutodon its play ability

- client/Components/Games/NewGame.jsx
- client/Components/Games/TournamentLobby.jsx
for https://github.com/keyteki/keyteki/issues/3266
> change default time limit to 45

- server/game/GameActions/MakeTokenCreatureAction.js
- server/game/GameActions/PutIntoPlayAction.js
- test/helpers/integrationhelper.js
- test/helpers/playerinteractionwrapper.js
- test/server/tokens.spec.js
Fixes #3079
Adds xit test for #3241
> WoE: token test and fix for token-making prompt image

- server/game/cards/06-WoE/MirrorShell.js
- test/server/cards/06-WoE/MirrorShell.spec.js
> WoE: implement Mirror Shell

- server/game/GameActions.js
- server/game/GameActions/SequentialMakeTokenCreatureAction.js
- server/game/GameActions/index.js
- server/game/cards/06-WoE/OfferingToKiligog.js
- test/server/cards/06-WoE/OfferingToKiligog.spec.js
- test/server/cards/06-WoE/SpaceInvaders.spec.js
Suggested by romanogit.
Issue: https://github.com/keyteki/keyteki/pull/3173
> WoE: rework Offering to Kiligog with sequential plays

- client/Components/GameBoard/GameBoard.jsx
- client/Components/GameBoard/GameBoard.scss
- server/game/player.js
Adds each player's token to the side pane.
> Woe side pane

- server/game/cards/06-WoE/ExtrematodeInfection.js
- test/server/cards/06-WoE/ExtrematodeInfection.spec.js
> Fix Extrematode Infection

- server/game/cards/06-WoE/NirborFlamewing.js
- server/game/game.js
- test/server/cards/06-WoE/NirborFlamewing.spec.js
> WoE: implement Nirbor Flamewing

- server/game/cards/06-WoE/Befuddle.js
> add `effectAlert` to Befuddle

- server/game/cards/06-WoE/FeatsOfStrength.js
- server/game/cards/06-WoE/RampagingBrutodon.js
> WoE: small fixes for Feats of Strength and Rampgaing Brutodon

- server/game/cards/06-WoE/Researcher.js
- test/server/cards/06-WoE/Researcher.spec.js
> WoE: Researcher can archive any Mars card

- server/game/cards/06-WoE/Sandhopper.js
- test/server/cards/06-WoE/Sandhopper.spec.js
> WoE: fix Sandhopper picking opponent creatures

- test/server/cards/06-WoE/TalentScout.spec.js
> WoE: add a test for Bubbles + Talent Scout

- server/game/cards/06-WoE/RecordedHistory.js
> WoE: Recorded History should reveal the cards

- server/game/deck.js
> fixes pyro image

- server/game/cards/06-WoE/BrawlIn.js
- test/server/cards/06-WoE/BrawlIn.spec.js
And don't use pre-enraged tokens in the test.
> WoE: Brawl In should enrage newly-made tokens

- server/game/cards/06-WoE/ClosedDoorNegotiation.js
- test/server/cards/06-WoE/ClosedDoorNegotiation.spec.js
> WoE: fixed Closed-Door when stealing is prevented

- server/game/player.js
- test/server/cards/06-WoE/Amberling.spec.js
> WoE: fix Amberling edge cases

- server/game/GameActions/RevealAction.js
- server/game/cards/06-WoE/NearFutureLens.js
> Don't default to facedown=true in RevealAction

- server/game/cards/06-WoE/TheVisibleHand.js
@strib, @cryogen 
I implemented the change from "The Visible Hand" without the introduced flag.
I am thinking about Space Invaders
> The visible hand implemented without the "always" flag

- server/game/GameActions/ResolveFightAction.js
- test/server/cards/06-WoE/CrimTorchtooth.spec.js
> Splash attack should fire even when fighting an elusive creature

- server/game/cards/06-WoE/FriendlyGuide.js
- test/server/cards/06-WoE/FriendlyGuide.spec.js
> WoE: Friendly Guide should only work for controller

- server/game/cards/06-WoE/EndlessHordes.js
- test/server/cards/06-WoE/EndlessHordes.spec.js
> WoE: fix Endless Hordes when multiple enemies have same name

- server/game/cards/06-WoE/ShizyokuBuggy.js
- test/server/cards/06-WoE/ShizyokuBuggy.spec.js
Just noticed that I completely missed this restriction in the card text.
> WoE: add constraint to discarded card for Shĭzyokŭ Buggy

- server/game/cards/06-WoE/FriendlyGuide.js
- test/server/cards/06-WoE/FriendlyGuide.spec.js
> WoE: Friendly Guide can be used when neighbors dies during use

- server/game/cards/06-WoE/ExtrematodeInfection.js
- test/server/cards/06-WoE/ExtrematodeInfection.spec.js
> WoE: fix Extrematode Infection with wards

- server/game/cards/06-WoE/PullUpStakes.js
> WoE: Shuffle for Pull Up Stakes

- server/game/Card.js
> Fix tokenCard() being null

- client/Components/GameBoard/Card.jsx
- client/Components/GameBoard/CardImage.jsx
- client/Components/GameBoard/PlayerBoard.jsx
- client/archonMaker.js
- server/game/Card.js
- server/game/CardVisibility.js
- server/game/GameActions/FlipAction.js
- server/game/deck.js
- server/game/gamechat.js
- server/game/player.js
- test/helpers/integrationhelper.js
Refactors how tokenCard is sent to UI
Fixes #3314
Fixes #3318 
Fixes #3445 
Fixes #3454
> Fixes half-sized token

- client/archonMaker.js
same change was done for power
> Fix misplace of token armor in 1/2 images

- server/game/cards/01-Core/AnnihilationRitual.js
- server/game/player.js
- test/server/cards/01-Core/AnnihilationRitual.spec.js
> Fix Annihilation Ritual and token creatures

- server/game/cards/06-WoE/RagnarokPrep.js
> Ajdust Ragnaork Prep lose 2A message

- server/services/DeckService.js
> Fixes maverick and anomaly in alliance

- server/game/cards/01-Core/SoulSnatcher.js
- test/server/cards/01-Core/SoulSnatcher.spec.js
> Fixes soul snatcher and tokens

- server/game/costs.js
- test/server/cards/06-WoE/RampagingBrutodon.spec.js
> Fixes Rampaging Brutodon and cost

- server/game/cards/06-WoE/SunkCost.js
- test/server/cards/06-WoE/SunkCost.spec.js
> Sunk Cost should allow any house

- server/game/cards/01-Core/PingleWhoAnnoys.js
- server/game/player.js
- test/server/cards/01-Core/Autocannon.spec.js
- test/server/cards/01-Core/PingleWhoAnnoys.spec.js
> Fix Pingle dealing damage to own creature on opponent's turn

- server/services/DeckService.js
Such as It's Coming and DAV
Fixes #2952
> Fixes cards with multiple houses in Alliance

- server/game/cards/06-WoE/RampagingBrutodon.js
- server/game/cards/06-WoE/RevnaStarsong.js
> Fixes Revna applying to opponent

- test/server/cards/03-WC/TheGrimReaper.spec.js
- test/server/cards/07-GR/AwfulAtoll.spec.js
- test/server/cards/07-GR/ChokingIvy.spec.js
- test/server/cards/07-GR/DarkHeartOfTheForest.spec.js
- test/server/cards/07-GR/GhostTree.spec.js
- test/server/cards/07-GR/GravePixie.spec.js
- test/server/cards/07-GR/HauntingWitch.spec.js
- test/server/cards/07-GR/LostInTheWild.spec.js
- test/server/cards/07-GR/SkeletalMurmook.spec.js
- test/server/cards/07-GR/TheCircleOfLife.spec.js
> GR: improve haunted tests readability

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/vi.json
- public/locales/zhhans.json
- public/locales/zhhant.json
Now I remember why I used "deal damage" originally...
> GR: fix Returning Champion message locales

- server/game/cards/07-GR/AncestralTimekeeper.js
- server/game/cards/07-GR/Chronometer.js
- server/game/cards/07-GR/Synchronizer.js
- server/game/cards/07-GR/TickTock.js
- test/server/cards/07-GR/AncestralTimekeeper.spec.js
- test/server/cards/07-GR/Chronometer.spec.js
- test/server/cards/07-GR/Synchronizer.spec.js
- test/server/cards/07-GR/TickTock.spec.js
Tick-Tock, Chronometer, Ancestral Timekeeper and Synchronizer.
> GR: implement the clock suite

- server/game/cards/07-GR/ShrinkRayTechnician.js
- test/server/cards/07-GR/ShrinkRayTechnician.spec.js
> GR: fix Shrink-Ray Technician to only apply to target

- server/game/cards/07-GR/Kaspara.js
- test/server/cards/07-GR/Kaspara.spec.js
> server: fix Kaspara granting an ability from the archives

- server/game/cards/07-GR/Glimmerspore.js
- test/server/cards/07-GR/Glimmerspore.spec.js
> GR: fix Glimmerspore archiving self-controller, opp-owned artifacts

- server/game/cards/07-GR/CursedTomb.js
- test/server/cards/07-GR/CursedTomb.spec.js
> GR: Cursed Tomb purges itself when there are no creatures in play

- server/game/cards/07-GR/DownToSize.js
- test/server/cards/07-GR/DownToSize.spec.js
> GR: Down to Size should only affect enemy creatures

- server/game/cards/07-GR/MissChievous.js
The trueGameAction is evaulated even if the conditional fails.
> GR: fix Miss Chevious for solo play

- server/game/GameActions/PlaceUnderAction.js
- test/server/cards/07-GR/Cauldron.spec.js
> GR: Cauldron should trigger Near-Future Lens on its action

- server/game/cards/07-GR/WellOfMemory.js
- test/server/cards/07-GR/WellOfMemory.spec.js
> GR: Well of Memory should only let you return your own cards

- server/game/cards/07-GR/CurseOfFertility.js
> GR: fix Curse of Fertility message

- package-lock.json
- package.json
- server/api/account.js
> Fix crash on logout

- server/game/cards/07-GR/FlyingBroomstick.js
- test/server/cards/07-GR/FlyingBroomstick.spec.js
> GR: Flying Broomstick can target any creature in play

- server/game/cards/07-GR/IhakaOfTheDepths.js
- test/server/cards/07-GR/IhakaOfTheDepths.spec.js
> GR: Ihaka should not trigger on your turn when opponent draws

- server/game/cards/06-WoE/UncommonCurrency.js
- test/server/cards/06-WoE/UncommonCurrency.spec.js
> WoE: Uncommon Currency should do nothing with no enemy artifacts

- server/game/cards/06-WoE/EctoCharge.js
- server/game/cards/06-WoE/ScoopUp.js
- server/game/cards/07-GR/Cauldron.js
- server/game/cards/07-GR/IntoTheWarp.js
- test/server/cards/06-WoE/EctoCharge.spec.js
- test/server/cards/06-WoE/ScoopUp.spec.js
- test/server/cards/07-GR/Cauldron.spec.js
* Ecto-Charge back to a minimum of 6
* Scoop Up allows you to archive friendly opponent-owned creatures
* Text change for Into the Warp (no code change needed)
* Cauldron lets you play all cards under it.
> MRB v17.3 updates

- server/services/DeckService.js
> Fix GR cards that used to be anomalies

- server/db/schema/99 - Data.sql
- server/db/schema/migrations/11 - AS.sql
Are we spelling it Aember Skies or Aember Skies in the database? ---> I checked the json, it's Æmber Skies
> database migration for aember skies & corresponding data inserts

- server/game/cards/08-AS/IntentionalDischarge.js
- test/server/cards/08-AS/IntentionalDischarge.spec.js
It needs the house enhancement. IDK how to do that.
> AS: Intentional Discharge (Mars)

- server/game/cards/08-AS/CrimsonDax.js
- test/server/cards/08-AS/CrimsonDax.spec.js
So I think technically this should use the "reveal" game action. Maybe I can use the sequential thing there, and that would do the trick...
> AS: implement Crimson Dax (Mars)

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/th.json
- public/locales/vi.json
- public/locales/zhhans.json
- public/locales/zhhant.json
- server/game/cards/08-AS/HarmonicPack.js
- test/server/cards/08-AS/HarmonicPack.spec.js
Based on #4006 , cc @dgbrokaw .
> AS: implement Harmonic Pack

- server/game/cards/08-AS/TyrannusAquilae.js
- test/server/cards/08-AS/Akugyo.spec.js
- test/server/cards/08-AS/AlienPuffer.spec.js
- test/server/cards/08-AS/AnvilCrawler.spec.js
- test/server/cards/08-AS/Beehemoth.spec.js
- test/server/cards/08-AS/BlueAmberdrake.spec.js
- test/server/cards/08-AS/Colossipede.spec.js
- test/server/cards/08-AS/GrizzledWyvern.spec.js
- test/server/cards/08-AS/Icarus20.spec.js
- test/server/cards/08-AS/Impzilla.spec.js
- test/server/cards/08-AS/Lancet.spec.js
- test/server/cards/08-AS/MalifiDragon.spec.js
- test/server/cards/08-AS/Naja.spec.js
- test/server/cards/08-AS/RedAmberdrake.spec.js
- test/server/cards/08-AS/Rorqual.spec.js
- test/server/cards/08-AS/Screeyan.spec.js
- test/server/cards/08-AS/SentientCloud.spec.js
- test/server/cards/08-AS/Titanarpon.spec.js
- test/server/cards/08-AS/TyrannusAquilae.spec.js
- test/server/cards/08-AS/Volax.spec.js
Depends on keyteki/keyteki-json-data#76
> AS: Implement Tyrannus Aquilae (and update Skybeast houses)

- server/game/cards/08-AS/Tangrant.js
- test/server/cards/08-AS/Tangrant.spec.js
I think this is literally Mars Witch of the Wilds in terms of effects. So, I was lazy and didn't add tests.
> AS: implement Tangrant (Mars)

- server/game/cards/08-AS/SeekerMissiles.js
- test/server/cards/08-AS/SeekerMissiles.spec.js
> AS: Seeker Missles should count opponent flank Skyborns

- server/game/cards/09-ToC/TheAmasser.js
- server/game/player.js
- test/server/cards/09-ToC/TheAmasser.spec.js
And make `deployIndex == -1` to put creatures on the right flank.
> ToC: implement The Amasser 

- server/game/cards/08-AS/RainceFuryheart.js
- test/server/cards/08-AS/RainceFuryheart.spec.js
> AS: Raince Furyheart is a "before fight" effect

- server/game/cards/01-Core/EpicQuest.js
> Fix Epic Quest log message

- server/game/cards/06-WoE/CornerTheMarket.js
- test/server/cards/06-WoE/CornerTheMarket.spec.js
> Fix Corner the Market to allow scrap effects due to new wording

- server/game/cards/08-AS/ClapOfThunder.js
- test/server/cards/08-AS/ClapOfThunder.spec.js
> AS: fix Clap of Thunder when creature is not destroyed

- server/game/cards/08-AS/OnTheMark.js
> AS: fix On the Mark to require only one creature each

- server/game/cards/08-AS/SentientCloud.js
- test/server/cards/08-AS/SentientCloud.spec.js
It could be have been turned into an artifact by De-Animator
> AS: fix Sentient Cloud when there are no creatures

- server/game/cards/08-AS/RedSkies.js
- test/server/cards/08-AS/RedSkies.spec.js
> AS: fix Red Skies for _any_ red key forged

- server/game/cards/08-AS/TalonOfInvidius.js
> AS: fix Talon of Individius to work with one enemy creature

- server/game/cards/08-AS/DeDoss.js
- test/server/cards/08-AS/DeDoss.spec.js
> AS: fix De-Doss when a creature in play is playing another creature

- server/game/GameActions/PutIntoPlayAction.js
- server/game/GameActions/SequentialPutIntoPlayAction.js
- server/game/cards/08-AS/Skollenbuzzz.js
- test/server/cards/08-AS/Skollenbuzzz.spec.js
> AS: Skollenbuzzz should put creatures into play for controller

- server/game/cards/09-ToC/Harlock.js
- test/server/cards/09-ToC/Harlock.spec.js
I'm not sure why the fight effect condition is being evaluated on play, but it is, and this fixes it.
> ToC: fix Harlock

- server/game/cards/09-ToC/BumpInTheNight.js
Not sure how this can happen though, so wasn't able to write a test for it.
> ToC: fix Bump in the Night for when there's no pre-event

- server/game/cards/09-ToC/Minion.js
- test/server/cards/09-ToC/Minion.spec.js
> ToC: fix Minion to do nothing when no one is haunted

- server/game/cards/09-ToC/VaultOfRedemption.js
- test/server/cards/09-ToC/VaultOfRedemption.spec.js
> ToC: fix Vault of Redemption to look at clone traits

- server/game/cards/08-AS/BarterAndGames.js
> AS: Barter and Games was printing the wrong revealed first card

- server/services/DeckService.js
> ToC: correct default houses for all the sacro- mutants

- test/server/cards/08-AS/DeAnimator.spec.js
Seems to be working as intended after someone mentioned it might be buggy.  Might as well have a test for it.
> AS: add a De-Animator test for stacked Actions

- server/game/cards/09-ToC/Redhawk.js
- test/server/cards/09-ToC/Redhawk.spec.js
> ToC: implement Redhawk

- test/server/cards/07-GR/MarketFluctuation.spec.js
> GR: improve Market Fluctuation tests

- server/game/BaseActions/ReturnToHandFromDiscardAction.js
- server/game/Card.js
- server/game/cardaction.js
- test/server/cards/07-GR/SingingScythe.spec.js
The `returnToHandFromDiscard` effect shouldn't count towards the rule-of-6.
> GR: Singing Scythe return-to-hand isn't affected by Ro6

- server/game/cards/08-AS/FlintsLegend.js
- test/server/cards/08-AS/FlintsLegend.spec.js
> hAS: fix Flint's Legend when opponent has no amber

- server/game/cards/01-Core/AnnihilationRitual.js
- server/game/cards/08-AS/FlintsMap.js
- test/server/cards/01-Core/AnnihilationRitual.spec.js
- test/server/cards/01-Core/SpanglerBox.spec.js
After it was fixed in the master vault API.
> Fix Annihilation Ritual card ID

- server/services/DeckService.js
> server: mark gigantic tops using the new API card type for them

- server/game/cards/08-AS/RecreationalJettison.js
- test/server/cards/08-AS/RecreationalJettison.spec.js
> AS: Recreational Jettison should look at opponent keys too

- server/game/cards/08-AS/TreasureIsland.js
- test/server/cards/08-AS/TreasureIsland.spec.js
> AS: Treasure Island moves amber from pool, not creature

- server/game/cards/07-GR/DontBelieveYourEyes.js
- test/server/cards/07-GR/DontBelieveYourEyes.spec.js
> Allow capturing no amber with Don't Believe Your Eyes

- client/constants.js
- server/constants.js
- server/db/schema/99 - Data.sql
- server/db/schema/migrations/14 - Discovery.sql
There are no new cards in this set.
> Add support for Discovery

- client/constants.js
- server/constants.js
- server/db/schema/99 - Data.sql
- server/db/schema/migrations/14 - Discovery.sql
> Revert "Add support for Discovery"

- client/Components/GameBoard/GameBoard.jsx
- server/game/Card.js
- server/game/GameActions.js
- server/game/GameActions/ActivateProphecyAction.js
- server/game/GameActions/DeactivateProphecyAction.js
- server/game/GameActions/ResolveFateAction.js
- server/game/GameActions/index.js
- server/game/MenuCommands.js
- server/game/game.js
- server/game/player.js
- test/server/manualmode/prophecy-menu.spec.js
Allow for prophecy activation/deactivation/triggering via manual mode.
> PV: manual mode prophecy commands

- server/game/GameActions/FulfillProphecyAction.js
So it will show in the chat.
Fixes: #4506
> PV: make fate card faceup before resolving

- server/game/GameActions/ReturnToDeckAction.js
- server/game/cards/05-DT/BrainDrain.js
> PV: don't log cards returned to deck from a hidden zone

- server/game/cards/12-PV/Reiteration.js
> PV: fix Reiteration log message

- server/game/cards/08-AS/DeDoss.js
- test/server/cards/08-AS/DeDoss.spec.js
> Fix De-Doss to allow playing creatures as upgrades

- server/game/cards/02-AoA/PersistenceHunting.js
- test/server/cards/12-PV/DisabledSecurity.spec.js
Instead of the controller of Persistence Hunting's opponent.
> Fix Persistence Hunting to affect player's opponent

- server/game/cards/12-PV/NamelsConfession.js
- test/server/cards/12-PV/NamelsConfession.spec.js
> PV: fix Namel's Confession to use clone's modified power

- client/Components/Decks/DeckSummary.jsx
- client/pages/AllianceBuilder.jsx
- client/redux/reducers/cards.js
- server/api/decks.js
- server/services/DeckService.js
And fix small bug with dup tokens with alliance pods.
> PV: allow prophecies for alliance decks

- server/game/cards/12-PV/CursedLoot.js
- test/server/cards/12-PV/CursedLoot.spec.js
> PV: Cursed Loot should destroy after play, even w/o discarding

- server/game/cards/12-PV/Lithomancy.js
- test/server/cards/12-PV/Lithomancy.spec.js
> PV: fix Lithomancy to discard the card

- server/game/cards/12-PV/ResonantOrb.js
> PV: fix Resonant Orb to log second discarded card

- README.md
- server/game/game.js
- server/game/gamesteps/GameWonPrompt.js
- server/game/gamesteps/RematchWithNewDecksPrompt.js
- server/gamenode/gameserver.js
- server/gamerouter.js
- server/lobby.js
- Adds "Rematch with new decks" extra option on final prompt when match has ended
- Sends both users back to lobby to pick new decks for the match
- Adds few Readme points regarding setting up locally, specially for MACOS
- Fixes lint
> adds rematch with new decks, few readme addings and lint fixes

- server/game/cards/12-PV/WastefulRegret.js
- test/server/cards/12-PV/WastefulRegret.spec.js
> PV: fix Wasteful Regret to not trigger on own discard

- server/game/cards/12-PV/GovernessSilvina.js
- test/server/cards/12-PV/GovernessSilvina.spec.js
Previously it would remove the amber completely.
> PV: fix Governess Silvina when there are no enemy creatures

- server/game/Card.js
- server/game/cards/12-PV/GleamingTheCube.js
- server/game/cards/12-PV/RuthlessAvenger.js
- server/game/cards/12-PV/StrategicFeint.js
- server/game/cards/12-PV/Tealnar.js
> PV: highlight fate effects

- server/game/cards/07-GR/Warfaline.js
- test/helpers/playerinteractionwrapper.js
- test/server/cards/07-GR/Warfaline.spec.js
- test/server/cards/cancreatecards.spec.js
> Log which cards are shuffled by Warfaline

- server/game/GameActions/DiscardCardAction.js
- test/server/cards/12-PV/Ifraneye.spec.js
> Allow ordering of discards when there is a scrap effect

- server/game/GameActions/DiscardCardAction.js
- server/game/cards/06-WoE/ShoppingSpree.js
- server/game/cards/07-GR/Plummet.js
- server/game/cards/08-AS/InfernalTerran.js
- server/game/cards/12-PV/CrypticCollapse.js
- server/game/cards/12-PV/HazardZerp.js
- test/server/cards/08-AS/InfernalTerran.spec.js
> Fix discard events when scrap order is chosen

- server/game/GameActions/ChangeActiveHouse.js
- server/game/cards/03-WC/BookOfLeq.js
- test/server/cards/03-WC/BookOfLeq.spec.js
> Fix BookOfLeq to handle house-pipped cards correctly

- server/game/GameActions/RandomDiscardAction.js
- test/server/cards/03-WC/NogiSmartfist.spec.js
- test/server/cards/09-ToC/TheForsaken.spec.js
To allow for scrap abilities that could change the cards in hand before the next random discard.
> Random discards should happen one at a time

- server/game/cards/12-PV/OutlookNotSoGood.js
- test/server/cards/12-PV/OutlookNotSoGood.spec.js
> PV: fix Outlook Not So Good for upgrades

- server/game/cards/03-WC/UnitedAction.js
- test/server/cards/03-WC/UnitedAction.spec.js
fix: United Action should handle upgrade controller changes - not owner #4635
> fix: United Action should handle upgrade controller changes

- server/game/cards/07-GR/AnimatingForce.js
- test/server/cards/07-GR/AnimatingForce.spec.js
fix: Animating Force when control changes by adding versatile - fixes #4379
> fix: Animating Force when control changes

- server/game/cards/13-CC/Badger.js
- test/server/cards/13-CC/Badger.spec.js
fix: Badger should trigger after playing Badger - fixes #4644
> fix: Badger should trigger after playing Badger
